//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSDate, NSNumber, NSSet, NSString;

@interface CLSArchiveFile : NSManagedObject
{
}

@property (strong, nonatomic) NSSet *clues; // @dynamic clues;
@property (strong, nonatomic) NSString *contextURI; // @dynamic contextURI;
@property (strong, nonatomic) NSDate *creationDate; // @dynamic creationDate;
@property (strong, nonatomic) NSDate *endDate; // @dynamic endDate;
@property (strong, nonatomic) NSNumber *fixedLocation1Distance; // @dynamic fixedLocation1Distance;
@property (strong, nonatomic) NSNumber *fixedLocation2Distance; // @dynamic fixedLocation2Distance;
@property (strong, nonatomic) NSNumber *fixedLocation3Distance; // @dynamic fixedLocation3Distance;
@property (strong, nonatomic) NSDate *lastModificationDate; // @dynamic lastModificationDate;
@property (strong, nonatomic) NSDate *startDate; // @dynamic startDate;
@property (strong, nonatomic) NSString *uuid; // @dynamic uuid;

- (id)_cluesForPredicate:(id)arg1 prefetchPrimitives:(BOOL)arg2;
- (id)cluesForKeys:(id)arg1 prefetchPrimitives:(BOOL)arg2;
- (id)debugArchiveCluesWithPrefetchedPrimitives:(BOOL)arg1;
- (id)description;
- (id)inputArchiveCluesWithPrefetchedPrimitives:(BOOL)arg1;
- (id)meaningArchiveCluesWithPrefetchedPrimitives:(BOOL)arg1;
- (id)nonInputArchiveCluesWithPrefetchedPrimitives:(BOOL)arg1;
- (id)outputArchiveCluesWithPrefetchedPrimitives:(BOOL)arg1;

@end

