//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <CoreMotion/NSCopying-Protocol.h>

@class CMAttitude;

@interface CMDeviceMotionInternal : NSObject <NSCopying>
{
    CDStruct_31142d93 fGravity;
    CDStruct_31142d93 fUserAcceleration;
    CDStruct_31142d93 fRotationRate;
    CMAttitude *fAttitude;
    CDStruct_31142d93 fMagneticField;
    int fMagneticFieldCalibrationLevel;
    BOOL fDoingYawCorrection;
    BOOL fDoingBiasEstimation;
    float fHeading;
    float fHeadingAccuracy;
    long long fSensorLocation;
}

- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithDeviceMotion:(CDStruct_69e6d857)arg1 internal:(CDStruct_37a3040a)arg2;
- (BOOL)isEqual:(id)arg1;
- (void)setDeviceMotion:(CDStruct_69e6d857)arg1 internal:(CDStruct_37a3040a)arg2;

@end

