//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SleepDaemon/NSObject-Protocol.h>

@class NSDate;
@protocol HDSPEventScheduleDelegate;

@protocol HDSPEventScheduler <NSObject>

@property (weak, nonatomic) id<HDSPEventScheduleDelegate> delegate;

- (void)scheduleEventForDate:(NSDate *)arg1 options:(unsigned long long)arg2;
- (void)unschedule;
@end

