//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TrialProto/TRIPBMessage.h>

@interface TRIPBUInt64Value : TRIPBMessage
{
}

@property (nonatomic) unsigned long long value; // @dynamic value;

+ (id)descriptor;

@end

