//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreImage/CIFilter.h>

@class CIImage, NSNumber;

@interface PIHighKeyHDR : CIFilter
{
    CIImage *inputImage;
    NSNumber *inputStrength;
}

@property (strong, nonatomic) CIImage *inputImage; // @synthesize inputImage;
@property (strong, nonatomic) NSNumber *inputStrength; // @synthesize inputStrength;

+ (id)customAttributes;
- (void).cxx_destruct;
- (id)_highKeyHDR;
- (id)outputImage;

@end

