//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <LinkPresentation/LPComponentView.h>

@class LPImageViewStyle, NSArray, NSMutableArray;

__attribute__((visibility("hidden")))
@interface LPMultipleImageView : LPComponentView
{
    NSArray *_images;
    LPImageViewStyle *_style;
    NSMutableArray *_imageViews;
}

- (void).cxx_destruct;
- (struct CGSize)_availableSizeForImageNumber:(unsigned long long)arg1 withLayout:(unsigned long long)arg2 withinSize:(struct CGSize)arg3;
- (struct CGRect)_computeRectForImageAtIndex:(unsigned long long)arg1 fittingSize:(struct CGSize *)arg2 width:(double *)arg3 height:(double *)arg4 size:(struct CGSize)arg5 multipleImageLayout:(unsigned long long)arg6;
- (void)ensureImageViews;
- (id)init;
- (id)initWithImages:(id)arg1 style:(id)arg2;
- (void)layoutComponentView;
- (struct CGSize)layoutImagesForSize:(struct CGSize)arg1 applyingLayout:(BOOL)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

