//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PrototypeTools/PTSRow.h>

@interface PTSDrillDownRow : PTSRow
{
}

+ (id)rowWithTitle:(id)arg1 childSettingsKeyPath:(id)arg2;
+ (id)rowWithTitleKeyPath:(id)arg1 childSettingsKeyPath:(id)arg2;
- (id)init;
- (Class)rowTableViewCellClass;

@end

