//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <TextInput/NSCopying-Protocol.h>
#import <TextInput/NSMutableCopying-Protocol.h>
#import <TextInput/NSSecureCoding-Protocol.h>

@class NSCharacterSet, NSString;

@interface TICharacterSetDescription : NSObject <NSCopying, NSMutableCopying, NSSecureCoding>
{
    NSCharacterSet *_characterSet;
    BOOL _inverted;
    long long _baseIdentifier;
    NSString *_charactersAddedToBase;
    NSString *_charactersRemovedFromBase;
}

@property (readonly, nonatomic) long long baseIdentifier; // @synthesize baseIdentifier=_baseIdentifier;
@property (readonly, nonatomic) NSCharacterSet *characterSet;
@property (copy, nonatomic) NSString *charactersAddedToBase; // @synthesize charactersAddedToBase=_charactersAddedToBase;
@property (copy, nonatomic) NSString *charactersRemovedFromBase; // @synthesize charactersRemovedFromBase=_charactersRemovedFromBase;
@property (readonly, nonatomic) BOOL inverted; // @synthesize inverted=_inverted;

+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (id)awakeAfterUsingCoder:(id)arg1;
- (void)clearCachedCharacterSet;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithBase:(long long)arg1 additionalCharacters:(id)arg2 removedCharacters:(id)arg3 inverted:(BOOL)arg4;
- (id)initWithBaseCharacterSet:(long long)arg1;
- (id)initWithCharactersInString:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)invertedSetDescription;
- (BOOL)isEqual:(id)arg1;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)newCharacterSetFromDescription;

@end

