//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <PromotedContent/APPCPromotableBlacklistReasonCharacteristic-Protocol.h>

@class MISSING_TYPE, NSArray;

@interface APPCBlacklistReasonCharacteristic : NSObject <APPCPromotableBlacklistReasonCharacteristic>
{
    MISSING_TYPE *globalCategories;
    MISSING_TYPE *globalKeywords;
    MISSING_TYPE *campaignCategories;
    MISSING_TYPE *campaignKeywords;
}

@property (nonatomic, copy) NSArray *campaignCategories;
@property (nonatomic, copy) NSArray *campaignKeywords;
@property (nonatomic, copy) NSArray *globalCategories;
@property (nonatomic, copy) NSArray *globalKeywords;

- (void).cxx_destruct;
- (id)init;
- (id)initWithGlobalCategories:(id)arg1 globalKeywords:(id)arg2 campaignCategories:(id)arg3 campaignKeywords:(id)arg4;

@end

