//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <MapsSuggestions/MapsSuggestionsStrategy-Protocol.h>

@class MapsSuggestionsManager, NSMutableArray, NSMutableSet, NSString;

@interface MapsSuggestionsSimpleStrategy : NSObject <MapsSuggestionsStrategy>
{
    NSMutableSet *_preFilters;
    NSMutableArray *_improvers;
    NSMutableArray *_dedupers;
    NSMutableSet *_postFilters;
    NSMutableArray *_previousResults;
    MapsSuggestionsManager *_manager;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (weak, nonatomic) MapsSuggestionsManager *manager; // @synthesize manager=_manager;
@property (readonly) Class superclass;
@property (readonly, nonatomic) NSString *uniqueName;

- (void).cxx_destruct;
- (void)_addFilter:(id)arg1 processingType:(long long)arg2;
- (BOOL)_dedupeByEnrichingEntries:(id)arg1 withEntry:(id)arg2;
- (BOOL)_entry:(id)arg1 existsInStorage:(id)arg2;
- (id)_filteredPreviousResultsCrosscheckingStorage:(id)arg1;
- (id)_filtersForprocessingType:(long long)arg1;
- (BOOL)_improveEntry:(id)arg1;
- (void)addDeduper:(id)arg1;
- (void)addImprover:(id)arg1;
- (void)addPostFilter:(id)arg1;
- (void)addPreFilter:(id)arg1;
- (void)clearData;
- (id)init;
- (BOOL)postFiltersKept:(id)arg1;
- (BOOL)preFiltersKept:(id)arg1;
- (void)removeAllDedupers;
- (void)removeAllFilters;
- (void)removeAllImprovers;
- (void)removeFilter:(id)arg1;
- (id)topSuggestionsWithSourceEntries:(id)arg1 error:(id *)arg2;

@end

