//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue, TUMetadataCacheDataProviderDelegate;

@interface TUMetadataCacheDataProvider : NSObject
{
    id<TUMetadataCacheDataProviderDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_concurrentQueue;
    NSMutableDictionary *_providerCache;
}

@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *concurrentQueue; // @synthesize concurrentQueue=_concurrentQueue;
@property (weak, nonatomic) id<TUMetadataCacheDataProviderDelegate> delegate; // @synthesize delegate=_delegate;
@property (readonly, nonatomic, getter=isEmpty) BOOL empty;
@property (readonly, nonatomic) NSMutableDictionary *providerCache; // @synthesize providerCache=_providerCache;

- (void).cxx_destruct;
- (id)description;
- (id)init;
- (id)metadataForDestinationID:(id)arg1;
- (void)refresh;
- (void)setObject:(id)arg1 forDestinationID:(id)arg2;
- (void)updateCacheWithDestinationIDs:(id)arg1 withGroup:(id)arg2;

@end

