//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AXAssetLoader/NSObject-Protocol.h>

@class NSDictionary, NSString;

@protocol AXAssetAssertion <NSObject>

@property (readonly, nonatomic) NSString *assetType;
@property (readonly, nonatomic) NSString *clientIdentifier;

+ (id)assertionWithPropertyListRepresentation:(NSDictionary *)arg1 error:(id *)arg2;
- (NSDictionary *)propertyListRepresentation;
@end

