//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol HAP2CoAPIOConsumer;

@interface HAP2CoAPIOConsumerWeakHolder : NSObject
{
    id<HAP2CoAPIOConsumer> _consumer;
}

@property (readonly, weak, nonatomic) id<HAP2CoAPIOConsumer> consumer; // @synthesize consumer=_consumer;

+ (id)new;
- (void).cxx_destruct;
- (id)init;
- (id)initWithConsumer:(id)arg1;

@end

