//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol OS_dispatch_source;

@interface HAPBTLEConnectionRequestTuple : NSObject
{
    NSObject<OS_dispatch_source> *_connectionRequestTimer;
    NSString *_identifier;
    unsigned long long _advertisementFormat;
}

@property (readonly, nonatomic) unsigned long long advertisementFormat; // @synthesize advertisementFormat=_advertisementFormat;
@property (readonly, nonatomic) NSObject<OS_dispatch_source> *connectionRequestTimer; // @synthesize connectionRequestTimer=_connectionRequestTimer;
@property (readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;

+ (id)connectionRequestTupleWithTimer:(id)arg1 identifier:(id)arg2 advertisementFormat:(unsigned long long)arg3;
- (void).cxx_destruct;

@end

