//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "__SBSearchEtceteraTodayLayoutContentViewAccessibility_super.h"

@interface SBSearchEtceteraTodayLayoutContentViewAccessibility : __SBSearchEtceteraTodayLayoutContentViewAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)_accessibilityLoadAccessibilityInformation;
- (void)setTodayListMajorScrollView:(id)arg1;
- (void)setTodayListMinorScrollView:(id)arg1;

@end

