//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "__SBUIIconForceTouchViewControllerAccessibility_super.h"

@interface SBUIIconForceTouchViewControllerAccessibility : __SBUIIconForceTouchViewControllerAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)_axDismissShortcutMenu;
- (BOOL)_axIsControlCenterVisible;
- (void)_presentAnimated:(BOOL)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (BOOL)accessibilityPerformEscape;
- (void)loadView;

@end

