//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;

@interface CKLargeTitleAccessoryView : UIView
{
    UIButton *_leftAccessoryButton;
    UIButton *_rightAccessoryButton;
}

@property (strong, nonatomic) UIButton *leftAccessoryButton; // @synthesize leftAccessoryButton=_leftAccessoryButton;
@property (strong, nonatomic) UIButton *rightAccessoryButton; // @synthesize rightAccessoryButton=_rightAccessoryButton;

+ (id)newComposeButton;
+ (id)newOptionsButton;
- (void).cxx_destruct;
- (struct CGSize)_intrinsicSizeWithinSize:(struct CGSize)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

