//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ChatKit/CKAbstractReviewTableViewCell.h>

@class CKAttachmentItem, UIImageView;

__attribute__((visibility("hidden")))
@interface CKReviewLargeAttachmentsTableViewCell : CKAbstractReviewTableViewCell
{
    UIImageView *_previewView;
    CKAttachmentItem *_attachmentItem;
}

@property (strong, nonatomic) CKAttachmentItem *attachmentItem; // @synthesize attachmentItem=_attachmentItem;
@property (strong, nonatomic) UIImageView *previewView; // @synthesize previewView=_previewView;

+ (struct CGSize)leftHandSideViewSize;
+ (double)requestedHeight;
- (void).cxx_destruct;
- (void)_updateImageViewForAttachmentItem;
- (id)leftHandSideView;
- (void)prepareForReuse;
- (void)setModelObject:(id)arg1;

@end

