//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSDate, NSString, UIDateLabel, UIImage, UIImageView, UILabel;

@interface CKStarkConversationListCell : UITableViewCell
{
    UIImage *_monogramImage;
    UIImageView *_unreadImageView;
    UILabel *_recipientsLabel;
    UIDateLabel *_dateLabel;
}

@property (strong, nonatomic) NSDate *date; // @dynamic date;
@property (strong, nonatomic) UIDateLabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property (nonatomic) BOOL hasUnreadMessages; // @dynamic hasUnreadMessages;
@property (nonatomic) UIImage *monogramImage; // @synthesize monogramImage=_monogramImage;
@property (strong, nonatomic) NSString *recipientNames; // @dynamic recipientNames;
@property (strong, nonatomic) UILabel *recipientsLabel; // @synthesize recipientsLabel=_recipientsLabel;
@property (strong, nonatomic) UIImageView *unreadImageView; // @synthesize unreadImageView=_unreadImageView;

+ (double)starkCellMarginWidth;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;

@end

