//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <ChatKit/NSFastEnumeration-Protocol.h>

@class NSArray, NSMutableDictionary, NSMutableOrderedSet, NSString;
@protocol CKTranscriptBalloonSelectionManagerDataSource, CKTranscriptBalloonSelectionManagerDelegate;

@interface CKTranscriptBalloonSelectionManager : NSObject <NSFastEnumeration>
{
    id<CKTranscriptBalloonSelectionManagerDelegate> _delegate;
    id<CKTranscriptBalloonSelectionManagerDataSource> _dataSource;
    NSString *_trackedGuid;
    NSMutableOrderedSet *_selectedMessageGuids;
    NSMutableDictionary *_selectedStates;
}

@property (readonly, nonatomic) NSArray *chatItems;
@property (weak, nonatomic) id<CKTranscriptBalloonSelectionManagerDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property (weak, nonatomic) id<CKTranscriptBalloonSelectionManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property (readonly, nonatomic) unsigned long long selectedGuidCount;
@property (strong, nonatomic) NSMutableOrderedSet *selectedMessageGuids; // @synthesize selectedMessageGuids=_selectedMessageGuids;
@property (strong, nonatomic) NSMutableDictionary *selectedStates; // @synthesize selectedStates=_selectedStates;
@property (strong, nonatomic) NSString *trackedGuid; // @synthesize trackedGuid=_trackedGuid;

- (void).cxx_destruct;
- (id)_chatItemForGUID:(id)arg1;
- (void)addSelectedMessageGuid:(id)arg1 selectionState:(id)arg2;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (long long)indexOfGuid:(id)arg1 inChatItems:(id)arg2;
- (id)init;
- (BOOL)isMessageGuidSelected:(id)arg1;
- (void)removeAllSelectedMessageGuids;
- (void)removeAllSelectedMessageGuidsExceptTrackedGuid;
- (void)removeSelectedMessageGuid:(id)arg1;
- (void)removeTrackedGuid;
- (id)selectedGuidAtIndex:(unsigned long long)arg1;
- (id)selectedStateForGuid:(id)arg1;
- (void)setSelectedGuids:(id)arg1;
- (void)trackSelectedGuid:(id)arg1 selectionState:(id)arg2;

@end

