//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSData, NSString;

@interface SISchemaRedactableString : PBCodable
{
    int _redactionState;
    unsigned long long _which_String;
    NSString *_value;
}

@property (readonly, nonatomic) NSData *jsonData;
@property (nonatomic) int redactionState; // @synthesize redactionState=_redactionState;
@property (copy, nonatomic) NSString *value; // @synthesize value=_value;
@property (readonly, nonatomic) unsigned long long which_String; // @synthesize which_String=_which_String;

- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;

@end

