//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSObject.h>

@class VKViewVolume;

__attribute__((visibility("hidden")))
@interface VKViewTransform : NSObject
{
    shared_ptr_d1ecf7a2 _viewTransform;
}

@property (readonly, nonatomic) float contentScale;
@property (readonly, nonatomic) int coordinateSpace;
@property (readonly, nonatomic) float degreesFromPlumb;
@property (readonly, nonatomic) double farPlaneDistance;
@property (readonly, nonatomic) double focusDistance;
@property (readonly, nonatomic) struct VKPoint focusPoint;
@property (readonly, nonatomic) Matrix_6e1d3589 forwardVector;
@property (readonly, nonatomic) float heading;
@property (readonly, nonatomic) BOOL isGeocentric;
@property (readonly, nonatomic) BOOL isMercator;
@property (readonly, nonatomic) double nearPlaneDistance;
@property (readonly, nonatomic) Matrix_6e1d3589 rightVector;
@property (nonatomic) const CDStruct_aa5aacbc *scaledViewProjectionMatrix;
@property (readonly, nonatomic) struct CGSize screenSizeInPixels;
@property (readonly, nonatomic) struct CGSize screenSizeInPoints;
@property (readonly, nonatomic) struct VKPoint translation;
@property (readonly, nonatomic) struct VKPoint translationInMercator;
@property (readonly, nonatomic) Matrix_6e1d3589 upVector;
@property (readonly, nonatomic) const CDStruct_aa5aacbc *viewProjectionMatrix;
@property (readonly, nonatomic) VKViewVolume *viewVolume;
@property (readonly, nonatomic) double widthOverDepth;

- (id).cxx_construct;
- (void).cxx_destruct;
- (struct VKPoint)groundPointFromPixel:(Matrix_8746f91e)arg1;
- (struct VKPoint)groundPointFromScreenPoint:(struct CGPoint)arg1;
- (id)init;
- (CDStruct_aa5aacbc)orientationMatrixAtWorldPoint:(struct VKPoint)arg1;
- (void)setCoordinateSpace:(int)arg1 screenSizeInPixels:(struct CGSize)arg2 contentScale:(float)arg3 frustum:(CDStruct_184b3e93)arg4 position:(struct VKPoint)arg5 orientation:(const CDStruct_aa5aacbc *)arg6 horizontalOffset:(float)arg7;
- (shared_ptr_d1ecf7a2)viewTransform;

@end

