//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class ETModelDef, NSString;

@interface ETVariable : NSObject
{
    float _initializationAlpha;
    float _initializationBeta;
    unsigned long long _kind;
    NSString *_name;
    NSString *_layerName;
    unsigned long long _initializationMode;
    ETModelDef *_model;
}

@property float initializationAlpha; // @synthesize initializationAlpha=_initializationAlpha;
@property float initializationBeta; // @synthesize initializationBeta=_initializationBeta;
@property unsigned long long initializationMode; // @synthesize initializationMode=_initializationMode;
@property (nonatomic) unsigned long long kind; // @synthesize kind=_kind;
@property (strong, nonatomic) NSString *layerName; // @synthesize layerName=_layerName;
@property (weak, nonatomic) ETModelDef *model; // @synthesize model=_model;
@property (strong, nonatomic) NSString *name; // @synthesize name=_name;

- (void).cxx_destruct;
- (id)copyData;
- (id)getOpaqueCopy;
- (id)initWithModelDef:(id)arg1;
- (id)swapWithOpaqueCopy:(id)arg1;
- (void)updateWithData:(id)arg1;

@end

