//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <HeroAppPredictionClient/ATXProtoBufWrapper-Protocol.h>
#import <HeroAppPredictionClient/ATXSuggestionExecutableProtocol-Protocol.h>
#import <HeroAppPredictionClient/NSCopying-Protocol.h>
#import <HeroAppPredictionClient/NSSecureCoding-Protocol.h>

@class CPSClipMetadata, NSString;

@interface ATXHeroAppPrediction : NSObject <ATXProtoBufWrapper, ATXSuggestionExecutableProtocol, NSSecureCoding, NSCopying>
{
    BOOL _isTouristApp;
    unsigned long long _adamId;
    NSString *_bundleId;
    double _latitude;
    double _longitude;
    double _latitudeAtPredictionTime;
    double _longitudeAtPredictionTime;
    unsigned long long _radiusInMeters;
    unsigned long long _rank;
    double _score;
    NSString *_urlHash;
    CPSClipMetadata *_clipMetadata;
}

@property (nonatomic) unsigned long long adamId; // @synthesize adamId=_adamId;
@property (strong, nonatomic) NSString *bundleId; // @synthesize bundleId=_bundleId;
@property (strong, nonatomic) CPSClipMetadata *clipMetadata; // @synthesize clipMetadata=_clipMetadata;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) BOOL isTouristApp; // @synthesize isTouristApp=_isTouristApp;
@property (nonatomic) double latitude; // @synthesize latitude=_latitude;
@property (nonatomic) double latitudeAtPredictionTime; // @synthesize latitudeAtPredictionTime=_latitudeAtPredictionTime;
@property (nonatomic) double longitude; // @synthesize longitude=_longitude;
@property (nonatomic) double longitudeAtPredictionTime; // @synthesize longitudeAtPredictionTime=_longitudeAtPredictionTime;
@property (nonatomic) unsigned long long radiusInMeters; // @synthesize radiusInMeters=_radiusInMeters;
@property (nonatomic) unsigned long long rank; // @synthesize rank=_rank;
@property (nonatomic) double score; // @synthesize score=_score;
@property (readonly) Class superclass;
@property (strong, nonatomic) NSString *urlHash; // @synthesize urlHash=_urlHash;

+ (id)copyClipMetadata:(id)arg1;
+ (BOOL)isClipMetadataEqual:(id)arg1 other:(id)arg2;
+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (BOOL)checkAndReportDecodingFailureIfNeededForBOOL:(BOOL)arg1 key:(id)arg2 coder:(id)arg3 errorDomain:(id)arg4 errorCode:(long long)arg5;
- (BOOL)checkAndReportDecodingFailureIfNeededFordouble:(double)arg1 key:(id)arg2 coder:(id)arg3 errorDomain:(id)arg4 errorCode:(long long)arg5;
- (BOOL)checkAndReportDecodingFailureIfNeededForid:(id)arg1 key:(id)arg2 coder:(id)arg3 errorDomain:(id)arg4 errorCode:(long long)arg5;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)encodeAsProto;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithPredictedAdamId:(unsigned long long)arg1 bundleId:(id)arg2 latitude:(double)arg3 longitude:(double)arg4 radiusInMeters:(unsigned long long)arg5 rank:(unsigned long long)arg6 isTouristApp:(BOOL)arg7 score:(double)arg8 urlHash:(id)arg9 clipMetadata:(id)arg10;
- (id)initWithPredictedAdamId:(unsigned long long)arg1 latitude:(double)arg2 longitude:(double)arg3 radiusInMeters:(unsigned long long)arg4 rank:(unsigned long long)arg5 isTouristApp:(BOOL)arg6;
- (id)initWithPredictedBundleId:(id)arg1 latitude:(double)arg2 longitude:(double)arg3 radiusInMeters:(unsigned long long)arg4 rank:(unsigned long long)arg5 isTouristApp:(BOOL)arg6;
- (id)initWithProto:(id)arg1;
- (id)initWithProtoData:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)proto;

@end

