//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TSCharts/TSCHChartFeature.h>

@interface TSCHChartFeaturePieFamily : TSCHChartFeature
{
}

- (id)animationDeliveryStylesForFilter:(id)arg1;
- (BOOL)editableFormatForValueStrings;
- (id)genericToSpecificPropertyMap;
- (BOOL)hasExplodableSeriesElements;
- (BOOL)hasFixedFrameRatio;
- (id)initialSceneWithChartInfo:(id)arg1 layoutSettings:(CDStruct_b1c75024)arg2;
- (unsigned long long)maxCellsToCheckForGridValueType;
- (void)p_initializeAxisIDs;
- (BOOL)rendersBackgroundAxis;
- (BOOL)rendersUsingRadialGeometry;
- (int)representativeGridValueAxisType;
- (unsigned long long)styleIndexForAxisID:(id)arg1;
- (BOOL)supportsBackgroundFill;
- (BOOL)supportsBorderFrame;
- (BOOL)supportsCategoryLabelsInChartRangeEditor;
- (BOOL)supportsElementSeriesNames;
- (BOOL)supportsErrorBars;
- (BOOL)supportsGroupedShadows;
- (BOOL)supportsLabelExplosion;
- (BOOL)supportsMultipleValuesPerSeries;
- (BOOL)supportsPercentNumberFormatting;
- (BOOL)supportsReferenceLines;
- (BOOL)supportsStartAngleRotation;
- (BOOL)supportsTrendLines;
- (void)updateTitlesForExportingModel:(id)arg1 info:(id)arg2;
- (Class)valueAxisClassForID:(id)arg1 scale:(long long)arg2;

@end

