//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <HMFoundation/HMFObject.h>

@interface HMIDESRunner : HMFObject
{
}

+ (id)flattenTrainingResult:(id)arg1;
+ (id)packageTrainingResult:(id)arg1 privatize:(BOOL)arg2 maxNorm:(double)arg3 normBinCount:(unsigned long long)arg4 encryptionKey:(id)arg5 error:(id *)arg6;

@end

