//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <CoreSpeech/CSAudioStreamProvidingDelegate-Protocol.h>
#import <CoreSpeech/CSXPCConnectionDelegate-Protocol.h>

@class CSAudioRecordContext, CSAudioStream, CSXPCConnection, NSDictionary, NSString;
@protocol CSAudioStreamProviding, CSTriggerInfoProviding;

@interface CSAudioStreamProvidingProxy : NSObject <CSXPCConnectionDelegate, CSAudioStreamProvidingDelegate>
{
    id<CSAudioStreamProviding> _audioStreamProviding;
    id<CSTriggerInfoProviding> _triggerInfoProviding;
    CSXPCConnection *_xpcConnection;
    unsigned long long _streamClientType;
    CSAudioStream *_audioStream;
    NSDictionary *_lastVoiceTriggerInfo;
    NSDictionary *_lastRTSTriggerInfo;
    CSAudioRecordContext *_recordContext;
    NSString *_recordEventUUID;
}

@property (strong, nonatomic) CSAudioStream *audioStream; // @synthesize audioStream=_audioStream;
@property (weak, nonatomic, setter=setAudioStreamProvidingForProxy:) id<CSAudioStreamProviding> audioStreamProviding; // @synthesize audioStreamProviding=_audioStreamProviding;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (copy) NSDictionary *lastRTSTriggerInfo; // @synthesize lastRTSTriggerInfo=_lastRTSTriggerInfo;
@property (copy) NSDictionary *lastVoiceTriggerInfo; // @synthesize lastVoiceTriggerInfo=_lastVoiceTriggerInfo;
@property (strong, nonatomic) CSAudioRecordContext *recordContext; // @synthesize recordContext=_recordContext;
@property (strong, nonatomic) NSString *recordEventUUID; // @synthesize recordEventUUID=_recordEventUUID;
@property (nonatomic) unsigned long long streamClientType; // @synthesize streamClientType=_streamClientType;
@property (readonly) Class superclass;
@property (weak, nonatomic) id<CSTriggerInfoProviding> triggerInfoProviding; // @synthesize triggerInfoProviding=_triggerInfoProviding;
@property (weak, nonatomic) CSXPCConnection *xpcConnection; // @synthesize xpcConnection=_xpcConnection;

- (void).cxx_destruct;
- (void)CSXPCConnectionReceivedClientError:(id)arg1 clientError:(id)arg2 client:(id)arg3;
- (void)_handleAudioStreamPrepareMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;
- (void)_handleAudioStreamRequestMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;
- (void)_handleIsNarrowband:(id)arg1 messageBody:(id)arg2 client:(id)arg3;
- (void)_handleIsRecordingMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;
- (void)_handlePlaybackRouteMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;
- (void)_handleRecordDeviceInfo:(id)arg1 messageBody:(id)arg2 client:(id)arg3;
- (void)_handleRecordRouteMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;
- (void)_handleRecordSettings:(id)arg1 messageBody:(id)arg2 client:(id)arg3;
- (void)_handleSetCurrentConextMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;
- (void)_handleStartAudioStreamMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;
- (void)_handleStopAudioStreamMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;
- (void)_handleVoiceTriggerInfoMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;
- (void)_sendDelegateMessageToClient:(id)arg1;
- (void)_sendReply:(id)arg1 client:(id)arg2 result:(BOOL)arg3 error:(id)arg4;
- (void)_setAllowMixableAudioWhileRecording:(BOOL)arg1;
- (void)audioStreamProvider:(id)arg1 audioBufferAvailable:(id)arg2;
- (void)audioStreamProvider:(id)arg1 audioChunkForTVAvailable:(id)arg2;
- (void)audioStreamProvider:(id)arg1 didHardwareConfigurationChange:(long long)arg2;
- (void)audioStreamProvider:(id)arg1 didStopStreamUnexpectly:(long long)arg2;
- (void)handleXPCMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;
- (id)initWithXPCConnection:(id)arg1;
- (void)setInitialContext:(id)arg1;

@end

