//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDiffableDataSourceSnapshot, NSOrderedCollectionDifference;

@interface _UIDiffableDataSourceTransaction : NSObject
{
    NSArray *_reorderedItemIdentifiers;
    long long _source;
    NSDiffableDataSourceSnapshot *_initialSnapshot;
    NSDiffableDataSourceSnapshot *_finalSnapshot;
    NSOrderedCollectionDifference *_difference;
    NSArray *_sectionTransactions;
}

@property (readonly, nonatomic) NSOrderedCollectionDifference *difference; // @synthesize difference=_difference;
@property (readonly, nonatomic) NSDiffableDataSourceSnapshot *finalSnapshot; // @synthesize finalSnapshot=_finalSnapshot;
@property (readonly, nonatomic) NSDiffableDataSourceSnapshot *initialSnapshot; // @synthesize initialSnapshot=_initialSnapshot;
@property (readonly, nonatomic) NSArray *sectionTransactions; // @synthesize sectionTransactions=_sectionTransactions;

+ (id)applyTransactionWithInitialSnapshot:(id)arg1 finalSnapshot:(id)arg2 difference:(id)arg3 sectionTransactions:(id)arg4;
+ (id)reorderingTransactionWithInitialSnapshot:(id)arg1 finalSnapshot:(id)arg2 difference:(id)arg3 sectionTransactions:(id)arg4;
- (void).cxx_destruct;
- (id)description;
- (id)finalDataSourceSnapshotter;
- (long long)finalGlobalIndexForInitialGlobalIndex:(long long)arg1;
- (id)finalIndexPathForInitialIndexPath:(id)arg1;
- (id)finalIndexPathForSupplementaryElementOfKind:(id)arg1 forInitialIndexPath:(id)arg2;
- (long long)finalSectionCount;
- (struct _NSRange)finalSectionGlobalItemRangeForSection:(long long)arg1;
- (long long)finalSectionIndexForInitialSectionIndex:(long long)arg1;
- (id)initWithInitialSnapshot:(id)arg1 finalSnapshot:(id)arg2 source:(long long)arg3 reorderedItemIdentifiers:(id)arg4 difference:(id)arg5 sectionTransactions:(id)arg6;
- (struct _NSRange)initalSectionGlobalItemRangeForSection:(long long)arg1;
- (id)initialDataSourceSnapshotter;
- (long long)initialGlobalIndexForFinalGlobalIndex:(long long)arg1;
- (id)initialIndexPathForFinalIndexPath:(id)arg1;
- (id)initialIndexPathForSupplementaryElementOfKind:(id)arg1 forFinalIndexPath:(id)arg2;
- (long long)initialSectionCount;
- (long long)initialSectionIndexForFinalSectionIndex:(long long)arg1;
- (BOOL)isApplyTransaction;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isReorderingTransaction;
- (id)performDiffGeneratingUpdates;
- (id)reorderedItemIdentifiers;
- (long long)source;

@end

