//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface _UIFocusLinearMovementSequence : NSObject
{
    BOOL _looping;
    NSArray *_items;
}

@property (readonly, copy, nonatomic) NSArray *items; // @synthesize items=_items;
@property (readonly, nonatomic, getter=isLooping) BOOL looping; // @synthesize looping=_looping;

+ (id)sequenceWithItems:(id)arg1 loops:(BOOL)arg2;
- (void).cxx_destruct;
- (id)init;
- (id)initWithItems:(id)arg1 loops:(BOOL)arg2;

@end

