//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSLayoutConstraint, UIView;
@protocol UIInterfaceActionVisualSeparatorDisplaying><UIInterfaceActionVisualSectionSeparatorDisplaying;

__attribute__((visibility("hidden")))
@interface _UIInterfaceActionSeparatorConstraintController : NSObject
{
    double _constantAxisDimension;
    UIView<UIInterfaceActionVisualSeparatorDisplaying><UIInterfaceActionVisualSectionSeparatorDisplaying> *_separatorView;
    NSLayoutConstraint *_fixedHeightConstraint;
    NSLayoutConstraint *_fixedWidthConstraint;
    long long _constantSizedAxis;
}

@property (nonatomic) double constantAxisDimension; // @synthesize constantAxisDimension=_constantAxisDimension;
@property (nonatomic) long long constantSizedAxis; // @synthesize constantSizedAxis=_constantSizedAxis;
@property (readonly, nonatomic) NSLayoutConstraint *fixedHeightConstraint; // @synthesize fixedHeightConstraint=_fixedHeightConstraint;
@property (readonly, nonatomic) NSLayoutConstraint *fixedWidthConstraint; // @synthesize fixedWidthConstraint=_fixedWidthConstraint;
@property (readonly, weak, nonatomic) UIView<UIInterfaceActionVisualSeparatorDisplaying><UIInterfaceActionVisualSectionSeparatorDisplaying> *separatorView; // @synthesize separatorView=_separatorView;

- (void).cxx_destruct;
- (BOOL)_isFixedWidth;
- (void)_updateConstantSizedConstraints;
- (id)initWithSeparatorView:(id)arg1;
- (void)separatorViewDidUpdateConstraints;

@end

