//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <UIKitCore/NSCopying-Protocol.h>

__attribute__((visibility("hidden")))
@interface _UISegmentedControlSegmentHoverIdentifier : NSObject <NSCopying>
{
    long long _index;
    BOOL _isSelected;
}

@property (readonly, nonatomic) long long index; // @synthesize index=_index;
@property (readonly, nonatomic) BOOL isSelected; // @synthesize isSelected=_isSelected;

- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)initWithIndex:(long long)arg1 selected:(BOOL)arg2;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualToIdentifier:(id)arg1;

@end

