//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKitCore/UILayoutContainerView.h>

@class UISplitViewControllerPanelImpl;

__attribute__((visibility("hidden")))
@interface _UISplitViewControllerPanelImplView : UILayoutContainerView
{
    UISplitViewControllerPanelImpl *_impl;
}

@property (weak, nonatomic) UISplitViewControllerPanelImpl *impl; // @synthesize impl=_impl;

- (void).cxx_destruct;
- (void)_searchForFocusRegionsInContext:(id)arg1;

@end

