//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKitCore/UIPickerContentView.h>

__attribute__((visibility("hidden")))
@interface UIDOMHTMLOptionPickerCell : UIPickerContentView
{
    BOOL _disabled;
}

@property (nonatomic) BOOL disabled; // @synthesize disabled=_disabled;

- (BOOL)_isSelectable;
- (id)initCommon;
- (id)initWithHTMLOptionNode:(id)arg1;

@end

