//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CDPDevice, NSDictionary, NSString, OTClique;

@interface CDPDRemoteSecretValidationResult : NSObject
{
    BOOL _userDidCancel;
    BOOL _userDidReset;
    unsigned long long _secretType;
    CDPDevice *_device;
    NSString *_validSecret;
    NSDictionary *_recoveredInfo;
    OTClique *_recoveredClique;
}

@property (copy, nonatomic) CDPDevice *device; // @synthesize device=_device;
@property (strong, nonatomic) OTClique *recoveredClique; // @synthesize recoveredClique=_recoveredClique;
@property (copy, nonatomic) NSDictionary *recoveredInfo; // @synthesize recoveredInfo=_recoveredInfo;
@property (nonatomic) unsigned long long secretType; // @synthesize secretType=_secretType;
@property (nonatomic) BOOL userDidCancel; // @synthesize userDidCancel=_userDidCancel;
@property (nonatomic) BOOL userDidReset; // @synthesize userDidReset=_userDidReset;
@property (copy, nonatomic) NSString *validSecret; // @synthesize validSecret=_validSecret;

- (void).cxx_destruct;

@end

