//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor, UIImageView;

@interface FMRule : UIView
{
    BOOL _leading;
    UIColor *_color;
    UIImageView *_imageView;
}

@property (strong, nonatomic) UIColor *color; // @synthesize color=_color;
@property (strong, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property (nonatomic) BOOL leading; // @synthesize leading=_leading;

+ (id)imageWithColor:(id)arg1 leading:(BOOL)arg2;
- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)commonSetup;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)prepareForInterfaceBuilder;

@end

