//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <InputContext/_ICPredictionSourcing-Protocol.h>

@class NSString;

@interface _ICInternalSource : NSObject <_ICPredictionSourcing>
{
    NSString *_name;
}

- (void).cxx_destruct;
- (BOOL)doesSupportTriggerSourceType:(unsigned char)arg1;
- (void)hibernate;
- (id)init;
- (id)localizedStringForKey:(id)arg1 withLocale:(id)arg2;
- (id)name;
- (void)predictedItemsWithProactiveTrigger:(id)arg1 searchContext:(id)arg2 limit:(unsigned long long)arg3 timeoutInMilliseconds:(unsigned long long)arg4 handler:(CDUnknownBlockType)arg5;
- (void)provideFeedbackForString:(id)arg1 type:(unsigned char)arg2 style:(unsigned char)arg3;
- (void)searchForMeCardEmailAddressesWithTimeout:(unsigned long long)arg1 handler:(CDUnknownBlockType)arg2;
- (void)searchForMeCardRegionsWithTimeout:(unsigned long long)arg1 handler:(CDUnknownBlockType)arg2;
- (void)warmUp;

@end

