//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <iWorkImport/GQZArchiveInputStream-Protocol.h>

@class NSData, NSString;

__attribute__((visibility("hidden")))
@interface GQZArchiveMemoryInputStream : NSObject <GQZArchiveInputStream>
{
    NSData *mData;
    const char *mBytes;
    long long mSize;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (const char *)dataAtOffset:(long long)arg1 size:(unsigned long long)arg2 end:(long long)arg3 readSize:(unsigned long long *)arg4;
- (void)dealloc;
- (id)initWithData:(id)arg1;
- (void)readFromOffset:(long long)arg1 size:(unsigned long long)arg2 buffer:(char *)arg3;
- (long long)size;

@end

