//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (TSPObjectSerialization)
+ (id)tsp_decoderDataInfoDictionaryFromMessage:(const RepeatedPtrField_fe6aca30 *)arg1;
+ (id)tsp_decoderResourceNameDictionaryFromMessage:(const RepeatedPtrField_fe6aca30 *)arg1;
+ (id)tsp_identifierToObjectUUIDDictionaryFromMessage:(const RepeatedPtrField_c964a194 *)arg1;
+ (id)tsp_identifierToObjectUUIDDictionaryFromWeakExternalReferences:(id)arg1 updatingComponentInfo:(struct ComponentInfo *)arg2 failIfReferenceIsNotPersisted:(BOOL)arg3 context:(id)arg4 error:(id *)arg5;
- (void)tsp_saveIdentifierToObjectUUIDDictionaryToMessage:(RepeatedPtrField_c964a194 *)arg1;
@end

