//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSObject.h>

@class TSCH3DChartTitlePositioner, TSCH3DLabelResources, TSCHChartInfo;

__attribute__((visibility("hidden")))
@interface TSCH3DChartTitleProperties : NSObject
{
    TSCHChartInfo *mInfo;
    TSCH3DLabelResources *mLabels;
    BOOL mHidden;
    TSCH3DChartTitlePositioner *mCachedPositioner;
}

@property (strong, nonatomic) TSCH3DChartTitlePositioner *cachedPositioner; // @synthesize cachedPositioner=mCachedPositioner;
@property (readonly, nonatomic) TSCHChartInfo *chartInfo; // @synthesize chartInfo=mInfo;
@property (nonatomic) BOOL hidden; // @synthesize hidden=mHidden;
@property (readonly, nonatomic) TSCH3DLabelResources *labels; // @synthesize labels=mLabels;

+ (id)propertiesWithInfo:(id)arg1 styleIndex:(unsigned long long)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithInfo:(id)arg1 styleIndex:(unsigned long long)arg2;

@end

