//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <iWorkImport/TSCH3DDefaultDataBufferResource.h>

__attribute__((visibility("hidden")))
@interface TSCH3DBarUnitCubeResource : TSCH3DDefaultDataBufferResource
{
}

+ (id)_singletonAlloc;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)defaultDataBuffer;
+ (id)sharedInstance;
- (id)autorelease;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (oneway void)release;
- (id)retain;
- (unsigned long long)retainCount;

@end

