//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface TSUMutableWarningSet : NSObject
{
    NSObject<OS_dispatch_queue> *_accessQueue;
    NSMutableSet *_warnings;
}

@property (readonly) unsigned long long count;

- (void).cxx_destruct;
- (void)addWarning:(id)arg1;
- (BOOL)containsWarningPassingTest:(CDUnknownBlockType)arg1;
- (BOOL)hasWarningsOfKind:(long long)arg1;
- (id)init;
- (id)initWithSet:(id)arg1;
- (id)popAllWarnings;
- (id)popAllWarningsIfContainsWarningPassingTest:(CDUnknownBlockType)arg1;
- (void)unionSet:(id)arg1;
- (id)warningsOfKind:(long long)arg1;
- (id)warningsPassingTest:(CDUnknownBlockType)arg1;

@end

