//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ADDaemonMetricsHelper : NSObject
{
    NSString *_adamID;
}

@property (readonly, nonatomic) NSString *adamID; // @synthesize adamID=_adamID;

- (void).cxx_destruct;
- (void)downloadCompleted;
- (void)downloadInitiated;
- (id)initWithAdamID:(id)arg1;
- (void)installCompleted;
- (void)purchcaseCompleted;

@end

