//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MIME/NSObject-Protocol.h>

@class NSString;

@protocol ECMIMECharset <NSObject>

@property (readonly, nonatomic) BOOL canBeUsedForOutgoingMessages;
@property (readonly, copy, nonatomic) NSString *charsetName;
@property (readonly, copy, nonatomic) NSString *displayName;
@property (readonly) unsigned long long encoding;

@end

