//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSFileManager.h>

@interface NSFileManager (IMSharedUtilities)
- (BOOL)__im_getItemsRemovedFromiCloudBackupsAtDirectoryPath:(id)arg1 outPaths:(id *)arg2 outRemovedPaths:(id *)arg3 error:(id *)arg4;
- (BOOL)__im_getiCloudBackupAttributeForItemAtPath:(id)arg1 attributeValue:(BOOL *)arg2 error:(id *)arg3;
- (BOOL)__im_setiCloudBackupAttribute:(BOOL)arg1 onDirectoryAndChildrenAtPath:(id)arg2 error:(id *)arg3;
- (BOOL)__im_setiCloudBackupAttribute:(BOOL)arg1 onItemAtPath:(id)arg2 error:(id *)arg3;
@end

