//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/_UIRemoteViewController.h>

@class QLRemoteItemViewController;

__attribute__((visibility("hidden")))
@interface QLRemotePreviewHostViewController : _UIRemoteViewController
{
    QLRemoteItemViewController *_remoteItemViewController;
}

@property (weak) QLRemoteItemViewController *remoteItemViewController; // @synthesize remoteItemViewController=_remoteItemViewController;

- (void).cxx_destruct;
- (void)viewServiceDidTerminateWithError:(id)arg1;

@end

