//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppPredictionUI/APUIWFLIntentControllerDelegate-Protocol.h>
#import <AppPredictionUI/ATXTVIntentHandler-Protocol.h>

@class APUIWFLIntentController, ATXAction, NSString;

@interface APUITVIntentHandler : NSObject <APUIWFLIntentControllerDelegate, ATXTVIntentHandler>
{
    ATXAction *_action;
    APUIWFLIntentController *_intentController;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_punchToAppWithIntent:(id)arg1;
- (void)executeTVActionWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithTVAction:(id)arg1 context:(long long)arg2;
- (void)intentController:(id)arg1 didFailWithError:(id)arg2 forInteraction:(id)arg3;
- (void)intentController:(id)arg1 didHandleInteraction:(id)arg2;
- (void)intentController:(id)arg1 requiresConfirmationForIntent:(id)arg2 intentResponse:(id)arg3;
- (void)intentController:(id)arg1 requiresContinuingInAppForIntent:(id)arg2 proceedHandler:(CDUnknownBlockType)arg3;
- (void)intentControllerDidFailAuthorizationCheck:(id)arg1;

@end

