//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIGestureRecognizer.h>

#import <TSReading/TSDAutoscrollDelegate-Protocol.h>
#import <TSReading/TSDTrackerManipulator-Protocol.h>

@class TSDAutoscroll, TSDInteractiveCanvasController, TSDKnobTracker, TSDRep, TSDiOSCanvasViewController, UITouch;

@interface TSDKnobDragGestureRecognizer : UIGestureRecognizer <TSDAutoscrollDelegate, TSDTrackerManipulator>
{
    TSDiOSCanvasViewController *mCVC;
    TSDInteractiveCanvasController *mICC;
    UITouch *mTouch;
    struct CGPoint mKnobToTouchOffset;
    TSDKnobTracker *mTracker;
    BOOL mKnobTouchHasMoved;
    BOOL mDelayHasElapsed;
    struct CGPoint mOriginalPointInWindow;
    UITouch *mSecondTouch;
    TSDRep *mLastHitRep;
    BOOL mTouchesMoved;
    TSDAutoscroll *mAutoscroll;
    struct CGPoint mAutoscrollPoint;
}

@property (strong, nonatomic) TSDAutoscroll *autoscroll; // @synthesize autoscroll=mAutoscroll;
@property (nonatomic) struct CGPoint autoscrollPoint; // @synthesize autoscrollPoint=mAutoscrollPoint;
@property (readonly, nonatomic) TSDInteractiveCanvasController *icc;
@property (readonly, nonatomic) TSDInteractiveCanvasController *interactiveCanvasController; // @synthesize interactiveCanvasController=mICC;

- (BOOL)allowTrackerManipulatorToTakeControl:(id)arg1;
- (int)allowedAutoscrollDirections;
- (void)autoscrollWillNotStart;
- (void)cancelBecauseOfRotation;
- (void)dealloc;
- (id)initWithInteractiveCanvasController:(id)arg1;
- (void)operationDidEnd;
- (void)p_cancelDelayedKnobTracking;
- (BOOL)p_hitRepIsValid:(id)arg1;
- (struct CGPoint)p_pointInUnscaledCanvas;
- (void)p_requestDelayedKnobTracking:(double)arg1;
- (void)p_triggerDelayedKnobTracking:(id)arg1;
- (BOOL)readyToEndOperation;
- (void)reset;
- (void)setState:(long long)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (id)tracker;
- (double)unscaledStartAutoscrollThreshold;
- (void)updateAfterAutoscroll:(id)arg1;

@end

