//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class TSDMagicMoveAnimationMatch, TSDTextureSet;

@interface TSDMagicMoveTextureZOrdererMatch : NSObject
{
    BOOL _isOutgoingZIndexUnmatched;
    BOOL _isIncomingZIndexUnmatched;
    TSDTextureSet *_outgoingTexture;
    TSDTextureSet *_incomingTexture;
    long long _outgoingZIndex;
    long long _incomingZIndex;
    TSDMagicMoveAnimationMatch *_animationMatch;
}

@property (readonly, nonatomic) TSDMagicMoveAnimationMatch *animationMatch; // @synthesize animationMatch=_animationMatch;
@property (readonly, nonatomic) TSDTextureSet *incomingTexture; // @synthesize incomingTexture=_incomingTexture;
@property (nonatomic) long long incomingZIndex; // @synthesize incomingZIndex=_incomingZIndex;
@property (readonly, nonatomic) BOOL isIncomingZIndexUnmatched; // @synthesize isIncomingZIndexUnmatched=_isIncomingZIndexUnmatched;
@property (readonly, nonatomic) BOOL isOutgoingZIndexUnmatched; // @synthesize isOutgoingZIndexUnmatched=_isOutgoingZIndexUnmatched;
@property (readonly, nonatomic) TSDTextureSet *outgoingTexture; // @synthesize outgoingTexture=_outgoingTexture;
@property (nonatomic) long long outgoingZIndex; // @synthesize outgoingZIndex=_outgoingZIndex;

- (void)dealloc;
- (id)description;
- (id)init;
- (id)initWithAnimationMatch:(id)arg1;
- (double)interpolatedZIndexAtPercent:(double)arg1;
- (double)intersectionPercentWithZOrdererMatch:(id)arg1;
- (BOOL)intersectsZOrdererMatch:(id)arg1;
- (BOOL)intersectsZOrdererMatch:(id)arg1 withAttemptedZIndex:(long long)arg2;

@end

