//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TSReading/TSDRenderable.h>

@class CAShapeLayer, NSArray, NSString;

@interface TSDShapeRenderable : TSDRenderable
{
}

@property (nonatomic) struct CGColor *fillColor;
@property (copy, nonatomic) NSString *lineCap;
@property (copy, nonatomic) NSArray *lineDashPattern;
@property (nonatomic) double lineDashPhase;
@property (copy, nonatomic) NSString *lineJoin;
@property (nonatomic) double lineWidth;
@property (nonatomic) double miterLimit;
@property (nonatomic) const struct CGPath *path;
@property (readonly, nonatomic) CAShapeLayer *shapeLayer;
@property (nonatomic) struct CGColor *strokeColor;
@property (nonatomic) double strokeEnd;

+ (id)renderable;
+ (id)renderableFromShapeLayer:(id)arg1;
- (id)initWithShapeLayer:(id)arg1;
- (void)setCGLineCap:(int)arg1;
- (void)setCGLineJoin:(int)arg1;

@end

