//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary;
@protocol OS_dispatch_queue;

@interface MCCloudConfiguration : NSObject
{
    NSObject<OS_dispatch_queue> *_memberQueue;
    NSDictionary *_memberQueueDetails;
    NSDictionary *_memberQueueSetAsideDetails;
}

@property (copy, nonatomic) NSDictionary *details;
@property (strong, nonatomic) NSObject<OS_dispatch_queue> *memberQueue; // @synthesize memberQueue=_memberQueue;
@property (strong, nonatomic) NSDictionary *memberQueueDetails; // @synthesize memberQueueDetails=_memberQueueDetails;
@property (strong, nonatomic) NSDictionary *memberQueueSetAsideDetails; // @synthesize memberQueueSetAsideDetails=_memberQueueSetAsideDetails;
@property (copy, nonatomic) NSDictionary *setAsideDetails;

+ (id)sharedConfiguration;
- (void).cxx_destruct;
- (id)diagnosticsUploadURL;
- (id)init;
- (BOOL)isAwaitingConfiguration;
- (BOOL)isProvisionallyEnrolled;
- (BOOL)isSupervised;
- (BOOL)isTeslaEnrolled;
- (id)provisionalEnrollmentExpirationDate;
- (void)refreshDetailsFromDisk;
- (int)userMode;

@end

