//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface MCInstallerReader : NSObject
{
}

+ (void)_setProfileStorageDirectory:(id)arg1;
+ (id)sharedReader;
- (id)pathsToInstalledProfilesWithFilterFlags:(int)arg1;

@end

