//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <EmailDaemon/EFLoggable-Protocol.h>

@class NSString;
@protocol EDAccountsProvider;

@interface EDFetchController : NSObject <EFLoggable>
{
    id<EDAccountsProvider> _accountsProvider;
}

@property (strong, nonatomic) id<EDAccountsProvider> accountsProvider; // @synthesize accountsProvider=_accountsProvider;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)log;
- (void).cxx_destruct;
- (id)initWithAccountsProvider:(id)arg1;

@end

