//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <EmailDaemon/EDMessageRepositoryQueryHandler.h>

#import <EmailDaemon/EDMessageQueryHelperDelegate-Protocol.h>
#import <EmailDaemon/EFContentProtectionObserver-Protocol.h>
#import <EmailDaemon/EFLoggable-Protocol.h>
#import <EmailDaemon/EMCollectionItemIDStateCapturerDelegate-Protocol.h>

@class EDMessageQueryHelper, EDThreadReloadSummaryHelper, EDUpdateThrottler, EDVIPManager, EMCollectionItemIDStateCapturer, EMMailboxScope, NSArray, NSMutableDictionary, NSMutableOrderedSet, NSObject, NSString;
@protocol EDRemoteSearchProvider, EFScheduler, EMMessageListItemQueryResultsObserver, OS_dispatch_queue;

@interface EDInMemoryThreadQueryHandler : EDMessageRepositoryQueryHandler <EDMessageQueryHelperDelegate, EFLoggable, EFContentProtectionObserver, EMCollectionItemIDStateCapturerDelegate>
{
    NSMutableOrderedSet *_conversationIDs;
    NSMutableDictionary *_threadsByConversationID;
    NSMutableDictionary *_changesWhilePaused;
    NSMutableDictionary *_oldestThreadsByMailboxObjectIDs;
    struct os_unfair_lock_s _threadsLock;
    BOOL _didCancel;
    BOOL _isInitialized;
    BOOL _isPaused;
    BOOL _hasChangesWhilePaused;
    EDVIPManager *_vipManager;
    id<EDRemoteSearchProvider> _remoteSearchProvider;
    EDMessageQueryHelper *_messageQueryHelper;
    NSArray *_messageSortDescriptors;
    CDUnknownBlockType _comparator;
    EDUpdateThrottler *_updateThrottler;
    EDThreadReloadSummaryHelper *_reloadSummaryHelper;
    id<EFScheduler> _scheduler;
    NSObject<OS_dispatch_queue> *_contentProtectionQueue;
    NSObject<OS_dispatch_queue> *_resultQueue;
    EMMailboxScope *_mailboxScope;
    EMCollectionItemIDStateCapturer *_stateCapturer;
}

@property (readonly, nonatomic) CDUnknownBlockType comparator; // @synthesize comparator=_comparator;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *contentProtectionQueue; // @synthesize contentProtectionQueue=_contentProtectionQueue;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) BOOL didCancel; // @synthesize didCancel=_didCancel;
@property (nonatomic) BOOL hasChangesWhilePaused; // @synthesize hasChangesWhilePaused=_hasChangesWhilePaused;
@property (readonly) unsigned long long hash;
@property (nonatomic) BOOL isInitialized; // @synthesize isInitialized=_isInitialized;
@property (nonatomic) BOOL isPaused; // @synthesize isPaused=_isPaused;
@property (readonly, nonatomic) EMMailboxScope *mailboxScope; // @synthesize mailboxScope=_mailboxScope;
@property (strong, nonatomic) EDMessageQueryHelper *messageQueryHelper; // @synthesize messageQueryHelper=_messageQueryHelper;
@property (readonly, copy, nonatomic) NSArray *messageSortDescriptors; // @synthesize messageSortDescriptors=_messageSortDescriptors;
@property (readonly, nonatomic) EDThreadReloadSummaryHelper *reloadSummaryHelper; // @synthesize reloadSummaryHelper=_reloadSummaryHelper;
@property (readonly, nonatomic) id<EDRemoteSearchProvider> remoteSearchProvider; // @synthesize remoteSearchProvider=_remoteSearchProvider;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *resultQueue; // @synthesize resultQueue=_resultQueue;
@property (readonly, nonatomic) id<EMMessageListItemQueryResultsObserver> resultsObserverIfNotPaused;
@property (readonly, nonatomic) id<EFScheduler> scheduler; // @synthesize scheduler=_scheduler;
@property (readonly, nonatomic) EMCollectionItemIDStateCapturer *stateCapturer; // @synthesize stateCapturer=_stateCapturer;
@property (readonly) Class superclass;
@property (readonly, nonatomic) EDUpdateThrottler *updateThrottler; // @synthesize updateThrottler=_updateThrottler;
@property (readonly, nonatomic) EDVIPManager *vipManager; // @synthesize vipManager=_vipManager;

+ (id)log;
- (void).cxx_destruct;
- (void)_blockedSendersDidChange:(id)arg1;
- (void)_contentProtectionChangedToLocked;
- (void)_contentProtectionChangedToUnlocked;
- (void)_createHelperAndReconcileJournal:(BOOL)arg1;
- (BOOL)_didMergeInThreads:(id)arg1;
- (void)_didSendUpdates;
- (id)_inMemoryThreadSortDescriptorsForThreadSortDescriptors:(id)arg1;
- (void)_initializeOldestThreadsByMailbox;
- (BOOL)_mergeInThreads:(id)arg1 forMove:(BOOL)arg2;
- (BOOL)_messageListItemChangeAffectsSorting:(id)arg1;
- (id)_messageQueryFromThreadsQuery:(id)arg1;
- (id)_messagesByConversationIDForMessages:(id)arg1;
- (void)_messagesWereAdded:(id)arg1;
- (void)_messagesWereChanged:(id)arg1 forKeyPaths:(id)arg2 deleted:(BOOL)arg3;
- (void)_notifyObserverOfOldestThreadsByMailboxObjectIDs;
- (void)_prepareToSendUpdates;
- (BOOL)_queryHelperIsCurrent:(id)arg1;
- (void)_refreshObserver;
- (BOOL)_removeThreadsForInMemoryThreads:(id)arg1 forMove:(BOOL)arg2;
- (BOOL)_reportChanges:(id)arg1;
- (BOOL)_reportDeletes:(id)arg1;
- (void)_restartHelper;
- (BOOL)_threadsWereDeleted;
- (BOOL)_updateCurrentOldestThreadWithThreadIfApplicable:(id)arg1 forMailbox:(id)arg2;
- (BOOL)_updateOldestThreadsForMailboxes:(id)arg1;
- (void)_vipsDidChange:(id)arg1;
- (void)cancel;
- (void)contentProtectionStateChanged:(int)arg1 previousState:(int)arg2;
- (void)dealloc;
- (id)initWithQuery:(id)arg1 messagePersistence:(id)arg2 hookRegistry:(id)arg3 vipManager:(id)arg4 remoteSearchProvider:(id)arg5 observer:(id)arg6 observationIdentifier:(id)arg7;
- (id)itemIDsForStateCaptureWithErrorString:(id *)arg1;
- (id)labelForStateCapture;
- (id)messagesForThread:(id)arg1;
- (void)queryHelper:(id)arg1 conversationIDDidChangeForMessages:(id)arg2 fromConversationID:(long long)arg3;
- (void)queryHelper:(id)arg1 conversationNotificationLevelDidChangeForConversation:(long long)arg2 conversationID:(long long)arg3;
- (void)queryHelper:(id)arg1 didAddMessages:(id)arg2;
- (void)queryHelper:(id)arg1 didDeleteMessages:(id)arg2;
- (void)queryHelper:(id)arg1 didFindMessages:(id)arg2;
- (void)queryHelper:(id)arg1 didUpdateMessages:(id)arg2 forKeyPaths:(id)arg3;
- (void)queryHelper:(id)arg1 messageFlagsDidChangeForMessages:(id)arg2;
- (void)queryHelper:(id)arg1 objectIDDidChangeForMessage:(id)arg2 oldObjectID:(id)arg3 oldConversationID:(long long)arg4;
- (void)queryHelperDidFindAllMessages:(id)arg1;
- (void)queryHelperDidFinishRemoteSearch:(id)arg1;
- (void)queryHelperNeedsRestart:(id)arg1;
- (void)start;
- (void)tearDown;
- (void)test_tearDown;
- (id)threadForObjectID:(id)arg1 error:(id *)arg2;

@end

