//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FileProvider/FPItemCollectionDiffs.h>

@class NSMutableArray, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface FPItemCollectionItemIDBasedDiffs : FPItemCollectionDiffs
{
    NSMutableArray *_deletedItemIDs;
    NSMutableArray *_updatedItems;
    NSMutableDictionary *_replacedItemsByFormerID;
}

@property (strong) NSMutableArray *deletedItemIDs; // @synthesize deletedItemIDs=_deletedItemIDs;
@property (strong) NSMutableDictionary *replacedItemsByFormerID; // @synthesize replacedItemsByFormerID=_replacedItemsByFormerID;
@property (strong) NSMutableArray *updatedItems; // @synthesize updatedItems=_updatedItems;

- (void).cxx_destruct;
- (BOOL)containsChanges;

@end

