//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "__HUQuickControlViewControllerAccessibility_super.h"

@interface HUQuickControlViewControllerAccessibility : __HUQuickControlViewControllerAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (id)_accessibilityControlsContainerView;
- (void)_accessibilityMoveToActiveControl;
- (id)accessibilityControlServiceName;
- (void)viewDidAppear:(BOOL)arg1;

@end

