//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "__HSSetupTroubleshootingTipCellAccessibility_super.h"

@interface HSSetupTroubleshootingTipCellAccessibility : __HSSetupTroubleshootingTipCellAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)_accessibilityLoadAccessibilityInformation;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

