//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Photos/PHFetchResult.h>

@class NSArray, NSOrderedSet, NSString, PHFetchOptions;

@interface PHUnauthorizedFetchResult : PHFetchResult
{
    CDUnknownBlockType _fetchBlock;
    PHFetchOptions *_options;
    NSArray *_objects;
    NSOrderedSet *_objectIDs;
    NSString *_identifier;
}

@property (readonly) CDUnknownBlockType fetchBlock; // @synthesize fetchBlock=_fetchBlock;
@property (readonly) NSString *identifier; // @synthesize identifier=_identifier;
@property (readonly) NSOrderedSet *objectIDs; // @synthesize objectIDs=_objectIDs;
@property (readonly) NSArray *objects; // @synthesize objects=_objects;
@property (readonly, copy) PHFetchOptions *options; // @synthesize options=_options;

- (void).cxx_destruct;
- (id)changeHandlingKey;
- (id)changeHandlingValueUsingSeedOids:(id)arg1 withChange:(id)arg2 usingManagedObjectContext:(id)arg3;
- (long long)collectionFetchType;
- (id)containerIdentifier;
- (id)copyWithOptions:(id)arg1;
- (id)description;
- (id)fetchRequest;
- (id)fetchResultWithChangeHandlingValue:(id)arg1;
- (id)fetchedObjectIDs;
- (id)fetchedObjects;
- (void)getMediaTypeCounts;
- (unsigned long long)hash;
- (id)initWithOptions:(id)arg1 fetchBlock:(CDUnknownBlockType)arg2;
- (BOOL)isEqual:(id)arg1;
- (id)objectIDAtIndex:(unsigned long long)arg1;
- (id)photoLibrary;
- (unsigned long long)possibleChangesForChange:(id)arg1;
- (void)prefetchObjectsAtIndexes:(id)arg1;
- (void)updateRegistrationForChangeNotificationDeltas;

@end

