//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <PersonalizationPortraitInternals/NSCopying-Protocol.h>

@class NSString;

@interface PPM2DatabaseRecordCount : PBCodable <NSCopying>
{
    NSString *_activeTreatments;
    unsigned int _schemaVersion;
    NSString *_tableName;
    CDStruct_278ffb8f _has;
}

@property (strong, nonatomic) NSString *activeTreatments; // @synthesize activeTreatments=_activeTreatments;
@property (readonly, nonatomic) BOOL hasActiveTreatments;
@property (nonatomic) BOOL hasSchemaVersion;
@property (readonly, nonatomic) BOOL hasTableName;
@property (nonatomic) unsigned int schemaVersion; // @synthesize schemaVersion=_schemaVersion;
@property (strong, nonatomic) NSString *tableName; // @synthesize tableName=_tableName;

- (void).cxx_destruct;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;

@end

