//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface MFAttachmentIcon : NSObject
{
}

+ (id)attachment:(id)arg1 iconForSize:(struct CGSize)arg2 sourceIsManaged:(BOOL)arg3;

@end

