//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <GeoServices/GEOMapServiceCategoriesTicket-Protocol.h>

@class GEOMapServiceTraits, NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface _GEOSpotlightCategoryTicket : NSObject <GEOMapServiceCategoriesTicket>
{
    GEOMapServiceTraits *_traits;
    BOOL _canceled;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly, nonatomic) NSDictionary *responseUserInfo;
@property (readonly) Class superclass;
@property (readonly, nonatomic) GEOMapServiceTraits *traits;

- (void)cancel;
- (void)dealloc;
- (id)initWithTraits:(id)arg1;
- (void)submitWithHandler:(CDUnknownBlockType)arg1 networkActivity:(CDUnknownBlockType)arg2;

@end

