//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString;
@protocol OS_dispatch_queue;

@interface GEOEventRecorderInstrumentation : NSObject
{
    NSObject<OS_dispatch_queue> *_loggingQueue;
    NSString *_filepath;
    NSString *_geoFilepath;
    NSString *_movieFilepath;
    NSDate *_startDate;
}

+ (id)defaultInstrumentation;
+ (void)endInstrumentation;
+ (id)initializeDefaultInstrumentation;
- (void).cxx_destruct;
- (void)_captureScreenVideo:(id)arg1;
- (void)_setupLogging;
- (void)captureEventRecorderScreenVideo;
- (void)captureUIEvent:(id)arg1;
- (void)captureUserActionLogMessageEvent:(id)arg1;
- (id)getRecordedFilePaths;
- (id)init;
- (void)initializeFilepaths;
- (void)writeString:(id)arg1 ToFilepath:(id)arg2;

@end

