//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <GeoServices/NSCopying-Protocol.h>

@class GEOMultiTabsState;

@interface GEOLogMsgStateMapUI : PBCodable <NSCopying>
{
    GEOMultiTabsState *_multiTabsState;
    int _layoutInfo;
    int _layoutStyle;
    BOOL _landscape;
    struct {
        unsigned int has_layoutInfo:1;
        unsigned int has_layoutStyle:1;
        unsigned int has_landscape:1;
    } _flags;
}

@property (nonatomic) BOOL hasLandscape;
@property (nonatomic) BOOL hasLayoutInfo;
@property (nonatomic) BOOL hasLayoutStyle;
@property (readonly, nonatomic) BOOL hasMultiTabsState;
@property (nonatomic) BOOL landscape;
@property (nonatomic) int layoutInfo;
@property (nonatomic) int layoutStyle;
@property (strong, nonatomic) GEOMultiTabsState *multiTabsState;

+ (BOOL)isValid:(id)arg1;
- (void).cxx_destruct;
- (int)StringAsLayoutInfo:(id)arg1;
- (int)StringAsLayoutStyle:(id)arg1;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)jsonRepresentation;
- (id)layoutInfoAsString:(int)arg1;
- (id)layoutStyleAsString:(int)arg1;
- (void)mergeFrom:(id)arg1;
- (void)readAll:(BOOL)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;

@end

