//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBRequest.h>

#import <GeoServices/NSCopying-Protocol.h>

@class GEOABSecondPartyPlaceRequestClientMetaData, GEOPDAnalyticMetadata, GEORPClientCapabilities, GEORPUserCredentials, NSMutableArray, NSString;

@interface GEORPProblemStatusRequest : PBRequest <NSCopying>
{
    GEOABSecondPartyPlaceRequestClientMetaData *_abAssignmentMetadata;
    GEOPDAnalyticMetadata *_analyticMetadata;
    GEORPClientCapabilities *_clientCapabilities;
    NSMutableArray *_problemIds;
    NSString *_statusNotificationId;
    GEORPUserCredentials *_userCredentials;
}

@property (strong, nonatomic) GEOABSecondPartyPlaceRequestClientMetaData *abAssignmentMetadata; // @synthesize abAssignmentMetadata=_abAssignmentMetadata;
@property (strong, nonatomic) GEOPDAnalyticMetadata *analyticMetadata; // @synthesize analyticMetadata=_analyticMetadata;
@property (strong, nonatomic) GEORPClientCapabilities *clientCapabilities; // @synthesize clientCapabilities=_clientCapabilities;
@property (readonly, nonatomic) BOOL hasAbAssignmentMetadata;
@property (readonly, nonatomic) BOOL hasAnalyticMetadata;
@property (readonly, nonatomic) BOOL hasClientCapabilities;
@property (readonly, nonatomic) BOOL hasStatusNotificationId;
@property (readonly, nonatomic) BOOL hasUserCredentials;
@property (strong, nonatomic) NSMutableArray *problemIds; // @synthesize problemIds=_problemIds;
@property (strong, nonatomic) NSString *statusNotificationId; // @synthesize statusNotificationId=_statusNotificationId;
@property (strong, nonatomic) GEORPUserCredentials *userCredentials; // @synthesize userCredentials=_userCredentials;

+ (Class)problemIdType;
- (void)addProblemId:(id)arg1;
- (void)clearProblemIds;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (void)populateAnalyticsMetadata;
- (id)problemIdAtIndex:(unsigned long long)arg1;
- (unsigned long long)problemIdsCount;
- (BOOL)readFrom:(id)arg1;
- (unsigned int)requestTypeCode;
- (Class)responseClass;
- (void)writeTo:(id)arg1;

@end

