//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSXPCConnection;

@interface GEORecentLocations : NSObject
{
    NSXPCConnection *_connection;
}

- (void)dealloc;
- (id)init;
- (void)requestRecentLocationsWithResponse:(CDUnknownBlockType)arg1;

@end

