//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <CalendarNotification/CALNNotificationStorage-Protocol.h>

@class NSString;
@protocol CALNNotificationStorage;

@interface CALNNotificationStorageWrapper : NSObject <CALNNotificationStorage>
{
    id<CALNNotificationStorage> _wrappedStorage;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (strong) id<CALNNotificationStorage> wrappedStorage; // @synthesize wrappedStorage=_wrappedStorage;

- (void).cxx_destruct;
- (void)addNotificationRecord:(id)arg1;
- (id)initWithWrappedStorage:(id)arg1;
- (id)notificationRecords;
- (void)removeNotificationRecordsPassingTest:(CDUnknownBlockType)arg1;

@end

