//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <NewsTransport/NSCopying-Protocol.h>

@class NSData, NSString, NTPBAppConfigurationResource, NTPBCacheCoordinatorHints, NTPBDate, NTPBIssueReadingHistoryItem, NTPBNetworkSessionList, NTPBPersonalizationLocalData, NTPBPrivateDataControllerSyncState, NTPBReadingHistoryItem;

@interface NTPBKeyValuePair : PBCodable <NSCopying>
{
    NTPBAppConfigurationResource *_appConfigurationResource;
    NTPBCacheCoordinatorHints *_cacheCoordinatorHintsValue;
    NSData *_dataValue;
    NTPBDate *_dateValue;
    NTPBIssueReadingHistoryItem *_issueReadingHistoryItem;
    NSString *_key;
    NTPBNetworkSessionList *_networkSessionList;
    NTPBPersonalizationLocalData *_personalizationLocalData;
    NTPBPrivateDataControllerSyncState *_privateDataControllerSyncState;
    NTPBReadingHistoryItem *_readingHistoryItem;
    NSData *_recordData;
    NSString *_stringValue;
    int _valueType;
    struct {
        unsigned int valueType:1;
    } _has;
}

@property (strong, nonatomic) NTPBAppConfigurationResource *appConfigurationResource; // @synthesize appConfigurationResource=_appConfigurationResource;
@property (strong, nonatomic) NTPBCacheCoordinatorHints *cacheCoordinatorHintsValue; // @synthesize cacheCoordinatorHintsValue=_cacheCoordinatorHintsValue;
@property (strong, nonatomic) NSData *dataValue; // @synthesize dataValue=_dataValue;
@property (strong, nonatomic) NTPBDate *dateValue; // @synthesize dateValue=_dateValue;
@property (readonly, nonatomic) BOOL hasAppConfigurationResource;
@property (readonly, nonatomic) BOOL hasCacheCoordinatorHintsValue;
@property (readonly, nonatomic) BOOL hasDataValue;
@property (readonly, nonatomic) BOOL hasDateValue;
@property (readonly, nonatomic) BOOL hasIssueReadingHistoryItem;
@property (readonly, nonatomic) BOOL hasKey;
@property (readonly, nonatomic) BOOL hasNetworkSessionList;
@property (readonly, nonatomic) BOOL hasPersonalizationLocalData;
@property (readonly, nonatomic) BOOL hasPrivateDataControllerSyncState;
@property (readonly, nonatomic) BOOL hasReadingHistoryItem;
@property (readonly, nonatomic) BOOL hasRecordData;
@property (readonly, nonatomic) BOOL hasStringValue;
@property (nonatomic) BOOL hasValueType;
@property (strong, nonatomic) NTPBIssueReadingHistoryItem *issueReadingHistoryItem; // @synthesize issueReadingHistoryItem=_issueReadingHistoryItem;
@property (strong, nonatomic) NSString *key; // @synthesize key=_key;
@property (strong, nonatomic) NTPBNetworkSessionList *networkSessionList; // @synthesize networkSessionList=_networkSessionList;
@property (strong, nonatomic) NTPBPersonalizationLocalData *personalizationLocalData; // @synthesize personalizationLocalData=_personalizationLocalData;
@property (strong, nonatomic) NTPBPrivateDataControllerSyncState *privateDataControllerSyncState; // @synthesize privateDataControllerSyncState=_privateDataControllerSyncState;
@property (strong, nonatomic) NTPBReadingHistoryItem *readingHistoryItem; // @synthesize readingHistoryItem=_readingHistoryItem;
@property (strong, nonatomic) NSData *recordData; // @synthesize recordData=_recordData;
@property (strong, nonatomic) NSString *stringValue; // @synthesize stringValue=_stringValue;
@property (nonatomic) int valueType; // @synthesize valueType=_valueType;

- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;

@end

