//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <NewsTransport/NSCopying-Protocol.h>

@class NSMutableArray, NSString;

@interface NTPBBundleSubscriberInfo : PBCodable <NSCopying>
{
    long long _startTimestamp;
    int _bundleSubscriptionStatus;
    NSMutableArray *_subscribedChannelIds;
    NSString *_userId;
    NSString *_userStorefrontId;
    BOOL _isStoreDemoModeEnabled;
    struct {
        unsigned int startTimestamp:1;
        unsigned int bundleSubscriptionStatus:1;
        unsigned int isStoreDemoModeEnabled:1;
    } _has;
}

@property (nonatomic) int bundleSubscriptionStatus; // @synthesize bundleSubscriptionStatus=_bundleSubscriptionStatus;
@property (nonatomic) BOOL hasBundleSubscriptionStatus;
@property (nonatomic) BOOL hasIsStoreDemoModeEnabled;
@property (nonatomic) BOOL hasStartTimestamp;
@property (readonly, nonatomic) BOOL hasUserId;
@property (readonly, nonatomic) BOOL hasUserStorefrontId;
@property (nonatomic) BOOL isStoreDemoModeEnabled; // @synthesize isStoreDemoModeEnabled=_isStoreDemoModeEnabled;
@property (nonatomic) long long startTimestamp; // @synthesize startTimestamp=_startTimestamp;
@property (strong, nonatomic) NSMutableArray *subscribedChannelIds; // @synthesize subscribedChannelIds=_subscribedChannelIds;
@property (strong, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property (strong, nonatomic) NSString *userStorefrontId; // @synthesize userStorefrontId=_userStorefrontId;

+ (Class)subscribedChannelIdsType;
- (void).cxx_destruct;
- (int)StringAsBundleSubscriptionStatus:(id)arg1;
- (void)addSubscribedChannelIds:(id)arg1;
- (id)bundleSubscriptionStatusAsString:(int)arg1;
- (void)clearSubscribedChannelIds;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)subscribedChannelIdsAtIndex:(unsigned long long)arg1;
- (unsigned long long)subscribedChannelIdsCount;
- (void)writeTo:(id)arg1;

@end

