//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _MKRouteETA : NSObject
{
    int _status;
    double _distance;
    unsigned long long _transportType;
    double _travelTime;
    double _responseTime;
}

@property (nonatomic) double distance; // @synthesize distance=_distance;
@property (readonly, nonatomic) double responseTime; // @synthesize responseTime=_responseTime;
@property (nonatomic) int status; // @synthesize status=_status;
@property (nonatomic) unsigned long long transportType; // @synthesize transportType=_transportType;
@property (nonatomic) double travelTime; // @synthesize travelTime=_travelTime;

+ (id)routeETAWithDistance:(double)arg1 travelTime:(double)arg2 transportType:(unsigned long long)arg3;
+ (id)routeETAWithDistance:(double)arg1 travelTime:(double)arg2 transportType:(unsigned long long)arg3 status:(int)arg4;

@end

