//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PhotosGraph/NSObject-Protocol.h>

@class NSData, NSDate, NSString, VNSceneprint;

@protocol CLSSimilarlyStackableItem <NSObject>

@property (readonly) NSData *clsDistanceIdentity;
@property (readonly) NSString *clsIdentifier;
@property (readonly) VNSceneprint *clsSceneprint;
@property (readonly) NSDate *cls_universalDate;

@end

