//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PhotosGraph/PGGraphOptimizedNode.h>

@class NSArray, NSNumber, NSSet, NSString;

@interface PGGraphSocialGroupNode : PGGraphOptimizedNode
{
    NSNumber *_uuid;
    float _weight;
}

@property (readonly, nonatomic) BOOL isFrequentSocialGroup;
@property (readonly, nonatomic) NSSet *momentNodes;
@property (readonly) unsigned long long numberOfMomentNodes;
@property (readonly) unsigned long long numberOfPersonNodes;
@property (readonly, nonatomic) NSSet *personNodes;
@property (readonly, nonatomic) unsigned long long rank;
@property (readonly) long long socialGroupID;
@property (readonly, nonatomic) NSString *socialGroupName;
@property (readonly, nonatomic) NSArray *sortedPersonNodes;

+ (id)weightSortDescriptors;
- (void).cxx_destruct;
- (id)UUID;
- (id)description;
- (unsigned short)domain;
- (void)enumerateMomentNodesUsingBlock:(CDUnknownBlockType)arg1;
- (void)enumeratePersonNodesUsingBlock:(CDUnknownBlockType)arg1;
- (BOOL)hasProperties:(id)arg1;
- (id)initWithLabel:(id)arg1 domain:(unsigned short)arg2 weight:(float)arg3;
- (id)initWithWeight:(float)arg1;
- (id)label;
- (id)propertyDictionary;
- (void)setLocalProperties:(id)arg1;
- (void)setWeight:(float)arg1;
- (float)weight;

@end

