//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PhotosGraph/NSObject-Protocol.h>

@class NSString, PGGraphNamingProcessor;

@protocol PGNamingAnalyzer <NSObject>
- (id)initWithNamingProcessor:(PGGraphNamingProcessor *)arg1;
- (NSString *)name;
- (void)runAnalysisWithProgressBlock:(void (^)(double, BOOL *))arg1;
@end

