//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSExtensionContext.h>

#import <AudioToolbox/AUAudioUnitHostProtocol-Protocol.h>
#import <AudioToolbox/_AURemoteParameterSynchronization-Protocol.h>

@class AUAudioUnit_XH, NSExtension, NSUUID;
@protocol AUAudioUnitXPCProtocol;

@interface AUHostExtensionContext : NSExtensionContext <AUAudioUnitHostProtocol, _AURemoteParameterSynchronization>
{
    NSExtension *_extension;
    NSUUID *_requestIdentifier;
    AUAudioUnit_XH *_audioUnit;
    id<AUAudioUnitXPCProtocol> _remote;
}

@property (nonatomic) AUAudioUnit_XH *audioUnit; // @synthesize audioUnit=_audioUnit;
@property (strong, nonatomic) NSExtension *extension; // @synthesize extension=_extension;
@property (nonatomic) id<AUAudioUnitXPCProtocol> remote; // @synthesize remote=_remote;
@property (strong, nonatomic) NSUUID *requestIdentifier; // @synthesize requestIdentifier=_requestIdentifier;

+ (id)_extensionAuxiliaryHostProtocol;
+ (id)_extensionAuxiliaryVendorProtocol;
- (id)_derivedExtensionAuxiliaryHostProtocol;
- (void)dealloc;
- (void)propertiesChanged:(id)arg1;
- (void)syncParameter:(unsigned long long)arg1 value:(float)arg2 extOriginator:(unsigned long long)arg3 hostTime:(unsigned long long)arg4 eventType:(unsigned int)arg5;

@end

