//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary;

@interface HKDataCategoryController : NSObject
{
    NSMutableArray *_dataCategories;
    NSMutableDictionary *_dataCategoriesByCategoryID;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)allDataCategories;
- (id)categoryWithID:(long long)arg1;
- (id)init;

@end

