//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <NewsUI/SXVideoShareabilityProviding-Protocol.h>

@class NSString;

@interface NUVideoShareabilityProvider : NSObject <SXVideoShareabilityProviding>
{
    BOOL _sharingEnabled;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly, nonatomic, getter=isSharingEnabled) BOOL sharingEnabled; // @synthesize sharingEnabled=_sharingEnabled;
@property (readonly) Class superclass;

- (id)init;
- (id)initWithSharingEnabled:(BOOL)arg1;
- (BOOL)isVideoShareable:(id)arg1;

@end

