//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol NSObject;

@interface NMSObfuscatableDescriptionItem : NSObject
{
    BOOL _obfuscated;
    NSString *_format;
    id<NSObject> _value;
}

@property (strong, nonatomic) NSString *format; // @synthesize format=_format;
@property (nonatomic) BOOL obfuscated; // @synthesize obfuscated=_obfuscated;
@property (strong, nonatomic) id<NSObject> value; // @synthesize value=_value;

- (void).cxx_destruct;
- (id)initWithFormat:(id)arg1 value:(id)arg2 obfuscated:(BOOL)arg3;

@end

