//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface ARCoachingHeuristic : NSObject
{
    BOOL _satisfied;
}

@property (readonly, nonatomic) long long requirements;
@property (nonatomic) BOOL satisfied; // @synthesize satisfied=_satisfied;

- (void)updateWithFrame:(id)arg1;

@end

