//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ARKit/ARImageBasedTechnique.h>

@class ARWorldTrackingErrorData, ARWorldTrackingOptions, ARWorldTrackingPoseData, ARWorldTrackingReferenceAnchorData, NSDictionary, NSHashTable, NSObject;
@protocol OS_dispatch_semaphore;

@interface ARWorldTrackingTechnique : ARImageBasedTechnique
{
    NSHashTable *_observers;
    NSObject<OS_dispatch_semaphore> *_observersSemaphore;
    BOOL _useFixedIntrinsics;
    long long _vioHandleState;
    NSObject<OS_dispatch_semaphore> *_vioHandleStateSemaphore;
    NSObject<OS_dispatch_semaphore> *_vioObjectDetectionSemaphore;
    ARWorldTrackingReferenceAnchorData *_anchorData;
    ARWorldTrackingErrorData *_errorData;
    ARWorldTrackingPoseData *_cachedPoseData;
    long long _reinitializationAttempts;
    long long _reinitializationAttemptsAtInitialization;
    double _lastRelocalizationTimestamp;
    double _lastQualityKeyframeTimestamp;
    long long _previousKeyframeCount;
    double _lastPoseTrackingMapTimestamp;
    double _lastMajorRelocalizationTimestamp;
    double _lastPoseMajorRelocalizationTimestamp;
    BOOL _relocalizingAfterSensorDataDrop;
    BOOL _didRelocalize;
    BOOL _didClearMap;
    NSObject<OS_dispatch_semaphore> *_resultSemaphore;
    double _minVergenceAngleCosine;
    double _resultLatency;
    BOOL _allowPoseGraphUpdates;
    NSDictionary *_objectDetectionOptions;
    ARWorldTrackingOptions *_mutableOptions;
}

@property (strong) ARWorldTrackingOptions *mutableOptions; // @synthesize mutableOptions=_mutableOptions;
@property (readonly, copy, nonatomic) ARWorldTrackingOptions *options;

+ (BOOL)isSupported;
+ (BOOL)supportsVideoResolution:(struct CGSize)arg1;
- (void).cxx_destruct;
- (void)addObserver:(id)arg1;
- (void)addReferenceAnchors:(id)arg1;
- (CDStruct_14d5dc5e)cameraTransformAtTimestamp:(double)arg1;
- (void)clearMap;
- (id)getObservers;
- (id)init;
- (id)initWithOptions:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (void)loadSurfaceData:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)removeReferenceAnchors:(id)arg1;
- (id)serializeMapData;
- (id)serializeSurfaceData;
- (BOOL)setupObjectDetection:(id)arg1;
- (long long)vioHandleState;

@end

