//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MediaPlayer/MPAsyncOperation.h>

@class MPMediaLibrary, NSArray;

@interface MPModelLibraryStoreIDsImportChangeRequestOperation : MPAsyncOperation
{
    BOOL _shouldLibraryAdd;
    MPMediaLibrary *_mediaLibrary;
    NSArray *_storeIDs;
    CDUnknownBlockType _responseHandler;
}

@property (strong, nonatomic) MPMediaLibrary *mediaLibrary; // @synthesize mediaLibrary=_mediaLibrary;
@property (copy, nonatomic) CDUnknownBlockType responseHandler; // @synthesize responseHandler=_responseHandler;
@property (nonatomic) BOOL shouldLibraryAdd; // @synthesize shouldLibraryAdd=_shouldLibraryAdd;
@property (copy, nonatomic) NSArray *storeIDs; // @synthesize storeIDs=_storeIDs;

- (void).cxx_destruct;
- (void)execute;

@end

