//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIAccessibilityElement.h>

@class MISSING_TYPE;

@interface _TtC9TeaCharts30LineSeriesAccessibilityElement : UIAccessibilityElement
{
    MISSING_TYPE *series;
    MISSING_TYPE *chartModel;
    MISSING_TYPE *interactor;
    MISSING_TYPE *dataElements;
}

@property (nonatomic) struct CGRect accessibilityFrame;

- (void).cxx_destruct;
- (id)init;
- (id)initWithAccessibilityContainer:(id)arg1;
- (id)tc_accessibilityDataSeriesGridlinePositionsForAxis:(long long)arg1;
- (BOOL)tc_accessibilityDataSeriesIncludesTrendlineInSonification;
- (id)tc_accessibilityDataSeriesMaximumValueForAxis:(long long)arg1;
- (id)tc_accessibilityDataSeriesMinimumValueForAxis:(long long)arg1;
- (id)tc_accessibilityDataSeriesName;
- (double)tc_accessibilityDataSeriesSonificationDuration;
- (BOOL)tc_accessibilityDataSeriesSupportsSonification;
- (BOOL)tc_accessibilityDataSeriesSupportsSummarization;
- (id)tc_accessibilityDataSeriesTitleForAxis:(long long)arg1;
- (long long)tc_accessibilityDataSeriesType;
- (id)tc_accessibilityDataSeriesValueDescriptionForPosition:(double)arg1 axis:(long long)arg2;
- (id)tc_accessibilityDataSeriesValuesForAxis:(long long)arg1;

@end

