//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC8VideosUI21InAppBannerLockupCell : UICollectionViewCell
{
    MISSING_TYPE *layout;
    MISSING_TYPE *bannerContentView;
    MISSING_TYPE *logoImageView;
    MISSING_TYPE *labels;
    MISSING_TYPE *decorationImageView;
    MISSING_TYPE *dividerView;
    MISSING_TYPE *parentIsInAppBanner;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

