//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <VideosUI/VUIImageLoadParams-Protocol.h>

@class NSString, NSURL;

__attribute__((visibility("hidden")))
@interface VUIPlistMediaEntityImageLoadParams : NSObject <VUIImageLoadParams>
{
    NSString *_imageIdentifier;
    NSURL *_imageURL;
    NSString *_baseImageIdentifier;
    unsigned long long _imageType;
}

@property (copy, nonatomic) NSString *baseImageIdentifier; // @synthesize baseImageIdentifier=_baseImageIdentifier;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly, copy, nonatomic) NSString *imageIdentifier; // @synthesize imageIdentifier=_imageIdentifier;
@property (nonatomic) unsigned long long imageType; // @synthesize imageType=_imageType;
@property (copy, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)init;
- (id)initWithImageURL:(id)arg1 baseImageIdentifier:(id)arg2 imageType:(unsigned long long)arg3;
- (BOOL)isEqual:(id)arg1;

@end

