//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <SpringBoardUI/SBUIActionPlatterViewControllerDelegate-Protocol.h>

@class CNMonogrammer, NSArray, NSString, SBUIActionPlatterViewController, SBUIAppIconForceTouchControllerDataProvider, _UIAssetManager;
@protocol SBUIAppIconForceTouchShortcutViewControllerDelegate;

@interface SBUIAppIconForceTouchShortcutViewController : UIViewController <SBUIActionPlatterViewControllerDelegate>
{
    SBUIActionPlatterViewController *_actionPlatterViewController;
    _UIAssetManager *_assetManager;
    CNMonogrammer *_monogrammer;
    BOOL _reversesApplicationShortcutItems;
    SBUIAppIconForceTouchControllerDataProvider *_dataProvider;
    NSArray *_applicationShortcutItems;
    long long _iconPosition;
    id<SBUIAppIconForceTouchShortcutViewControllerDelegate> _delegate;
}

@property (readonly, nonatomic) NSArray *applicationShortcutItems; // @synthesize applicationShortcutItems=_applicationShortcutItems;
@property (readonly, nonatomic) SBUIAppIconForceTouchControllerDataProvider *dataProvider; // @synthesize dataProvider=_dataProvider;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id<SBUIAppIconForceTouchShortcutViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) long long iconPosition; // @synthesize iconPosition=_iconPosition;
@property (nonatomic) BOOL reversesApplicationShortcutItems; // @synthesize reversesApplicationShortcutItems=_reversesApplicationShortcutItems;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_actionFromApplicationShortcutItem:(id)arg1;
- (id)_assetManager;
- (id)_imageFromApplicationShortcutIcon:(id)arg1;
- (id)_monogrammer;
- (BOOL)actionPlatterViewControllerShouldRespondToTouches:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDataProvider:(id)arg1 applicationShortcutItems:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;

@end

