//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TSUResourceRequestAnalyticsSender : NSObject
{
}

+ (void)sendAnalyticsForResourceRequest:(id)arg1 error:(id)arg2;
+ (void)setSharedAnalyticsSender:(id)arg1;
+ (id)sharedInstanceQueue;
- (void)sendAnalyticsForResourceRequest:(id)arg1 error:(id)arg2;

@end

