//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SilexVideo/NSObject-Protocol.h>

@class NSError;

@protocol SVPlayerStatusObserving <NSObject>

@property (copy, nonatomic, setter=onChange:) CDUnknownBlockType changeBlock;
@property (readonly, copy, nonatomic) NSError *error;
@property (readonly, nonatomic) long long status;

@end

