//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface FMXPCNotificationsUtil : NSObject
{
    NSMutableDictionary *_darwinNotificationHandlers;
    NSMutableDictionary *_distributedNotificationHandlers;
    NSObject<OS_dispatch_queue> *_modificationQueue;
}

@property (strong, nonatomic) NSMutableDictionary *darwinNotificationHandlers; // @synthesize darwinNotificationHandlers=_darwinNotificationHandlers;
@property (strong, nonatomic) NSMutableDictionary *distributedNotificationHandlers; // @synthesize distributedNotificationHandlers=_distributedNotificationHandlers;
@property (strong, nonatomic) NSObject<OS_dispatch_queue> *modificationQueue; // @synthesize modificationQueue=_modificationQueue;

+ (void)handleDarwinNotificationsWithHandlers:(id)arg1;
+ (void)handleDistributedNotificationsWithHandlers:(id)arg1;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_didReceiveDarwinNotification:(id)arg1;
- (void)_didReceiveDistributedNotification:(id)arg1 withContext:(id)arg2;
- (void)deregisterHandlerForDarwinNotification:(id)arg1;
- (void)deregisterHandlerForDistributedNotification:(id)arg1;
- (id)init;
- (BOOL)isHandlerRegisteredForDarwinNotification:(id)arg1;
- (BOOL)isHandlerRegisteredForDistributedNotification:(id)arg1;
- (void)registerHandler:(CDUnknownBlockType)arg1 forDarwinNotification:(id)arg2;
- (void)registerHandler:(CDUnknownBlockType)arg1 forDistributedNotification:(id)arg2;

@end

