//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class AMSAuthenticateRequest, AMSDialogRequest, AMSEngagementRequest;

@protocol BLUIHostServiceProtocol
- (void)handleAuthenticateRequest:(AMSAuthenticateRequest *)arg1 withReply:(void (^)(AMSAuthenticateResult *, NSError *))arg2;
- (void)handleDialogRequest:(AMSDialogRequest *)arg1 withReply:(void (^)(AMSDialogResult *, NSError *))arg2;
- (void)handleEngagementRequest:(AMSEngagementRequest *)arg1 withReply:(void (^)(AMSEngagementResult *, NSError *))arg2;
@end

