//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WorkflowKit/WFResource.h>

#import <WorkflowKit/WFWorkflowReferencing-Protocol.h>

@class NSString, WFWorkflow;

@interface WFWorkflowTypeResource : WFResource <WFWorkflowReferencing>
{
    WFWorkflow *_workflow;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (weak, nonatomic) WFWorkflow *workflow; // @synthesize workflow=_workflow;

+ (BOOL)mustBeAvailableForDisplay;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)refreshAvailability;
- (BOOL)workflowTypesAreValid;

@end

