//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ICURLPerformanceMetrics : NSObject
{
    BOOL _cachedResponse;
    BOOL _connectionReused;
    double _connectionStartTime;
    double _connectionEndTime;
    double _domainLookupStartTime;
    double _domainLookupEndTime;
    double _fetchStartTime;
    double _requestStartTime;
    double _responseStartTime;
    double _responseEndTime;
    double _secureConnectionStartTime;
    NSString *_appleTimingApp;
    NSString *_connectionType;
    NSString *_edgeNodeCacheStatus;
    NSString *_environmentDataCenter;
    NSString *_responseDate;
    unsigned long long _statusCode;
    unsigned long long _redirectCount;
    unsigned long long _requestMessageSize;
    NSString *_requestUrl;
    NSString *_resolvedIPAddress;
    unsigned long long _responseMessageSize;
}

@property (readonly, nonatomic) NSString *appleTimingApp; // @synthesize appleTimingApp=_appleTimingApp;
@property (readonly, nonatomic) BOOL cachedResponse; // @synthesize cachedResponse=_cachedResponse;
@property (readonly, nonatomic) double connectionEndTime; // @synthesize connectionEndTime=_connectionEndTime;
@property (readonly, nonatomic) BOOL connectionReused; // @synthesize connectionReused=_connectionReused;
@property (readonly, nonatomic) double connectionStartTime; // @synthesize connectionStartTime=_connectionStartTime;
@property (readonly, nonatomic) NSString *connectionType; // @synthesize connectionType=_connectionType;
@property (readonly, nonatomic) double domainLookupEndTime; // @synthesize domainLookupEndTime=_domainLookupEndTime;
@property (readonly, nonatomic) double domainLookupStartTime; // @synthesize domainLookupStartTime=_domainLookupStartTime;
@property (readonly, nonatomic) NSString *edgeNodeCacheStatus; // @synthesize edgeNodeCacheStatus=_edgeNodeCacheStatus;
@property (readonly, nonatomic) NSString *environmentDataCenter; // @synthesize environmentDataCenter=_environmentDataCenter;
@property (readonly, nonatomic) double fetchStartTime; // @synthesize fetchStartTime=_fetchStartTime;
@property (readonly, nonatomic) unsigned long long redirectCount; // @synthesize redirectCount=_redirectCount;
@property (readonly, nonatomic) unsigned long long requestMessageSize; // @synthesize requestMessageSize=_requestMessageSize;
@property (readonly, nonatomic) double requestStartTime; // @synthesize requestStartTime=_requestStartTime;
@property (readonly, nonatomic) NSString *requestUrl; // @synthesize requestUrl=_requestUrl;
@property (readonly, nonatomic) NSString *resolvedIPAddress; // @synthesize resolvedIPAddress=_resolvedIPAddress;
@property (readonly, nonatomic) NSString *responseDate; // @synthesize responseDate=_responseDate;
@property (readonly, nonatomic) double responseEndTime; // @synthesize responseEndTime=_responseEndTime;
@property (readonly, nonatomic) unsigned long long responseMessageSize; // @synthesize responseMessageSize=_responseMessageSize;
@property (readonly, nonatomic) double responseStartTime; // @synthesize responseStartTime=_responseStartTime;
@property (readonly, nonatomic) double secureConnectionStartTime; // @synthesize secureConnectionStartTime=_secureConnectionStartTime;
@property (readonly, nonatomic) unsigned long long statusCode; // @synthesize statusCode=_statusCode;

- (void).cxx_destruct;
- (id)initWithTransactionMetrics:(id)arg1 request:(id)arg2;

@end

