//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSXPCConnection;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface SNAnalysisClient : NSObject
{
    CDUnknownBlockType _connectionToServerGenerator;
    NSXPCConnection *_xpcConnectionToServer;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableArray *_pendingInvalidationHandlers;
}

+ (id)defaultClient;
+ (id)newConnectionToMachServiceWithName:(id)arg1 lostConnectionHandler:(CDUnknownBlockType)arg2 queue:(id)arg3;
- (void).cxx_destruct;
- (id)_connectionToServerWithInvalidationHandler:(CDUnknownBlockType)arg1 queue:(id)arg2;
- (id)_createRemoteSystemAudioAnalyzerWithInvalidationHandler:(CDUnknownBlockType)arg1 queue:(id)arg2;
- (void)_handleLostConnection;
- (id)_remoteResourceCoordinatorWithInvalidationHandler:(CDUnknownBlockType)arg1 queue:(id)arg2;
- (id)createRemoteSystemAudioAnalyzerWithInvalidationHandler:(CDUnknownBlockType)arg1 queue:(id)arg2;
- (id)init;
- (id)initToConnectToMachServiceWithName:(id)arg1 queue:(id)arg2;
- (id)initWithConnectionGenerator:(CDUnknownBlockType)arg1 queue:(id)arg2;

@end

