//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BiomePubSub/BPSSubscription.h>

#import <BiomePubSub/BPSSubscriber-Protocol.h>

@class NSString;
@protocol BPSSubscriber;

@interface BPSFilterProducer : BPSSubscription <BPSSubscriber>
{
    struct os_unfair_lock_s _lock;
    id<BPSSubscriber> _downstream;
    long long _state;
    BPSSubscription *_subscription;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (strong, nonatomic) id<BPSSubscriber> downstream; // @synthesize downstream=_downstream;
@property (readonly) unsigned long long hash;
@property (nonatomic) long long state; // @synthesize state=_state;
@property (strong, nonatomic) BPSSubscription *subscription; // @synthesize subscription=_subscription;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)cancel;
- (id)initWithDownstream:(id)arg1;
- (void)receiveCompletion:(id)arg1;
- (long long)receiveInput:(id)arg1;
- (id)receiveNewValue:(id)arg1;
- (void)receiveSubscription:(id)arg1;
- (void)requestDemand:(long long)arg1;
- (id)upstreamSubscriptions;

@end

