//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC9SeymourUI40RemoteBrowsingGuestPairingViewController : UIViewController
{
    MISSING_TYPE *presenter;
    MISSING_TYPE *animationState;
    MISSING_TYPE *layout;
    MISSING_TYPE *frameMarkers;
    MISSING_TYPE *animationImageView;
    MISSING_TYPE *frames;
    MISSING_TYPE *indicatorView;
    MISSING_TYPE *titleLabel;
    MISSING_TYPE *subtitleLabel;
    MISSING_TYPE *captionLabel;
    MISSING_TYPE *stackView;
    MISSING_TYPE *$__lazy_storage_$_appOpeningSequence;
    MISSING_TYPE *$__lazy_storage_$_pairingSuccessfulSequence;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)arg1;

@end

