//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@interface UIPDFHighlightLayer : CALayer
{
    struct CGPath *_clipPath;
    struct CGPath *_borderPath;
    struct CGPoint offset;
}

@property (nonatomic) struct CGPath *borderPath; // @dynamic borderPath;
@property (nonatomic) struct CGPath *clipPath; // @dynamic clipPath;
@property (nonatomic) struct CGPoint offset; // @synthesize offset;

- (void)dealloc;

@end

