//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SearchUI/SearchUIRowModel.h>

@class NSArray;

@interface SearchUIHorizontallyScrollingCardSectionRowModel : SearchUIRowModel
{
    NSArray *_cardSectionRowModels;
}

@property (strong) NSArray *cardSectionRowModels; // @synthesize cardSectionRowModels=_cardSectionRowModels;

- (void).cxx_destruct;
- (id)cardSection;
- (Class)cellViewClass;
- (BOOL)hasLeadingImage;
- (id)initWithResults:(id)arg1;
- (id)reuseIdentifier;

@end

