//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreUI/CUIStructuredThemeStore.h>

@class NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface CUIMutableStructuredThemeStore : CUIStructuredThemeStore
{
    NSString *_identifier;
    NSMutableDictionary *_memoryStore;
    NSMutableDictionary *_nameIdentifierStore;
    int _maxNameIdentifier;
    NSMutableDictionary *_apperanceNameIdentifierStore;
    int _maxApperanceNameIdentifier;
    NSMutableDictionary *_renditionInfoStore;
}

- (void)_addRenditionInfoForImageWithName:(id)arg1 andKey:(struct _renditionkeytoken *)arg2;
- (void)_removeRenditionInfoForImageWithName:(id)arg1;
- (id)allImageNames;
- (unsigned short)appearanceIdentifierForName:(id)arg1;
- (id)appearances;
- (BOOL)canGetRenditionWithKey:(const struct _renditionkeytoken *)arg1;
- (void)clearRenditionCache;
- (void)dealloc;
- (id)defaultAppearanceName;
- (id)imagesWithName:(id)arg1;
- (id)initWithIdentifier:(id)arg1;
- (void)insertCGImage:(struct CGImage *)arg1 withName:(id)arg2 andDescription:(id)arg3;
- (const struct _renditionkeyfmt *)keyFormat;
- (long long)maximumRenditionKeyTokenCount;
- (id)nameForAppearanceIdentifier:(unsigned short)arg1;
- (void)removeImageNamed:(id)arg1 withDescription:(id)arg2;
- (id)renditionInfoForIdentifier:(unsigned short)arg1;
- (struct _renditionkeytoken *)renditionKeyForAssetWithName:(id)arg1 withDescription:(id)arg2;
- (const struct _renditionkeytoken *)renditionKeyForName:(id)arg1;
- (const struct _renditionkeytoken *)renditionKeyForName:(id)arg1 cursorHotSpot:(struct CGPoint *)arg2;
- (id)renditionWithKey:(const struct _renditionkeytoken *)arg1;
- (id)renditionWithKey:(const struct _renditionkeytoken *)arg1 usingKeySignature:(id)arg2;
- (BOOL)usesCUISystemThemeRenditionKey;

@end

