//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import <AVKit/AVScrollViewObserverContentView-Protocol.h>

@class AVCABackdropLayerView, AVExternalPlaybackIndicatorView, AVPlaybackControlsView, AVScrollViewObserver, AVStyleSheet, AVTurboModePlaybackControlsPlaceholderView, NSMutableDictionary, NSNumber, NSString, UIImageView, __AVPlayerLayerView;
@protocol AVPlaybackContentContainer, AVPlayerViewControllerContentViewDelegate;

__attribute__((visibility("hidden")))
@interface AVPlayerViewControllerContentView : UIView <AVScrollViewObserverContentView>
{
    BOOL _shouldLoadPlaybackControlsHint;
    BOOL _canAutomaticallyZoomLetterboxVideos;
    BOOL _styleSheetShouldUseCompactFullScreenItemSize;
    BOOL _needsInitialLayout;
    NSString *_automaticVideoGravity;
    AVExternalPlaybackIndicatorView *_externalPlaybackIndicatorView;
    UIImageView *_unsupportedContentIndicatorView;
    UIImageView *_audioOnlyIndicatorView;
    UIView *_iAdPreRollView;
    id<AVPlayerViewControllerContentViewDelegate> _delegate;
    UIView<AVPlaybackContentContainer> *_playbackContentContainerView;
    UIView *_interactiveContentOverlayView;
    AVPlaybackControlsView *_playbackControlsView;
    AVTurboModePlaybackControlsPlaceholderView *_turboModePlaybackControlsPlaceholderView;
    __AVPlayerLayerView *_playerLayerView;
    NSMutableDictionary *_targetVideoGravities;
    AVCABackdropLayerView *_backdropLayerView;
    NSString *_externalPlaybackIndicatorTitle;
    NSString *_externalPlaybackIndicatorSubtitle;
    AVStyleSheet *_styleSheet;
    AVScrollViewObserver *_scrollingObserver;
    struct UIEdgeInsets _edgeInsetsForLetterboxedContent;
    struct UIEdgeInsets _videoContentInset;
}

@property (readonly, nonatomic) UIImageView *audioOnlyIndicatorView; // @synthesize audioOnlyIndicatorView=_audioOnlyIndicatorView;
@property (readonly, nonatomic) UIImageView *audioOnlyIndicatorViewIfLoaded;
@property (copy, nonatomic) NSString *automaticVideoGravity; // @synthesize automaticVideoGravity=_automaticVideoGravity;
@property (readonly, nonatomic) AVCABackdropLayerView *backdropLayerView; // @synthesize backdropLayerView=_backdropLayerView;
@property (nonatomic) BOOL canAutomaticallyZoomLetterboxVideos; // @synthesize canAutomaticallyZoomLetterboxVideos=_canAutomaticallyZoomLetterboxVideos;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id<AVPlayerViewControllerContentViewDelegate> delegate; // @synthesize delegate=_delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic) struct UIEdgeInsets edgeInsetsForLetterboxedContent; // @synthesize edgeInsetsForLetterboxedContent=_edgeInsetsForLetterboxedContent;
@property (copy, nonatomic) NSString *externalPlaybackIndicatorSubtitle; // @synthesize externalPlaybackIndicatorSubtitle=_externalPlaybackIndicatorSubtitle;
@property (copy, nonatomic) NSString *externalPlaybackIndicatorTitle; // @synthesize externalPlaybackIndicatorTitle=_externalPlaybackIndicatorTitle;
@property (readonly, nonatomic) AVExternalPlaybackIndicatorView *externalPlaybackIndicatorView; // @synthesize externalPlaybackIndicatorView=_externalPlaybackIndicatorView;
@property (readonly, nonatomic) AVExternalPlaybackIndicatorView *externalPlaybackIndicatorViewIfLoaded;
@property (readonly) unsigned long long hash;
@property (readonly, nonatomic) UIView *iAdPreRollView; // @synthesize iAdPreRollView=_iAdPreRollView;
@property (readonly, nonatomic) UIView *iAdPreRollViewIfLoaded;
@property (readonly, nonatomic, getter=isInAWindowAndNotScrolling) BOOL inAWindowAndNotScrolling;
@property (strong, nonatomic) UIView *interactiveContentOverlayView; // @synthesize interactiveContentOverlayView=_interactiveContentOverlayView;
@property (readonly, nonatomic) BOOL isCoveringWindow;
@property (readonly, nonatomic) NSNumber *layoutClass;
@property (nonatomic) BOOL needsInitialLayout; // @synthesize needsInitialLayout=_needsInitialLayout;
@property (strong, nonatomic) UIView<AVPlaybackContentContainer> *playbackContentContainerView; // @synthesize playbackContentContainerView=_playbackContentContainerView;
@property (readonly, nonatomic) AVPlaybackControlsView *playbackControlsView; // @synthesize playbackControlsView=_playbackControlsView;
@property (strong, nonatomic) __AVPlayerLayerView *playerLayerView; // @synthesize playerLayerView=_playerLayerView;
@property (readonly, nonatomic, getter=isScrolling) BOOL scrolling;
@property (readonly, nonatomic) AVScrollViewObserver *scrollingObserver; // @synthesize scrollingObserver=_scrollingObserver;
@property (readonly, nonatomic, getter=isScrollingQuickly) BOOL scrollingQuickly;
@property (nonatomic) BOOL shouldLoadPlaybackControlsHint; // @synthesize shouldLoadPlaybackControlsHint=_shouldLoadPlaybackControlsHint;
@property (strong, nonatomic) AVStyleSheet *styleSheet; // @synthesize styleSheet=_styleSheet;
@property (nonatomic) BOOL styleSheetShouldUseCompactFullScreenItemSize; // @synthesize styleSheetShouldUseCompactFullScreenItemSize=_styleSheetShouldUseCompactFullScreenItemSize;
@property (readonly) Class superclass;
@property (readonly, nonatomic) NSMutableDictionary *targetVideoGravities; // @synthesize targetVideoGravities=_targetVideoGravities;
@property (readonly, weak, nonatomic) AVTurboModePlaybackControlsPlaceholderView *turboModePlaybackControlsPlaceholderView; // @synthesize turboModePlaybackControlsPlaceholderView=_turboModePlaybackControlsPlaceholderView;
@property (readonly, nonatomic) UIImageView *unsupportedContentIndicatorView; // @synthesize unsupportedContentIndicatorView=_unsupportedContentIndicatorView;
@property (readonly, nonatomic) UIImageView *unsupportedContentIndicatorViewIfLoaded;
@property (nonatomic) struct UIEdgeInsets videoContentInset; // @synthesize videoContentInset=_videoContentInset;

- (void).cxx_destruct;
- (void)_applyVideoGravityIfNeeded:(long long)arg1;
- (void)_insertPlaybackControlsOrPlaceholderView:(id)arg1;
- (BOOL)_isBeingTransitionedToOrFromFullScreen;
- (void)_loadTurboModePlaybackControlsPlaceholderViewIfNeeded;
- (void)_loadTurboOrFullPlaybackControlsIfNeeded;
- (id)_mediaTimingFunctionForCurrentAnimationCurve;
- (void)_updateStyleSheet;
- (void)_updateVideoContentInsetForVideoGravity:(long long)arg1;
- (void)_updateVideoGravityDuringLayoutSubviewsAndAssertThatIfYouBreakThisMethodYouOwnThisMethod;
- (void)addPlaybackContentContainerViewIfNeeded;
- (id)avkit_backdropGroupLeader;
- (BOOL)avkit_hasFullScreenLayoutClass;
- (void)avkit_needsUpdateBackdropCaptureViewHidden;
- (void)dealloc;
- (void)didMoveToSuperview;
- (void)didMoveToWindow;
- (id)initWithFrame:(struct CGRect)arg1 playbackContentContainerView:(id)arg2 targetVideoGravities:(id)arg3;
- (BOOL)isViewDescendantOfPlaybackControlsSubview:(id)arg1;
- (void)layoutSubviews;
- (void)loadPlaybackControlsViewIfNeeded;
- (void)removeTurboModePlaybackControlsPlaceholderViewIfNeeded;
- (void)scrollViewObserverValuesDidChange:(id)arg1;
- (void)setExternalPlaybackIndicatorTitle:(id)arg1 subtitle:(id)arg2;
- (void)setShowsAudioOnlyIndicator:(BOOL)arg1;
- (void)setShowsExternalPlaybackIndicator:(BOOL)arg1;
- (void)setShowsUnsupportedContentIndicator:(BOOL)arg1;
- (void)setTargetVideoGravity:(id)arg1 forLayoutClass:(unsigned long long)arg2;

@end

