//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AVKit/NSObject-Protocol.h>

@protocol AVPlaybackControlsViewItem <NSObject>

@property (nonatomic, getter=isCollapsed) BOOL collapsed;
@property (readonly, nonatomic, getter=isCollapsedOrExcluded) BOOL collapsedOrExcluded;
@property (nonatomic) struct CGSize extrinsicContentSize;
@property (nonatomic) BOOL hasAlternateAppearance;
@property (nonatomic) BOOL hasFullScreenAppearance;
@property (nonatomic, getter=isIncluded) BOOL included;

@end

