//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "__PGButtonViewAccessibility_super.h"

@interface PGButtonViewAccessibility : __PGButtonViewAccessibility_super
{
}

+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (id)_accessibilityCustomActions;
- (BOOL)isAccessibilityElement;

@end

