//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIView;

@interface NCAuxiliaryOptionsButton : UIButton
{
    UIView *_backgroundView;
}

- (void).cxx_destruct;
- (void)_configureBackgroundViewIfNecessary;
- (void)_handleHoverGestureRecognizerEvent:(id)arg1;
- (void)_setCornerRadius:(double)arg1;
- (void)_updateBackgroundVisualStyling;
- (id)init;
- (void)layoutSubviews;
- (void)setHighlighted:(BOOL)arg1;

@end

