//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class VCPTaskProcessingService;

@interface VCPVisualIntelligenceAnalysisService : NSObject
{
    VCPTaskProcessingService *_service;
}

+ (id)service;
- (void).cxx_destruct;
- (id)init;
- (void)requestShareSheetProcessingForAssetURL:(id)arg1 withOptions:(id)arg2 andCompletionHandler:(CDUnknownBlockType)arg3;
- (void)requestShareSheetProcessingForPixelBuffer:(struct __CVBuffer *)arg1 withOptions:(id)arg2 andCompletionHandler:(CDUnknownBlockType)arg3;

@end

