//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SAObjects/SADomainObject.h>

@class NSArray, NSNumber, NSString, SAReminderRecurrence, SAReminderTrigger;

@interface SAReminderListObject : SADomainObject
{
}

@property (copy, nonatomic) NSString *accountName;
@property (copy, nonatomic) NSString *name;
@property (strong, nonatomic) SAReminderRecurrence *recurrence;
@property (strong, nonatomic) SAReminderTrigger *reminderTrigger;
@property (copy, nonatomic) NSArray *reminders;
@property (copy, nonatomic) NSArray *remindersToCreate;
@property (copy, nonatomic) NSNumber *totalNumOfReminders;

+ (id)listObject;
+ (id)listObjectWithDictionary:(id)arg1 context:(id)arg2;
- (id)encodedClassName;
- (id)groupIdentifier;

@end

