//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE, NSString;

@interface _TtCC3VFX8VFXSceneP33_DBE3D0EF7607B52568E80C840F179BF911BindingImpl : _TtCs12_SwiftObject
{
    MISSING_TYPE *objectName;
    MISSING_TYPE *bindingName;
    MISSING_TYPE *type;
    MISSING_TYPE *semantic;
    MISSING_TYPE *min;
    MISSING_TYPE *max;
}

@property (nonatomic, copy) NSString *bindingName;
@property (nonatomic, readonly) NSString *identifier;
@property (nonatomic) double max; // @synthesize max;
@property (nonatomic) double min; // @synthesize min;
@property (nonatomic, copy) NSString *objectName;
@property (nonatomic) long long semantic; // @synthesize semantic;
@property (nonatomic) long long type; // @synthesize type;


@end

