//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <CoreRoutine/NSSecureCoding-Protocol.h>

@class RTRoute;

@interface RTPredictedRoute : NSObject <NSSecureCoding>
{
    RTRoute *_route;
    double _confidence;
}

@property (nonatomic) double confidence; // @synthesize confidence=_confidence;
@property (copy, nonatomic) RTRoute *route; // @synthesize route=_route;

+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithRoute:(id)arg1 confidence:(double)arg2;
- (BOOL)isEqual:(id)arg1;

@end

