//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSError, UIWebClip;

@interface SBFWebClipSanitationReport : NSObject
{
    UIWebClip *_webClip;
    long long _result;
    NSError *_error;
}

@property (readonly, copy, nonatomic) NSError *error; // @synthesize error=_error;
@property (readonly, nonatomic) long long result; // @synthesize result=_result;
@property (readonly, nonatomic) UIWebClip *webClip; // @synthesize webClip=_webClip;

- (void).cxx_destruct;
- (id)description;
- (id)initWithWebClip:(id)arg1 result:(long long)arg2 error:(id)arg3;

@end

