//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "__CCUIContentModuleContainerTransitionAccessibility_super.h"

@interface CCUIContentModuleContainerTransitionAccessibility : __CCUIContentModuleContainerTransitionAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (id)_axExpandedPlatterModalParentOfView:(id)arg1;
- (void)transitionDidEnd:(BOOL)arg1;

@end

