//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SOKerberosHelper : NSObject
{
}

+ (BOOL)_testForUPNForUser:(id)arg1;
+ (struct gss_cred_id_t_desc_struct *)acquireCredentialForUPN:(id)arg1;
+ (struct gss_cred_id_t_desc_struct *)acquireCredentialForUUID:(id)arg1;
+ (BOOL)authenticate:(struct gss_cred_id_t_desc_struct *)arg1 toServer:(id)arg2 returningToken:(id *)arg3 andError:(id *)arg4;
+ (BOOL)changePasswordForUPN:(id)arg1 withOldPassword:(id)arg2 withNewPassword:(id)arg3 withError:(id *)arg4;
+ (struct gss_cred_id_t_desc_struct *)createCredential:(id)arg1 withOptions:(id)arg2 andError:(id *)arg3;
+ (unsigned int)createGSSName:(id)arg1 gname:(struct gss_name_t_desc_struct **)arg2 error:(id *)arg3;
+ (void)destroyAllCredentials;
+ (void)destroyCredential:(id)arg1;
+ (void)destroyCredentialForUPN:(id)arg1;
+ (id)listCredentials;
+ (BOOL)validatePassword:(id)arg1 forUser:(id)arg2;

@end

