//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC13HealthProfile23CloudSyncDataSourceItem : _TtCs12_SwiftObject
{
    MISSING_TYPE *uniqueIdentifier;
    MISSING_TYPE *titleLabel;
    MISSING_TYPE *detailLabel;
    MISSING_TYPE *action;
    MISSING_TYPE *animateCloudSync;
    MISSING_TYPE *reuseIdentifier;
}

@end

