//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Silex/SXAVPlayerFactoryProviding-Protocol.h>

@class NSString;
@protocol SXAVPlayerFactory;

@interface SXAVPlayerFactoryManager : NSObject <SXAVPlayerFactoryProviding>
{
    id<SXAVPlayerFactory> _videoAVPlayerFactory;
    id<SXAVPlayerFactory> _adAVPlayerFactory;
}

@property (readonly, nonatomic) id<SXAVPlayerFactory> adAVPlayerFactory; // @synthesize adAVPlayerFactory=_adAVPlayerFactory;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, nonatomic) id<SXAVPlayerFactory> videoAVPlayerFactory; // @synthesize videoAVPlayerFactory=_videoAVPlayerFactory;

- (void).cxx_destruct;
- (id)initWithVideoAVPlayerFactory:(id)arg1 adAVPlayerFactory:(id)arg2;
- (id)playerFactoryForVideo:(id)arg1;

@end

