//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Silex/SXContentScaleManager-Protocol.h>

@class NSString;
@protocol SXContentScaleManagerDelegate;

@interface SXContentScaleManager : NSObject <SXContentScaleManager>
{
    long long _contentScale;
    double _contentScaleFactor;
    id<SXContentScaleManagerDelegate> _delegate;
}

@property (nonatomic) long long contentScale; // @synthesize contentScale=_contentScale;
@property (readonly, nonatomic) double contentScaleFactor; // @synthesize contentScaleFactor=_contentScaleFactor;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id<SXContentScaleManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)decrease;
- (void)increase;
- (id)initWithContentScale:(long long)arg1;
- (void)reset;

@end

