//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Silex/SXComponentAnimation.h>

@interface SXFadeComponentAnimation : SXComponentAnimation
{
}

@property (readonly, nonatomic) double initialAlpha; // @dynamic initialAlpha;

+ (id)typeString;
- (Class)handlerClass;
- (int)transitionBehavior;

@end

