//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Silex/NSObject-Protocol.h>

@class SXItemizedScrollView, UIView;

@protocol SXItemizedScrollViewDataSource <NSObject>
- (struct CGRect)itemizedScrollView:(SXItemizedScrollView *)arg1 frameForViewAtIndex:(unsigned long long)arg2;
- (UIView *)itemizedScrollView:(SXItemizedScrollView *)arg1 viewAtIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfViewsInItemizedScrollView:(SXItemizedScrollView *)arg1;

@optional
- (double)gutterBetweenItemsInNotPagingItemizedScrollView:(SXItemizedScrollView *)arg1;
- (BOOL)itemizedScrollView:(SXItemizedScrollView *)arg1 isAllowedToAddViewInHierarchy:(unsigned long long)arg2;
- (BOOL)itemizedScrollViewWillReindex:(SXItemizedScrollView *)arg1;
@end

