//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Silex/SXLayoutOperationFactory-Protocol.h>

@class NSString, SXDynamicAdController;
@protocol SXComponentSizerEngine;

@interface SXLayoutOperationFactory : NSObject <SXLayoutOperationFactory>
{
    id<SXComponentSizerEngine> _componentSizerEngine;
    SXDynamicAdController *_dynamicAdController;
}

@property (readonly, nonatomic) id<SXComponentSizerEngine> componentSizerEngine; // @synthesize componentSizerEngine=_componentSizerEngine;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, nonatomic) SXDynamicAdController *dynamicAdController; // @synthesize dynamicAdController=_dynamicAdController;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)initWithComponentSizerEngine:(id)arg1 dynamicAdController:(id)arg2;
- (id)layoutOperationWithViewportSize:(struct CGSize)arg1 constrainedToWidth:(double)arg2 layoutDataProvider:(id)arg3;

@end

