//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <HealthRecordsUI/WDClinicalSourcesDataProvider.h>

@interface _TtC15HealthRecordsUI27ClinicalSourcesDataProvider : WDClinicalSourcesDataProvider
{
}

- (id)initWithHealthRecordsStore:(id)arg1;

@end

