//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <HealthRecordsUI/WDMedicalRecordGroupableCell.h>

@class HKGradient, HKGradientView, NSLayoutConstraint;

__attribute__((visibility("hidden")))
@interface WDMedicalRecordCategoryMinimizedSectionHeaderCell : WDMedicalRecordGroupableCell
{
    HKGradientView *_backgroundGradientView;
    NSLayoutConstraint *_heightConstraint;
}

@property (strong, nonatomic) HKGradientView *backgroundGradientView; // @synthesize backgroundGradientView=_backgroundGradientView;
@property (strong, nonatomic) HKGradient *gradient;
@property (strong, nonatomic) NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint=_heightConstraint;

+ (double)_pillBackgroundViewHeightConstraint;
+ (id)_titleLabelFont;
- (void).cxx_destruct;
- (double)_cornerRadius;
- (void)_updateForCurrentSizeCategory;
- (void)setupSubviews;
- (void)traitCollectionDidChange:(id)arg1;

@end

