//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/NSObject-Protocol.h>

@class SBCoverSheetSlidingViewController;

@protocol SBCoverSheetSlidingViewControllerDelegate <NSObject>
- (void)coverSheetSlidingViewController:(SBCoverSheetSlidingViewController *)arg1 animateForGestureActive:(BOOL)arg2 withProgress:(double)arg3 beginBlock:(void (^)(void))arg4 endBlock:(void (^)(void))arg5;
- (void)coverSheetSlidingViewController:(SBCoverSheetSlidingViewController *)arg1 animationTickedWithProgress:(double)arg2 coverSheetFrame:(struct CGRect)arg3 gestureActive:(BOOL)arg4 forPresentationValue:(BOOL)arg5;
- (void)coverSheetSlidingViewController:(SBCoverSheetSlidingViewController *)arg1 committingToEndPresented:(BOOL)arg2;
- (void)coverSheetSlidingViewController:(SBCoverSheetSlidingViewController *)arg1 dismissGestureChangedWithProgress:(double)arg2;
- (void)coverSheetSlidingViewController:(SBCoverSheetSlidingViewController *)arg1 prepareForDismissalTransitionForReversingTransition:(BOOL)arg2 forUserGesture:(BOOL)arg3;
- (void)coverSheetSlidingViewController:(SBCoverSheetSlidingViewController *)arg1 prepareForPresentationTransitionForUserGesture:(BOOL)arg2;
- (void)coverSheetSlidingViewControllerCleanupDismissalTransition:(SBCoverSheetSlidingViewController *)arg1;
- (void)coverSheetSlidingViewControllerCleanupInterstitialTransition:(SBCoverSheetSlidingViewController *)arg1;
- (void)coverSheetSlidingViewControllerCleanupPresentationTransition:(SBCoverSheetSlidingViewController *)arg1;
- (void)coverSheetSlidingViewControllerCleanupRubberBandedPresentationTransition:(SBCoverSheetSlidingViewController *)arg1;
- (BOOL)coverSheetSlidingViewControllerContentShouldAutoRotateWhenNotVisible:(SBCoverSheetSlidingViewController *)arg1;
- (void)coverSheetSlidingViewControllerDidPassRubberBandThreshold:(SBCoverSheetSlidingViewController *)arg1;
- (void)coverSheetSlidingViewControllerPrepareForRubberBandedPresentationTransition:(SBCoverSheetSlidingViewController *)arg1;
- (void)coverSheetSlidingViewControllerUserPresentGestureBegan:(SBCoverSheetSlidingViewController *)arg1;
- (BOOL)hasContentUnderCoverSheetSlidingViewController:(SBCoverSheetSlidingViewController *)arg1;
@end

