//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface SBHardwareButtonActionList : NSObject
{
    long long _performQueueNestCount;
    BOOL _buttonDown;
    NSMutableArray *_actionBlocks;
}

@property (strong, nonatomic) NSMutableArray *actionBlocks; // @synthesize actionBlocks=_actionBlocks;
@property (nonatomic, getter=isButtonDown) BOOL buttonDown; // @synthesize buttonDown=_buttonDown;

- (void).cxx_destruct;
- (void)performQueuedButtonUpActions;
- (void)scheduleButtonUpActionBlock:(CDUnknownBlockType)arg1;

@end

