//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBProximitySensorControlling-Protocol.h>

@class NSMutableArray, NSString, SBHIDUILockAssertion;
@protocol BSInvalidatable;

@interface SBHIDInterface : NSObject <SBProximitySensorControlling>
{
    unsigned long long _lockState;
    NSMutableArray *_assertions;
    id<BSInvalidatable> _dispatchingAssertion;
    SBHIDUILockAssertion *_pocketTouchesAssertion;
    BOOL _proximityDetectionEnabled;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) BOOL pocketTouchesExpected;
@property (nonatomic, getter=isProximityDetectionEnabled) BOOL proximityDetectionEnabled;
@property (readonly) Class superclass;

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_reevaluateLockStateForSource:(long long)arg1;
- (void)_setLockState:(unsigned long long)arg1 source:(long long)arg2;
- (id)_suspendProximity:(BOOL)arg1 suspendMultitouch:(BOOL)arg2 disableTapToWake:(BOOL)arg3 source:(long long)arg4 reason:(id)arg5;
- (id)addStartupHIDLockAssertion;
- (id)init;
- (void)reevaluateHIDLockAssertionsForSource:(long long)arg1;
- (void)removeHIDLockAssertion:(id)arg1 source:(long long)arg2;
- (void)resetProximityCalibration;
- (id)suspendMultitouchForSource:(long long)arg1 reason:(id)arg2;
- (id)suspendProximityDetectionAndMultitouchForSource:(long long)arg1 disableTapToWake:(BOOL)arg2 reason:(id)arg3;
- (id)suspendProximityDetectionForSource:(long long)arg1 reason:(id)arg2;

@end

