//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBModelessSyncController : NSObject
{
    BOOL _isAppSyncing;
    BOOL _isSyncing;
    int _syncRegistrationToken;
    int _iCloudRestoreToken;
    BOOL _restoringFromICloud;
    BOOL _isAutoSyncing;
    BOOL _isWirelessSyncing;
}

@property (readonly, nonatomic) BOOL isAppSyncing; // @synthesize isAppSyncing=_isAppSyncing;
@property (readonly, nonatomic) BOOL isAutoSyncing; // @synthesize isAutoSyncing=_isAutoSyncing;
@property (readonly, nonatomic) BOOL isRestoringFromICloud;
@property (readonly, nonatomic) BOOL isSyncing; // @synthesize isSyncing=_isSyncing;
@property (readonly, nonatomic) BOOL isWirelessSyncing; // @synthesize isWirelessSyncing=_isWirelessSyncing;

+ (id)sharedInstance;
- (void)_appSyncStateChanged;
- (void)_beginObservingICloudRestoreStatus;
- (void)_endObservingICloudRestoreStatus;
- (void)_iCloudStatusChanged;
- (void)_setAppSyncState:(BOOL)arg1;
- (void)_updateIconsForStateChange;
- (void)beginMonitoring;
- (void)dealloc;
- (void)endMonitoring;
- (void)gotLowBatteryWarning;
- (id)init;

@end

