//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIStatusBar;

@interface SBStatusBarContainer : NSObject
{
    UIStatusBar *_statusBar;
    NSString *_reason;
}

@property (strong, nonatomic) NSString *reason; // @synthesize reason=_reason;
@property (weak, nonatomic) UIStatusBar *statusBar; // @synthesize statusBar=_statusBar;

- (void).cxx_destruct;
- (void)dealloc;
- (id)description;

@end

