//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBIconIndexNodeObserver-Protocol.h>
#import <SpringBoard/SBWallpaperObserver-Protocol.h>

@class NSString, SBFMappedImageCache, SBIconController, SBIconModel, SBWallpaperController;

@interface SBWallpaperPreviewSnapshotCache : NSObject <SBIconIndexNodeObserver, SBWallpaperObserver>
{
    SBWallpaperController *_wallpaperController;
    SBFMappedImageCache *_imageCache;
    long long _invalidatedLocations;
    SBIconController *_iconController;
    SBIconModel *_model;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)cacheKeyForVariant:(long long)arg1 options:(unsigned long long)arg2;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_backlightFadeFinished;
- (id)_homeScreenSnapshotProviderWithOptions:(unsigned long long)arg1 wallpaperImage:(id)arg2;
- (void)_iconControllerDidChangeIconModel:(id)arg1;
- (id)_lockScreenSnapshotProviderWithOptions:(unsigned long long)arg1 wallpaperImage:(id)arg2;
- (void)_modelDidLayout;
- (void)_modelWillLayout;
- (long long)_orientationForOptions:(unsigned long long)arg1;
- (id)_snapshotProviderForVariant:(long long)arg1 options:(unsigned long long)arg2 wallpaperImage:(id)arg3;
- (void)_switchToIconModel:(id)arg1;
- (void)dealloc;
- (id)homeScreenSnapshot;
- (id)init;
- (id)initWithImageCache:(id)arg1 iconController:(id)arg2 wallpaperController:(id)arg3;
- (void)invalidateSnapshotsForLocations:(long long)arg1;
- (id)lockScreenSnapshot;
- (void)node:(id)arg1 didAddContainedNodeIdentifiers:(id)arg2;
- (void)node:(id)arg1 didRemoveContainedNodeIdentifiers:(id)arg2;
- (void)nodeDidMoveContainedNodes:(id)arg1;
- (void)regenerateSnapshotsForLocations:(long long)arg1;
- (id)snapshotForVariant:(long long)arg1 options:(unsigned long long)arg2 wallpaperImage:(id)arg3;
- (void)wallpaperDidChangeForVariant:(long long)arg1;

@end

