//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/WGWidgetListViewControllerDelegate-Protocol.h>

@class WGMajorListViewController;

@protocol WGMajorListViewControllerDelegate <WGWidgetListViewControllerDelegate>

@optional
- (void)majorListViewControllerDidChangeHeaderVisibility:(WGMajorListViewController *)arg1;
@end

