//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface HAMenstrualAlgorithmsPrediction : NSObject
{
    BOOL _isOngoingMenstruation;
    unsigned int _julianDayOfWindowStart;
    NSArray *_startProbability;
    NSArray *_endProbability;
    NSArray *_convolvedProbability;
    double _startProbabilityMean;
    double _endProbabilityMean;
    double _convolvedProbabilityMean;
    double _startProbabilityStdDev;
    double _endProbabilityStdDev;
    double _convolvedProbabilityStdDev;
    struct _NSRange _lowRange;
}

@property (strong, nonatomic) NSArray *convolvedProbability; // @synthesize convolvedProbability=_convolvedProbability;
@property (nonatomic) double convolvedProbabilityMean; // @synthesize convolvedProbabilityMean=_convolvedProbabilityMean;
@property (nonatomic) double convolvedProbabilityStdDev; // @synthesize convolvedProbabilityStdDev=_convolvedProbabilityStdDev;
@property (strong, nonatomic) NSArray *endProbability; // @synthesize endProbability=_endProbability;
@property (nonatomic) double endProbabilityMean; // @synthesize endProbabilityMean=_endProbabilityMean;
@property (nonatomic) double endProbabilityStdDev; // @synthesize endProbabilityStdDev=_endProbabilityStdDev;
@property (nonatomic) BOOL isOngoingMenstruation; // @synthesize isOngoingMenstruation=_isOngoingMenstruation;
@property (nonatomic) unsigned int julianDayOfWindowStart; // @synthesize julianDayOfWindowStart=_julianDayOfWindowStart;
@property (nonatomic) struct _NSRange lowRange; // @synthesize lowRange=_lowRange;
@property (strong, nonatomic) NSArray *startProbability; // @synthesize startProbability=_startProbability;
@property (nonatomic) double startProbabilityMean; // @synthesize startProbabilityMean=_startProbabilityMean;
@property (nonatomic) double startProbabilityStdDev; // @synthesize startProbabilityStdDev=_startProbabilityStdDev;

- (void).cxx_destruct;

@end

