//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class GEOComposedGuidanceEvent;

__attribute__((visibility("hidden")))
@interface _MNJunctionViewPreloadEvent : NSObject
{
    BOOL _needsPreload;
    GEOComposedGuidanceEvent *_junctionViewEvent;
}

@property (strong, nonatomic) GEOComposedGuidanceEvent *junctionViewEvent; // @synthesize junctionViewEvent=_junctionViewEvent;
@property (nonatomic) BOOL needsPreload; // @synthesize needsPreload=_needsPreload;

- (void).cxx_destruct;

@end

