//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <Navigation/NSCopying-Protocol.h>

@interface MNRouteCoordinate : PBCodable <NSCopying>
{
    unsigned int _index;
    float _offset;
    struct {
        unsigned int index:1;
        unsigned int offset:1;
    } _has;
}

@property (nonatomic) BOOL hasIndex;
@property (nonatomic) BOOL hasOffset;
@property (nonatomic) unsigned int index; // @synthesize index=_index;
@property (nonatomic) float offset; // @synthesize offset=_offset;

- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;

@end

