//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSTimeZone;
@protocol GEOServerFormattedString;

@interface MNTransitInstruction : NSObject
{
    long long _context;
    NSArray *_majorFormattedInstruction;
    NSArray *_minorFormattedInstruction;
    NSArray *_tertiaryFormattedInstruction;
    id<GEOServerFormattedString> _departureBarInstruction;
    id<GEOServerFormattedString> _countStopsFormattedString;
}

@property (readonly, nonatomic) long long context; // @synthesize context=_context;
@property (strong, nonatomic) id<GEOServerFormattedString> countStopsFormattedString; // @synthesize countStopsFormattedString=_countStopsFormattedString;
@property (strong, nonatomic) id<GEOServerFormattedString> departureBarInstruction; // @synthesize departureBarInstruction=_departureBarInstruction;
@property (copy) NSArray *majorFormattedInstruction; // @synthesize majorFormattedInstruction=_majorFormattedInstruction;
@property (copy) NSArray *minorFormattedInstruction; // @synthesize minorFormattedInstruction=_minorFormattedInstruction;
@property (copy) NSArray *tertiaryFormattedInstruction; // @synthesize tertiaryFormattedInstruction=_tertiaryFormattedInstruction;
@property (readonly, nonatomic) NSTimeZone *timeZoneForFormattedString;

+ (id)instructionForUncertainArrivalToStationStep:(id)arg1 context:(long long)arg2;
- (void).cxx_destruct;
- (void)_fillInInstructions;
- (id)formattedInstructionForType:(long long)arg1;
- (id)initWithContext:(long long)arg1;
- (id)instructionSet;
- (id)instructionSetsForInstructionType:(long long)arg1;
- (struct NSDictionary *)overridenInstructionsMapping;
- (void)refreshInstructionStrings;

@end

