//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AuthKit/NSObject-Protocol.h>

@class AKAppleIDAuthenticationContext, NSData, NSString;

@protocol AKAnisetteProvisioningClientProtocol <NSObject>
- (void)eraseAnisetteForContext:(AKAppleIDAuthenticationContext *)arg1 withCompletion:(void (^)(BOOL, NSError *))arg2;
- (void)fetchAnisetteDataForContext:(AKAppleIDAuthenticationContext *)arg1 provisionIfNecessary:(BOOL)arg2 withCompletion:(void (^)(AKAnisetteData *, NSError *))arg3;
- (void)legacyAnisetteDataForContext:(AKAppleIDAuthenticationContext *)arg1 DSID:(NSString *)arg2 withCompletion:(void (^)(AKAnisetteData *, NSError *))arg3;
- (void)provisionAnisetteForContext:(AKAppleIDAuthenticationContext *)arg1 withCompletion:(void (^)(BOOL, NSError *))arg2;
- (void)syncAnisetteForContext:(AKAppleIDAuthenticationContext *)arg1 withSIMData:(NSData *)arg2 completion:(void (^)(BOOL, NSError *))arg3;
@end

