//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "__QuickLookBannerControllerAccessibility_super.h"

@interface QuickLookBannerControllerAccessibility : __QuickLookBannerControllerAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)_addOrRestartBannerViewTimer;

@end

