//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ClassKit/CLSAbstractHandout.h>

#import <ClassKit/CLSRelationable-Protocol.h>

@class NSArray, NSString;

@interface CLSArchivedHandout : CLSAbstractHandout <CLSRelationable>
{
}

@property (readonly, nonatomic) NSArray *attachments;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)relations;
+ (BOOL)supportsSecureCoding;
- (id)_init;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;

@end

