//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC7NewsUI228TodayMagazineFeedDataManager : NSObject
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *group;
    MISSING_TYPE *cursor;
    MISSING_TYPE *myMagazinesModule;
    MISSING_TYPE *pluginManager;
    MISSING_TYPE *childParentPluginIdentifierMap;
    MISSING_TYPE *parentPluggableViewController;
    MISSING_TYPE *subscriptionService;
    MISSING_TYPE *readingHistory;
    MISSING_TYPE *readingList;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

