//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <NewsUI2/_TtC7NewsUI219TodayViewController.h>

#import <NewsUI2/TUScrollable-Protocol.h>

@class NSArray;

@interface _TtC7NewsUI219TodayViewController (NewsUI2) <TUScrollable>

@property (nonatomic, readonly) long long pluginItemCount;
@property (nonatomic, readonly) NSArray *pluginItemIdentifiers;
@property (nonatomic, readonly) long long pluginVisibleItemCount;

- (void)deselect;
- (void)didPullToRefreshWithSender:(id)arg1;
- (void)initializeWithCompletion:(CDUnknownBlockType)arg1;
- (void)relayoutWithCompletion:(CDUnknownBlockType)arg1;
- (void)scrollToTopAnimated:(BOOL)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)significantTimeChangeDidOccur;
- (void)startTraversingWithDirection:(long long)arg1;
- (void)tabBarSplitViewDidChangeFocusToFocus:(long long)arg1 action:(long long)arg2;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillLayoutSubviews;
@end

