//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface TSMastheadModel : NSObject
{
    MISSING_TYPE *mastheadModel;
}

@property (nonatomic, readonly) NSString *appName;
@property (nonatomic, readonly) NSString *formattedDate;

- (void).cxx_destruct;
- (id)init;
- (id)initWithType:(long long)arg1;

@end

