//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ITMLKit/IKDOMText.h>

#import <ITMLKit/IKDOMCDATASection-Protocol.h>

@interface IKDOMCDATASection : IKDOMText <IKDOMCDATASection>
{
}

- (id)nodeName;
- (long long)nodeType;

@end

