//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <CTCarrierSpace/NSSecureCoding-Protocol.h>

@class NSArray, NSString;

@interface CTCarrierSpacePlanGroupInfo : NSObject <NSSecureCoding>
{
    long long _planCategory;
    NSArray *_groupOptionsList;
    NSString *_groupId;
}

@property (strong, nonatomic) NSString *groupId; // @synthesize groupId=_groupId;
@property (strong, nonatomic) NSArray *groupOptionsList; // @synthesize groupOptionsList=_groupOptionsList;
@property (nonatomic) long long planCategory; // @synthesize planCategory=_planCategory;

+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (BOOL)isEqual:(id)arg1;

@end

