//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <NanoPassKit/PKPaymentServiceDelegate-Protocol.h>

@class NSHashTable, NSMutableDictionary, NSSet, NSString, PKPaymentService;
@protocol OS_dispatch_queue;

@interface NPKPassAssociatedInfoManager : NSObject <PKPaymentServiceDelegate>
{
    NSObject<OS_dispatch_queue> *_internalQueue;
    NSObject<OS_dispatch_queue> *_observerQueue;
    NSMutableDictionary *_passAssociatedInfoModelsByPassUniqueID;
    int _pendingAddValueUpdatedNotifyToken;
    BOOL _paymentServiceWasInterrupted;
    PKPaymentService *_paymentService;
    NSHashTable *_observers;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (strong, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property (copy) NSSet *passes;
@property (readonly, nonatomic) PKPaymentService *paymentService; // @synthesize paymentService=_paymentService;
@property (nonatomic) BOOL paymentServiceWasInterrupted; // @synthesize paymentServiceWasInterrupted=_paymentServiceWasInterrupted;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_fetchMostRecentBalancesForPass:(id)arg1;
- (void)_fetchMostRecentInfoForPass:(id)arg1;
- (void)_fetchMostRecentTransitPropertiesAndAppletStateForPass:(id)arg1;
- (void)_loadPassContentIfNeeded:(id)arg1;
- (void)_notifyObservers:(CDUnknownBlockType)arg1;
- (void)_notifyObserversOfUpdatedTransitPassInfoForModel:(id)arg1;
- (id)_transitPassBalanceModelWithPass:(id)arg1 currentModel:(id)arg2;
- (void)_updateAllPassesItemsFieldsPendingUpdateStatus;
- (void)_updatePassTransitPassesInfoManagerForPassUniqueID:(id)arg1 updateBlock:(CDUnknownBlockType)arg2;
- (void)addPass:(id)arg1;
- (id)init;
- (id)initWithPaymentService:(id)arg1;
- (id)passInfoForPassWithUniqueID:(id)arg1;
- (void)paymentPassWithUniqueIdentifier:(id)arg1 didReceiveBalanceUpdate:(id)arg2;
- (void)paymentPassWithUniqueIdentifier:(id)arg1 didUpdateWithTransitPassProperties:(id)arg2;
- (void)paymentServiceEstablishedConnection;
- (void)paymentServiceReceivedInterruption;
- (void)refreshAllPasses;
- (void)registerObserver:(id)arg1;
- (void)removePassWithUniqueID:(id)arg1;
- (void)setPendingAmount:(id)arg1 forBalanceField:(id)arg2 passWithUniqueID:(id)arg3;
- (void)unregisterObserver:(id)arg1;

@end

