//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <NanoPassKit/NSCopying-Protocol.h>

@class NPKProtoStandalonePaymentProvisioningMethodMetadata, NSString;

@interface NPKProtoStandalonePaymentProvisioningMethodMetadataDictionaryEntry : PBCodable <NSCopying>
{
    NPKProtoStandalonePaymentProvisioningMethodMetadata *_metadata;
    NSString *_type;
}

@property (readonly, nonatomic) BOOL hasMetadata;
@property (readonly, nonatomic) BOOL hasType;
@property (strong, nonatomic) NPKProtoStandalonePaymentProvisioningMethodMetadata *metadata; // @synthesize metadata=_metadata;
@property (strong, nonatomic) NSString *type; // @synthesize type=_type;

- (void).cxx_destruct;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;

@end

