//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <NanoPassKit/NPKTransientPassAssertionServerClientProtocol-Protocol.h>

@class NSString, NSXPCConnection;

@interface NPKTransientAssertion : NSObject <NPKTransientPassAssertionServerClientProtocol>
{
    NSXPCConnection *_xpcConnection;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (strong, nonatomic) NSXPCConnection *xpcConnection; // @synthesize xpcConnection=_xpcConnection;

- (void).cxx_destruct;
- (id)_remoteObjectProxy;
- (void)_resyncState;
- (void)handleDelegatedDoublePressEvent;
- (id)initWithQueue:(id)arg1;
- (void)invalidate;

@end

