//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MediaSocial/NSObject-Protocol.h>

@class MSCLVoiceRecorder;

@protocol MSCLVoiceRecorderDelegate <NSObject>

@optional
- (void)voiceRecorder:(MSCLVoiceRecorder *)arg1 didFinishWithSuccess:(BOOL)arg2;
- (void)voiceRecorder:(MSCLVoiceRecorder *)arg1 didUpdateAveragePower:(float)arg2;
- (void)voiceRecorderDidStartRecording:(MSCLVoiceRecorder *)arg1;
@end

