//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ControlCenterUI/NSObject-Protocol.h>

@class CCUIButtonController, CCUIControlCenterStatusUpdate;
@protocol CCUIControlCenterSystemAgent;

@protocol CCUIButtonControllerDelegate <NSObject>
- (void)buttonController:(CCUIButtonController *)arg1 publishStatusUpdate:(CCUIControlCenterStatusUpdate *)arg2;
- (BOOL)buttonControllerShouldUseSmallButtons:(CCUIButtonController *)arg1;
- (id<CCUIControlCenterSystemAgent>)controlCenterSystemAgent;
@end

