//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Metal/NSCopying-Protocol.h>

@class MTLFunctionConstantValues, NSString;

@interface MTLFunctionDescriptor : NSObject <NSCopying>
{
    struct MTLFunctionDescriptorPrivate _private;
}

@property (copy, nonatomic) MTLFunctionConstantValues *constantValues; // @dynamic constantValues;
@property (copy, nonatomic) NSString *name; // @dynamic name;
@property (nonatomic) unsigned long long options; // @dynamic options;
@property (copy, nonatomic) NSString *specializedName; // @dynamic specializedName;

+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)functionDescriptor;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (id)formattedDescription:(unsigned long long)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;

@end

