//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreNFC/NFCReaderSession.h>

@protocol NFCTag;

@interface NFCTagReaderSession : NFCReaderSession
{
    id<NFCTag> _connectedTag;
    id _swiftDelegateWrapper;
}

@property (readonly, strong, nonatomic) id<NFCTag> connectedTag;

+ (BOOL)readingAvailable;
- (void)_callbackDidBecomeActive;
- (void)_callbackDidInvalidateWithError:(id)arg1;
- (void)connectToTag:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (void)didDetectTags:(id)arg1;
- (id)initWithDelegate:(id)arg1 sessionDelegateType:(long long)arg2 queue:(id)arg3 pollMethod:(unsigned long long)arg4 sessionConfig:(unsigned long long)arg5;
- (id)initWithPollingOption:(long long)arg1 delegate:(id)arg2 delegateType:(long long)arg3 queue:(id)arg4;
- (id)initWithPollingOption:(long long)arg1 delegate:(id)arg2 queue:(id)arg3;
- (id)initWithPollingOption:(long long)arg1 swiftDelegate:(id)arg2 queue:(id)arg3;
- (void)restartPolling;

@end

