//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpriteKit/SKNode.h>

#import <SpriteKit/NSSecureCoding-Protocol.h>

@class AVAudioNode;

@interface SKAudioNode : SKNode <NSSecureCoding>
{
    struct SKCAudioNode *_skcAudioNode;
    BOOL _autoplayLooped;
    BOOL _positional;
}

@property (nonatomic) BOOL autoplayLooped; // @synthesize autoplayLooped=_autoplayLooped;
@property (strong, nonatomic) AVAudioNode *avAudioNode;
@property (nonatomic, getter=isPositional) BOOL positional; // @synthesize positional=_positional;

+ (id)_audioURLWithName:(id)arg1 bundle:(id)arg2;
+ (BOOL)supportsSecureCoding;
- (void)_connectToScene:(id)arg1;
- (void)_didMakeBackingNode;
- (struct SKCNode *)_makeBackingNode;
- (void)_playLooped;
- (void)_setAudioName:(id)arg1 bundle:(id)arg2;
- (id)audioFile;
- (id)audioFileName;
- (id)audioURL;
- (void)commonInit;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithAVAudioNode:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFileNamed:(id)arg1;
- (id)initWithFileNamed:(id)arg1 bundle:(id)arg2;
- (id)initWithURL:(id)arg1;
- (BOOL)isEqualToNode:(id)arg1;
- (void)setAudioFileName:(id)arg1;
- (void)setAudioURL:(id)arg1;

@end

