//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <HomeKitDaemon/HMDLogEvent.h>

#import <HomeKitDaemon/HMDAWDLogEvent-Protocol.h>

@class NSString;

@interface HMDAssistantAccessControlModifiedEvent : HMDLogEvent <HMDAWDLogEvent>
{
    BOOL _isEnabled;
    unsigned long long _options;
    unsigned long long _numEnabledAccessories;
    unsigned long long _numCapableAccessories;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) BOOL isEnabled; // @synthesize isEnabled=_isEnabled;
@property (nonatomic) unsigned long long numCapableAccessories; // @synthesize numCapableAccessories=_numCapableAccessories;
@property (nonatomic) unsigned long long numEnabledAccessories; // @synthesize numEnabledAccessories=_numEnabledAccessories;
@property (nonatomic) unsigned long long options; // @synthesize options=_options;
@property (readonly) Class superclass;

+ (id)eventWithIsEnabled:(BOOL)arg1 options:(unsigned long long)arg2 numEnabledAccessories:(unsigned long long)arg3 numCapableAccessories:(unsigned long long)arg4;
+ (void)initialize;
+ (id)uuid;
- (unsigned int)AWDMessageType;
- (id)metricForAWD;

@end

