//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <StoreKitUI/SKUIRedeemIdManagerDelegate-Protocol.h>

@class NSMutableDictionary, NSString, SKUIClientContext, SKUIRedeemIdManager, UIBarButtonItem, UITableView;
@protocol SKUIRedeemIdDelegate;

@interface SKUIRedeemIdViewController : UIViewController <SKUIRedeemIdManagerDelegate>
{
    id<SKUIRedeemIdDelegate> _delegate;
    SKUIRedeemIdManager *_manager;
    SKUIClientContext *_clientContext;
    UITableView *_tableView;
    UIBarButtonItem *_nextButton;
    NSMutableDictionary *_fields;
}

@property (strong, nonatomic) SKUIClientContext *clientContext; // @synthesize clientContext=_clientContext;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id<SKUIRedeemIdDelegate> delegate; // @synthesize delegate=_delegate;
@property (readonly, copy) NSString *description;
@property (strong, nonatomic) NSMutableDictionary *fields; // @synthesize fields=_fields;
@property (readonly) unsigned long long hash;
@property (strong, nonatomic) SKUIRedeemIdManager *manager; // @synthesize manager=_manager;
@property (strong, nonatomic) UIBarButtonItem *nextButton; // @synthesize nextButton=_nextButton;
@property (readonly) Class superclass;
@property (strong, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;

- (void).cxx_destruct;
- (void)_adjustInsetsForKeyboardFrameValue:(id)arg1;
- (void)_cancelPressed;
- (struct UIEdgeInsets)_edgeInsetsFromInsets:(struct UIEdgeInsets)arg1 usingNewTopInset:(double)arg2;
- (id)_fieldForIndexPath:(id)arg1;
- (id)_finalOutputFields;
- (void)_initializeManager;
- (void)_initializeNavigationItem;
- (void)_initializeTableView;
- (void)_keyboardDidHide:(id)arg1;
- (void)_keyboardWillShow:(id)arg1;
- (void)_nextPressed;
- (void)_refreshNavigationItem;
- (void)_reloadFooter;
- (void)_subscribeToKeyboardEvents;
- (void)_updateFieldAtIndexPath:(id)arg1 withText:(id)arg2;
- (BOOL)_validateForm;
- (id)initWithClientContext:(id)arg1;
- (void)redeemIdManager:(id)arg1 didChangeToText:(id)arg2 forCellAtIndexPath:(id)arg3;
- (void)redeemIdManager:(id)arg1 didReturnText:(id)arg2 forCellAtIndexPath:(id)arg3;
- (void)redeemIdManager:(id)arg1 movedToRowAtIndexPath:(id)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;

@end

