//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewFlowLayout.h>

#import <StoreKitUI/SKUIStorePageCollectionViewLayout-Protocol.h>

@class NSArray, NSIndexSet, NSMapTable, NSString, UIColor;

@interface SKUIStorePageCollectionViewLayout : UICollectionViewFlowLayout <SKUIStorePageCollectionViewLayout>
{
    NSString *_backdropGroupName;
    UIColor *_collectionViewBackgroundColor;
    BOOL _hasValidGradientIndexPaths;
    BOOL _hasValidIndexPathsForPinningItems;
    BOOL _hasValidPinnedBackdropViewStyle;
    BOOL _hasValidPinningLayoutInformation;
    long long _inLayoutAttributesForElementsCount;
    NSMapTable *_indexPathToItemPinningConfiguration;
    NSMapTable *_indexPathToPinningLayoutInformation;
    NSArray *_indexPathsForGradientItems;
    NSArray *_indexPathsForPinningItems;
    double _overrideContentWidth;
    long long _pinnedBackdropViewStyle;
    BOOL _rendersWithParallax;
    BOOL _rendersWithPerspective;
    struct {
        unsigned int respondsToIndexPathsForPinningItems:1;
        unsigned int respondsToPinningContentInsetForItemAtIndexPath:1;
        unsigned int respondsToPinningStyleForItemAtIndexPath:1;
        unsigned int respondsToPinningTransitionStyleForItemAtIndexPath:1;
        unsigned int respondsToWillApplyLayoutAttributes:1;
    } _collectionViewDelegateFlags;
    NSArray *_updateItems;
    BOOL _allowsPinningTransitions;
    NSIndexSet *_expandChildPageSectionsIndexSet;
}

@property (nonatomic) BOOL allowsPinningTransitions; // @synthesize allowsPinningTransitions=_allowsPinningTransitions;
@property (copy, nonatomic) NSString *backdropGroupName; // @synthesize backdropGroupName=_backdropGroupName;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (copy, nonatomic) NSIndexSet *expandChildPageSectionsIndexSet; // @synthesize expandChildPageSectionsIndexSet=_expandChildPageSectionsIndexSet;
@property (readonly) unsigned long long hash;
@property (copy, nonatomic) NSArray *indexPathsForGradientItems; // @synthesize indexPathsForGradientItems=_indexPathsForGradientItems;
@property (readonly, nonatomic) NSArray *indexPathsForPinningItems;
@property (nonatomic) double overrideContentWidth; // @synthesize overrideContentWidth=_overrideContentWidth;
@property (nonatomic) BOOL rendersWithParallax; // @synthesize rendersWithParallax=_rendersWithParallax;
@property (nonatomic) BOOL rendersWithPerspective; // @synthesize rendersWithPerspective=_rendersWithPerspective;
@property (readonly) Class superclass;

+ (Class)invalidationContextClass;
+ (Class)layoutAttributesClass;
- (void).cxx_destruct;
- (void)_alginCellsToTop:(id)arg1;
- (BOOL)_allowsBackdropDecorationForItemPinningConfiguration:(id)arg1 atIndexPath:(id)arg2;
- (void)_appendAdditionalLayoutAttributesForPinningItemsInRect:(struct CGRect)arg1 toArray:(id)arg2;
- (void)_calculatePinningLayoutInformation;
- (void)_configureCellLayoutAttributes:(id)arg1 forItemWithPinningConfiguration:(id)arg2 layoutInformation:(id)arg3 atIndexPath:(id)arg4 allowPinning:(BOOL)arg5 returningIsPinning:(out BOOL *)arg6;
- (id)_getCollectionViewUpdateItemForItemFromIndex:(long long)arg1 initalLayout:(BOOL)arg2;
- (id)_indexPathsForBackgroundGradients;
- (id)_indexPathsForPinningItems;
- (void)_invalidatePinningLayoutInformation;
- (id)_itemPinningConfigurationForItemAtIndexPath:(id)arg1;
- (id)_itemPinningLayoutInformationForItemAtIndexPath:(id)arg1;
- (id)_layoutAttributesForGradientDecorationViewAtIndexPath:(id)arg1 currentAttributes:(id)arg2;
- (id)_layoutAttributesForPinnedBackdropDecorationViewAtIndexPath:(id)arg1 pinningConfiguration:(id)arg2 layoutInformation:(id)arg3;
- (long long)_pinnedBackdropViewStyle;
- (struct UIEdgeInsets)_pinningContentInsetForItemPinningConfiguration:(id)arg1 atIndexPath:(id)arg2;
- (struct CGRect)_pinningFrameForStartingFrame:(struct CGRect)arg1 itemPinningConfiguration:(id)arg2 atIndexPath:(id)arg3;
- (long long)_pinningStyleForItemPinningConfiguration:(id)arg1 atIndexPath:(id)arg2;
- (long long)_pinningTransitionStyleForItemPinningConfiguration:(id)arg1 atIndexPath:(id)arg2;
- (struct CGRect)_targetFrameForStartingFrame:(struct CGRect)arg1 itemPinningConfiguration:(id)arg2 layoutInformation:(id)arg3 atIndexPath:(id)arg4 returningIsPinning:(out BOOL *)arg5;
- (void)_updateItemsLayoutForRect:(struct CGRect)arg1;
- (struct CGSize)collectionViewContentSize;
- (id)finalLayoutAttributesForDisappearingItemAtIndexPath:(id)arg1;
- (id)init;
- (id)initialLayoutAttributesForAppearingItemAtIndexPath:(id)arg1;
- (void)invalidateLayoutWithContext:(id)arg1;
- (id)invalidationContextForBoundsChange:(struct CGRect)arg1;
- (id)layoutAttributesForDecorationViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForUnpinnedItemAtIndexPath:(id)arg1;
- (id)pinnedLayoutAttributesForItemsInRect:(struct CGRect)arg1;
- (void)prepareForCollectionViewUpdates:(id)arg1;
- (void)prepareLayout;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;

@end

