//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <StoreKitUI/UIInterfaceActionHandlerInvocationDelegate-Protocol.h>
#import <StoreKitUI/UIViewControllerTransitioningDelegate-Protocol.h>

@class NSMutableArray, NSString, SKUIReviewInAppRatingHeaderView, SKUIStarRatingControl, UIInterfaceAction, UIStackView, UIVisualEffectView;

__attribute__((visibility("hidden")))
@interface SKUIReviewInAppRatingViewController : UIViewController <UIViewControllerTransitioningDelegate, UIInterfaceActionHandlerInvocationDelegate>
{
    BOOL _disableSubmit;
    CDUnknownBlockType _completion;
    CDUnknownBlockType _ratingHandler;
    UIVisualEffectView *_backgroundView;
    UIStackView *_stackView;
    NSMutableArray *_constraints;
    SKUIReviewInAppRatingHeaderView *_headerView;
    unsigned long long _state;
    UIInterfaceAction *_ratingControlAction;
    SKUIStarRatingControl *_ratingControl;
}

@property (strong, nonatomic) UIVisualEffectView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property (copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property (strong, nonatomic) NSMutableArray *constraints; // @synthesize constraints=_constraints;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) BOOL disableSubmit; // @synthesize disableSubmit=_disableSubmit;
@property (readonly) unsigned long long hash;
@property (strong, nonatomic) SKUIReviewInAppRatingHeaderView *headerView; // @synthesize headerView=_headerView;
@property (strong, nonatomic) SKUIStarRatingControl *ratingControl; // @synthesize ratingControl=_ratingControl;
@property (strong, nonatomic) UIInterfaceAction *ratingControlAction; // @synthesize ratingControlAction=_ratingControlAction;
@property (copy, nonatomic) CDUnknownBlockType ratingHandler; // @synthesize ratingHandler=_ratingHandler;
@property (strong, nonatomic) UIStackView *stackView; // @synthesize stackView=_stackView;
@property (nonatomic) unsigned long long state; // @synthesize state=_state;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_actions;
- (id)_actionsLayoutAxesForCurrentState;
- (id)_buttonActionWithTitle:(id)arg1 style:(unsigned long long)arg2;
- (void)_ratingControlChanged:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (id)initWithTitle:(id)arg1 message:(id)arg2 icon:(id)arg3;
- (void)interfaceAction:(id)arg1 invokeActionHandler:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (id)presentationControllerForPresentedViewController:(id)arg1 presentingViewController:(id)arg2 sourceViewController:(id)arg3;
- (void)reloadViewsConfiguration;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;

@end

