//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoverSheet/NSObject-Protocol.h>

@class CSAccessory;

@protocol CSAccessoryStatusDelegate <NSObject>
- (void)accessoryAnimationStatusChanged:(BOOL)arg1;
- (void)accessoryAttached:(CSAccessory *)arg1;
- (void)accessoryDetached:(CSAccessory *)arg1;
@end

