//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class NSArray, NSURL, SLVideoQualityOption;
@protocol SLFacebookVideoOptionsDelegate;

__attribute__((visibility("hidden")))
@interface SLFacebookVideoOptionsViewController : UITableViewController
{
    NSArray *_qualityOptions;
    NSURL *_videoAssetURL;
    SLVideoQualityOption *_selectedOption;
    id<SLFacebookVideoOptionsDelegate> _delegate;
}

@property (weak, nonatomic) id<SLFacebookVideoOptionsDelegate> delegate; // @synthesize delegate=_delegate;

- (void).cxx_destruct;
- (void)_generateQualityOptionsWithAssetURL:(id)arg1;
- (void)didReceiveMemoryWarning;
- (id)initWithVideoAssetURL:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setSelectedQualityOption:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)viewDidLoad;

@end

