//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ITMLKit/IKViewElement.h>

@interface IKViewElement (VSAdditions)
- (BOOL)vs_boolAttributeValueForKey:(id)arg1;
- (unsigned long long)vs_elementType;
- (id)vs_itemElementsOfType:(unsigned long long)arg1;
- (unsigned long long)vs_selectedChildElementIndex;
@end

