//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CallFingerprint : NSObject
{
}

+ (BOOL)doesCallTypesMatch:(id)arg1:(id)arg2;
+ (BOOL)match:(id)arg1:(id)arg2;
+ (id)matchCallWithFingerprint:(id)arg1 withDatabase:(id)arg2;

@end

