//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CallHistory/CHSynchronizedLoggable.h>

@class NSArray, NSDate, NSNumber, NSPredicate, NSString;
@protocol SyncManagerProtocol;

@interface CHManager : CHSynchronizedLoggable
{
    BOOL _showsFaceTimeVideoCalls;
    BOOL _showsFaceTimeAudioCalls;
    BOOL _showsTelephonyCalls;
    BOOL _generateSyncTransactions;
    BOOL _cacheIsDirty;
    BOOL _reCoalesce;
    unsigned int _limitingCallTypes;
    NSArray *_recentCalls;
    NSDate *_limitingStartDate;
    NSDate *_limitingEndDate;
    NSPredicate *_postFetchingPredicate;
    NSString *_coalescingStrategy;
    long long _numberOfUnseenMissedCalls;
    id<SyncManagerProtocol> _syncManager;
    NSArray *_uncoalescedRecentCalls;
    NSArray *_uncoalescedUnFilteredRecentCalls;
    NSNumber *_unreadCallCount;
    id _databaseChangedNotificationRef;
    id _addressBookChangedNotificationRef;
}

@property (strong) id addressBookChangedNotificationRef; // @synthesize addressBookChangedNotificationRef=_addressBookChangedNotificationRef;
@property BOOL cacheIsDirty; // @synthesize cacheIsDirty=_cacheIsDirty;
@property (copy, nonatomic) NSString *coalescingStrategy; // @synthesize coalescingStrategy=_coalescingStrategy;
@property (strong) id databaseChangedNotificationRef; // @synthesize databaseChangedNotificationRef=_databaseChangedNotificationRef;
@property BOOL generateSyncTransactions; // @synthesize generateSyncTransactions=_generateSyncTransactions;
@property (nonatomic) unsigned int limitingCallTypes; // @synthesize limitingCallTypes=_limitingCallTypes;
@property (copy, nonatomic) NSDate *limitingEndDate; // @synthesize limitingEndDate=_limitingEndDate;
@property (copy, nonatomic) NSDate *limitingStartDate; // @synthesize limitingStartDate=_limitingStartDate;
@property long long numberOfUnseenMissedCalls; // @synthesize numberOfUnseenMissedCalls=_numberOfUnseenMissedCalls;
@property (copy, nonatomic) NSPredicate *postFetchingPredicate; // @synthesize postFetchingPredicate=_postFetchingPredicate;
@property BOOL reCoalesce; // @synthesize reCoalesce=_reCoalesce;
@property (strong, nonatomic) NSArray *recentCalls; // @synthesize recentCalls=_recentCalls;
@property (nonatomic) BOOL showsFaceTimeAudioCalls; // @synthesize showsFaceTimeAudioCalls=_showsFaceTimeAudioCalls;
@property (nonatomic) BOOL showsFaceTimeVideoCalls; // @synthesize showsFaceTimeVideoCalls=_showsFaceTimeVideoCalls;
@property (nonatomic) BOOL showsTelephonyCalls; // @synthesize showsTelephonyCalls=_showsTelephonyCalls;
@property (strong) id<SyncManagerProtocol> syncManager; // @synthesize syncManager=_syncManager;
@property (strong, nonatomic, getter=uncoalescedRecentCallsSync) NSArray *uncoalescedRecentCalls; // @synthesize uncoalescedRecentCalls=_uncoalescedRecentCalls;
@property (strong) NSArray *uncoalescedUnFilteredRecentCalls; // @synthesize uncoalescedUnFilteredRecentCalls=_uncoalescedUnFilteredRecentCalls;
@property (strong) NSNumber *unreadCallCount; // @synthesize unreadCallCount=_unreadCallCount;

+ (unsigned int)CHCallStatusForCallWithDuration:(double)arg1 isOriginated:(BOOL)arg2 isAnswered:(BOOL)arg3;
- (void).cxx_destruct;
- (void)addMultipleCallsToCallHistory:(id)arg1;
- (void)addToCallHistory:(id)arg1;
- (void)addressBookChanged:(id)arg1;
- (id)applyPredicate:(id)arg1 toCalls:(id)arg2;
- (double)callTimersGetIncoming;
- (double)callTimersGetLifetime;
- (double)callTimersGetOutgoing;
- (void)callTimersReset;
- (id)coalesceCalls:(id)arg1;
- (unsigned long long)countCallsWithPredicate:(id)arg1;
- (unsigned long long)countCallsWithPredicateSync:(id)arg1;
- (void)databaseChanged:(id)arg1;
- (void)dealloc;
- (void)deleteAllCalls;
- (void)deleteAllCallsSync;
- (void)deleteCall:(id)arg1;
- (void)deleteCallAtIndex:(unsigned long long)arg1;
- (void)deleteCallsWithPredicate:(id)arg1;
- (void)deleteTheseCalls:(id)arg1;
- (void)deleteTheseCallsSync:(id)arg1;
- (id)fetchRecentCallsSyncWithCoalescing:(BOOL)arg1;
- (unsigned long long)fetchUnreadCallsCount;
- (void)flush;
- (id)init;
- (id)initWithFetchingLimitsDictionary:(id)arg1 andCoalescingStrategy:(id)arg2 andPostFetchingPredicate:(id)arg3 withQueue:(id)arg4;
- (void)markAllCallsAsReadWithPredicate:(id)arg1;
- (id)recentCallsWithPredicate:(id)arg1;
- (void)registerForNotifications;
- (void)setDefaultInitValues;
- (void)setLimitingCallTypesSync:(unsigned int)arg1;
- (id)unCoalesceCall:(id)arg1;
- (void)unRegisterForNotifications;
- (void)updateBytesOfDataUsedFor:(id)arg1 with:(id)arg2;

@end

