//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface AFRemoteRequestWatcher : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    int _token;
    CDUnknownBlockType _handler;
}

- (void).cxx_destruct;
- (void)_setupListener;
- (void)dealloc;
- (id)init;
- (void)setNewRequestHandler:(CDUnknownBlockType)arg1;

@end

