//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <NanoTimeKitCompanion/NTKColoringView.h>

#import <NanoTimeKitCompanion/NTKKeylineView-Protocol.h>

@class NSString, UIBezierPath, UIColor;

@interface _NTKKeylinePathView : NTKColoringView <NTKKeylineView>
{
    UIBezierPath *_path;
}

@property (strong, nonatomic) UIColor *color;
@property (readonly, nonatomic) UIColor *contentColor;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (strong, nonatomic) UIColor *overrideColor;
@property (readonly) Class superclass;
@property (nonatomic) BOOL usesLegibility;

- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithPath:(id)arg1;

@end

