//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <NanoTimeKitCompanion/NTKSpriteKitAnalogFaceView.h>

@class NTKZeusAnalogScene, NTKZeusColorPalette, UIView;

@interface NTKZeusAnalogFaceView : NTKSpriteKitAnalogFaceView
{
    BOOL _isEditing;
    BOOL _isHandsVisibleInColorEditing;
    BOOL _isStatusBarIconShadowNeeded;
    NTKZeusColorPalette *_palette;
    UIView *_cornerView;
    struct CGRect _upperComplicationOverrideFrame;
    struct CGRect _lowerComplicationOverrideFrame;
}

@property (readonly, nonatomic) NTKZeusAnalogScene *analogScene; // @dynamic analogScene;

+ (id)_supportedComplicationSlots;
+ (id)_swatchColorForColorOption:(id)arg1 forDevice:(id)arg2;
+ (id)_swatchForEditModeDependsOnOptions:(long long)arg1 forDevice:(id)arg2;
+ (id)_swatchImageForColorOption:(id)arg1 forDevice:(id)arg2;
- (void).cxx_destruct;
- (void)_applyBreathingFraction:(double)arg1 forCustomEditMode:(long long)arg2 slot:(id)arg3;
- (void)_applyOption:(id)arg1 forCustomEditMode:(long long)arg2 slot:(id)arg3;
- (void)_applyRubberBandingFraction:(double)arg1 forCustomEditMode:(long long)arg2 slot:(id)arg3;
- (void)_applyTransitionFraction:(double)arg1 fromOption:(id)arg2 toOption:(id)arg3 forCustomEditMode:(long long)arg4 slot:(id)arg5;
- (double)_backgroundAlphaForEditMode:(long long)arg1;
- (long long)_complicationPickerStyleForSlot:(id)arg1;
- (void)_configureForEditMode:(long long)arg1;
- (void)_configureForTransitionFraction:(double)arg1 fromEditMode:(long long)arg2 toEditMode:(long long)arg3;
- (void)_configureReusableTimeView:(id)arg1;
- (BOOL)_fadesComplicationSlot:(id)arg1 inEditMode:(long long)arg2;
- (struct CGRect)_frameForComplicationDisplayWrapper:(id)arg1 inSlot:(id)arg2;
- (double)_handAlphaForEditing:(BOOL)arg1;
- (unsigned long long)_keylineLabelAlignmentForCustomEditMode:(long long)arg1 slot:(id)arg2;
- (BOOL)_keylineLabelShouldShowIndividualOptionNamesForCustomEditMode:(long long)arg1;
- (id)_keylineViewForCustomEditMode:(long long)arg1 slot:(id)arg2;
- (void)_loadLayoutRules;
- (void)_loadScene;
- (void)_loadSnapshotContentViews;
- (struct CGRect)_lowerComplicationFrameForStyle:(unsigned long long)arg1;
- (id)_newLegacyViewForComplication:(id)arg1 family:(long long)arg2 slot:(id)arg3;
- (double)_numbersAlphaForEditMode:(long long)arg1;
- (void)_prepareForStatusChange:(BOOL)arg1;
- (void)_prepareTimeViewForReuse:(id)arg1;
- (struct CGSize)_sceneSize;
- (double)_secondHandAlphaForDensity:(unsigned long long)arg1 isEditing:(BOOL)arg2;
- (void)_setStatusBarIconShadowNeeded:(BOOL)arg1;
- (id)_swatchImageForEditOption:(id)arg1 mode:(long long)arg2 withSelectedOptions:(id)arg3;
- (struct CGPoint)_timeTravelStatusModuleCenter;
- (BOOL)_timeViewBehindContentForEditMode:(long long)arg1;
- (void)_unloadSnapshotContentViews;
- (void)_updateDateComplicationPositionIfNecessary;
- (struct CGRect)_upperComplicationFrameForStyle:(unsigned long long)arg1;
- (double)_verticalPaddingForStatusBar;
- (BOOL)_wantsStatusBarIconShadow;
- (id)initWithFaceStyle:(long long)arg1 forDevice:(id)arg2 clientIdentifier:(id)arg3;
- (void)setOverrideDate:(id)arg1 duration:(double)arg2;

@end

