//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC8NewsFeed20DebugFormatRulerView : UIView
{
    MISSING_TYPE *scale;
    MISSING_TYPE *contentSize;
    MISSING_TYPE *contentBounds;
    MISSING_TYPE *canvasOffset;
    MISSING_TYPE *selectionFrame;
    MISSING_TYPE *rulersHidden;
    MISSING_TYPE *rulerSize;
    MISSING_TYPE *verticalRulerEdgeView;
    MISSING_TYPE *horizontalRulerEdgeView;
    MISSING_TYPE *gridView;
    MISSING_TYPE *cornerView;
    MISSING_TYPE *borderLayer;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)traitCollectionDidChange:(id)arg1;

@end

