//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NAImages : NSObject
{
}

+ (id)copyLinkActivity;
+ (id)delete;
+ (id)downloadIssueActivity;
+ (id)iconArticleMarkingShare;
+ (id)iconTextSizeControl;
+ (id)iconTextSizeControlCompact;
+ (id)ignoreSuggestionActivity;
+ (id)leftArrow;
+ (id)openChannelActivity;
+ (id)openInSafariActivity;
+ (id)play;
+ (id)playLast;
+ (id)playNext;
+ (id)playing;
+ (id)readStory;
+ (id)removeIssueActivity;
+ (id)removeIssueFromMyMagazinesActivity;
+ (id)reportActivity;
+ (id)rightArrow;
+ (id)sharrow;
+ (id)sharrowCompact;
- (void).cxx_destruct;
- (id)init;

@end

