//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <MobileCoreServices/LSOpenResourceOperationDelegate-Protocol.h>

@class NSOperation, NSString;
@protocol LSOpenResourceOperationDelegate;

__attribute__((visibility("hidden")))
@interface _LSOpenResourceOperationDelegateWrapper : NSObject <LSOpenResourceOperationDelegate>
{
    NSOperation *_operation;
    id<LSOpenResourceOperationDelegate> _delegate;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void)dealloc;
- (id)initWithOperation:(id)arg1 wrappedDelegate:(id)arg2;
- (void)openResourceOperation:(id)arg1 didFailWithError:(id)arg2;
- (void)openResourceOperation:(id)arg1 didFinishCopyingResource:(id)arg2;
- (void)openResourceOperationDidComplete:(id)arg1;

@end

