//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CATTaskRequest.h"

@class CRKCourseInvitation;

@interface CRKJoinControlGroupRequest : CATTaskRequest
{
    CRKCourseInvitation *_invitation;
}

@property (strong, nonatomic) CRKCourseInvitation *invitation; // @synthesize invitation=_invitation;

+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

