//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Intents/NSObject-Protocol.h>

@class NSArray, _INPBCondition, _INPBInteger;

@protocol _INPBIntegerList <NSObject>

@property (strong, nonatomic) _INPBCondition *conditionType;
@property (copy, nonatomic) NSArray *dataStrings;
@property (readonly, nonatomic) unsigned long long dataStringsCount;
@property (readonly, nonatomic) BOOL hasConditionType;

+ (Class)dataStringType;
- (void)addDataString:(_INPBInteger *)arg1;
- (void)clearDataStrings;
- (_INPBInteger *)dataStringAtIndex:(unsigned long long)arg1;
@end

