//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <Intents/NSCopying-Protocol.h>

@class NSData, NSString, PBUnknownFields;

@interface _INPBIntentResponsePayloadSuccess : PBCodable <NSCopying>
{
    PBUnknownFields *_unknownFields;
    NSData *_responseMessageData;
    NSString *_responseTypeName;
    BOOL _shouldOpenContainingApplication;
    struct {
        unsigned int shouldOpenContainingApplication:1;
    } _has;
}

@property (readonly, nonatomic) BOOL hasResponseMessageData;
@property (readonly, nonatomic) BOOL hasResponseTypeName;
@property (nonatomic) BOOL hasShouldOpenContainingApplication;
@property (strong, nonatomic) NSData *responseMessageData; // @synthesize responseMessageData=_responseMessageData;
@property (strong, nonatomic) NSString *responseTypeName; // @synthesize responseTypeName=_responseTypeName;
@property (nonatomic) BOOL shouldOpenContainingApplication; // @synthesize shouldOpenContainingApplication=_shouldOpenContainingApplication;
@property (readonly, nonatomic) PBUnknownFields *unknownFields;

+ (id)options;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;

@end

