//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Intents/NSObject-Protocol.h>

@class NSData, NSString;

@protocol _INPBFileDataAttachment <NSObject>

@property (copy, nonatomic) NSData *data;
@property (copy, nonatomic) NSString *fileName;
@property (readonly, nonatomic) BOOL hasData;
@property (readonly, nonatomic) BOOL hasFileName;

@end

