//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, XCUIApplication;

@interface XCUISiriService : NSObject
{
    XCUIApplication *_siriApplication;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, getter=isEnabled) BOOL enabled;
@property (strong) XCUIApplication *siriApplication; // @synthesize siriApplication=_siriApplication;

+ (id)siriService;
- (void).cxx_destruct;
- (void)_assertSiriEnabled;
- (void)_waitForActivation;
- (void)activateWithVoiceRecognitionText:(id)arg1;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (id)init;
- (void)injectAssistantRecognitionStrings:(id)arg1;
- (void)injectVoiceRecognitionAudioInputPaths:(id)arg1;

@end

