//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <coreroutine/RTDataProviderDuet.h>

#import <coreroutine/RTDataProviderProtocol-Protocol.h>

@class NSArray, NSDate, NSString, RTDefaultsManager;

@interface RTDataProviderNowPlaying : RTDataProviderDuet <RTDataProviderProtocol>
{
    BOOL _ready;
    unsigned int _lastNowPlayingState;
    NSDate *_dateOfLastNowPlayingTransition;
    NSString *_lastNowPlayingBundleId;
    double _minimumNowPlayingDurationTimeInterval;
    RTDefaultsManager *_defaultsManager;
    NSArray *_blacklistedBundleIds;
}

@property (strong, nonatomic) NSArray *blacklistedBundleIds; // @synthesize blacklistedBundleIds=_blacklistedBundleIds;
@property (strong, nonatomic) NSDate *dateOfLastNowPlayingTransition; // @synthesize dateOfLastNowPlayingTransition=_dateOfLastNowPlayingTransition;
@property (readonly, copy) NSString *debugDescription;
@property (strong, nonatomic) RTDefaultsManager *defaultsManager; // @synthesize defaultsManager=_defaultsManager;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (strong, nonatomic) NSString *lastNowPlayingBundleId; // @synthesize lastNowPlayingBundleId=_lastNowPlayingBundleId;
@property (nonatomic) unsigned int lastNowPlayingState; // @synthesize lastNowPlayingState=_lastNowPlayingState;
@property (nonatomic) double minimumNowPlayingDurationTimeInterval; // @synthesize minimumNowPlayingDurationTimeInterval=_minimumNowPlayingDurationTimeInterval;
@property (nonatomic) BOOL ready; // @synthesize ready=_ready;
@property (readonly) Class superclass;

+ (id)providerName;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_handleNowPlayingApplicationIsPlayingDidChange;
- (void)_registerForMediaRemoteNotifications;
- (void)_registerForNotifications;
- (void)_setup;
- (void)_unregisterForMediaRemoteNotifications;
- (void)_unregisterForNotifications;
- (void)_updateMinimumNowPlayingDurationWithHandler:(CDUnknownBlockType)arg1;
- (void)fetchBundleIdsSupportingNowPlayingCapability:(CDUnknownBlockType)arg1;
- (void)fetchMediaRemoteNowPlayingApplicationBundleId:(CDUnknownBlockType)arg1;
- (void)fetchMediaRemoteNowPlayingApplicationPlaybackState:(CDUnknownBlockType)arg1;
- (void)handleNowPlayingApplicationIsPlayingDidChange;
- (id)init;
- (id)initWithDefaultsManager:(id)arg1;
- (void)internalAddObserver:(id)arg1 name:(id)arg2;
- (void)internalRemoveObserver:(id)arg1 name:(id)arg2;
- (void)onDefaultsUpdate:(id)arg1;
- (void)populateDataProviderWithHandler:(CDUnknownBlockType)arg1;
- (void)shutdown;
- (id)supportedEventClasses;
- (void)updateBundlesSupportingMediaRemotePopulationWithHandler:(CDUnknownBlockType)arg1;

@end

