//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface RTLaunchServices : NSObject
{
}

+ (BOOL)canOpenApplication:(id)arg1;
+ (id)createProcessAssertionForPid:(int)arg1;
+ (void)launchClientWithBundleIdentifier:(id)arg1 restorationIdentifier:(id)arg2 eventAgentManager:(id)arg3 handler:(CDUnknownBlockType)arg4;

@end

