//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <coreroutine/RTCloudManagedObject.h>

@class NSDate, NSNumber, RTLearnedVisitMO;

@interface RTLearnedTransitionMO : RTCloudManagedObject
{
}

@property (strong, nonatomic) RTLearnedVisitMO *destination; // @dynamic destination;
@property (strong, nonatomic) RTLearnedVisitMO *origin; // @dynamic origin;
@property (copy, nonatomic) NSNumber *predominantMotionActivityType; // @dynamic predominantMotionActivityType;
@property (copy, nonatomic) NSDate *startDate; // @dynamic startDate;
@property (copy, nonatomic) NSDate *stopDate; // @dynamic stopDate;

+ (id)fetchRequest;
+ (id)managedObjectWithTransition:(id)arg1 inManagedObjectContext:(id)arg2;
+ (id)managedObjectWithTransition:(id)arg1 managedObject:(id)arg2 inManagedObjectContext:(id)arg3;

@end

