//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <coreroutine/RTVisitModelController-Protocol.h>

@class NSString, RTVisitHyperParameter, RTVisitTrajectorySequenceClassifierBatchMode;

@interface RTVisitModelControllerBatchMode : NSObject <RTVisitModelController>
{
    void *_espressoContext;
    void *_espressoPlan;
    CDStruct_0a65202a _inputBuffer;
    CDStruct_0a65202a _outputBuffer;
    RTVisitHyperParameter *_hyperParameter;
    RTVisitTrajectorySequenceClassifierBatchMode *_model;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly, nonatomic) RTVisitTrajectorySequenceClassifierBatchMode *model; // @synthesize model=_model;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (const float *)batchProcess:(const float *)arg1 featureVectorStride:(unsigned long long)arg2 firstSequenceIndex:(unsigned long long)arg3 firstSequenceLength:(unsigned long long)arg4 batchSize:(unsigned long long)arg5;
- (void)dealloc;
- (id)init;
- (id)initWithHyperParameter:(id)arg1;
- (const float *)predictFromInput:(const float *)arg1 featureVectorStride:(unsigned long long)arg2 firstSequenceIndex:(unsigned long long)arg3 firstSequenceLength:(unsigned long long)arg4 batchSize:(unsigned long long)arg5;

@end

