//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PassKitUI/PKDiscoveryShelfView.h>

@class PKContinuousButton, PKDiscoveryCallToAction, PKDiscoveryCallToActionShelf, PKDiscoveryMedia, UIImageView, UILabel;
@protocol PKDiscoveryCardViewDelegate;

@interface PKDiscoveryCallToActionShelfView : PKDiscoveryShelfView
{
    PKDiscoveryCallToActionShelf *_ctaShelf;
    PKDiscoveryCallToAction *_callToAction;
    PKDiscoveryMedia *_media;
    UILabel *_titleLabel;
    UILabel *_editorialDescriptionLabel;
    UIImageView *_iconImageView;
    PKContinuousButton *_button;
    struct CGSize _iconSize;
    BOOL _showActivityIndicator;
    id<PKDiscoveryCardViewDelegate> _delegate;
}

@property (weak, nonatomic) id<PKDiscoveryCardViewDelegate> delegate; // @synthesize delegate=_delegate;
@property (nonatomic) BOOL showActivityIndicator; // @synthesize showActivityIndicator=_showActivityIndicator;

- (void).cxx_destruct;
- (void)_buttonPressed:(id)arg1;
- (struct CGSize)_iconSize;
- (double)_leadingEditorialTextSpace;
- (double)_leadingTitleSpace;
- (struct CGSize)_sizeForMedia;
- (id)initWithShelf:(id)arg1;
- (void)layoutSubviews;
- (void)setImage:(id)arg1 animated:(BOOL)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

