//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewLayout.h>

@class NSMutableDictionary;

@interface PKDiscoveryLayout : UICollectionViewLayout
{
    NSMutableDictionary *_attributesPerIndexPath;
    NSMutableDictionary *_headersPerIndexPath;
    struct CGSize _currentSize;
    double _interimSpacing;
    double _lineSpacing;
}

@property (nonatomic) double interimSpacing; // @synthesize interimSpacing=_interimSpacing;
@property (nonatomic) double lineSpacing; // @synthesize lineSpacing=_lineSpacing;

- (void).cxx_destruct;
- (void)_adjustItems:(id)arg1 withLateralMove:(double)arg2;
- (struct CGSize)collectionViewContentSize;
- (id)init;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (void)prepareLayout;

@end

