//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PassKitUI/NSObject-Protocol.h>

@class PKPassFooterView;

@protocol PKPassFooterViewDelegate <NSObject>
- (void)passFooterViewDidChangeUserIntentRequirement:(PKPassFooterView *)arg1;
@end

