//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface PKPickerSection : NSObject
{
    NSString *_title;
    NSString *_footer;
    NSMutableArray *_items;
}

@property (copy, nonatomic) NSString *footer; // @synthesize footer=_footer;
@property (readonly, copy, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property (copy, nonatomic) NSString *title; // @synthesize title=_title;

+ (id)sectionWithTitle:(id)arg1;
+ (id)sectionWithTitle:(id)arg1 footer:(id)arg2;
- (void).cxx_destruct;

@end

