//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FamilyCircle/FAFamilyCircleRequest.h>

@class NSNumber, NSString;

@interface FAFetchFamilyPhotoRequest : FAFamilyCircleRequest
{
    BOOL _localFallback;
    BOOL _useMonogramAsLastResort;
    NSNumber *_memberDSID;
    NSString *_memberHashedDSID;
    unsigned long long _requestedSize;
    double _requiredWidth;
    double _requiredHeight;
    double _monogramDiameter;
    long long _backgroundType;
    NSString *_fullname;
    NSString *_emailAddress;
    NSString *_phoneNumber;
}

@property long long backgroundType; // @synthesize backgroundType=_backgroundType;
@property (copy) NSString *emailAddress; // @synthesize emailAddress=_emailAddress;
@property (copy) NSString *fullname; // @synthesize fullname=_fullname;
@property (readonly) BOOL localFallback; // @synthesize localFallback=_localFallback;
@property (readonly, copy) NSNumber *memberDSID; // @synthesize memberDSID=_memberDSID;
@property (readonly, copy) NSString *memberHashedDSID; // @synthesize memberHashedDSID=_memberHashedDSID;
@property double monogramDiameter; // @synthesize monogramDiameter=_monogramDiameter;
@property (copy) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property (readonly) unsigned long long requestedSize; // @synthesize requestedSize=_requestedSize;
@property double requiredHeight; // @synthesize requiredHeight=_requiredHeight;
@property double requiredWidth; // @synthesize requiredWidth=_requiredWidth;
@property BOOL useMonogramAsLastResort; // @synthesize useMonogramAsLastResort=_useMonogramAsLastResort;

- (void).cxx_destruct;
- (id)init;
- (id)initWithConnectionProvider:(id)arg1;
- (id)initWithFamilyMemberDSID:(id)arg1 size:(unsigned long long)arg2 localFallback:(BOOL)arg3;
- (id)initWithFamilyMemberDSID:(id)arg1 size:(unsigned long long)arg2 localFallback:(BOOL)arg3 connectionProvider:(id)arg4;
- (id)initWithFamilyMemberHashedDSID:(id)arg1 size:(unsigned long long)arg2 localFallback:(BOOL)arg3;
- (id)initWithFamilyMemberHashedDSID:(id)arg1 size:(unsigned long long)arg2 localFallback:(BOOL)arg3 connectionProvider:(id)arg4;
- (id)requestOptions;
- (void)startRequestWithCompletionHandler:(CDUnknownBlockType)arg1;

@end

