//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <NewsCore/NSCoding-Protocol.h>

@interface FCCommand : NSObject <NSCoding>
{
}

- (BOOL)canCoalesceWithCommand:(id)arg1;
- (void)coalesceWithCommand:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)executeWithContext:(id)arg1 delegate:(id)arg2;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (unsigned long long)statusForCloudKitError:(id)arg1;

@end

