//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FCFDBFeed;

@interface FCFeedInsertionToken : NSObject
{
    FCFDBFeed *_fromFeed;
    unsigned long long _fromOrder;
    unsigned long long _toOrder;
}

@property (strong, nonatomic) FCFDBFeed *fromFeed; // @synthesize fromFeed=_fromFeed;
@property (nonatomic) unsigned long long fromOrder; // @synthesize fromOrder=_fromOrder;
@property (nonatomic) unsigned long long toOrder; // @synthesize toOrder=_toOrder;

- (void).cxx_destruct;

@end

