//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface FCMultiStepFetchOperationStep : NSObject
{
    BOOL _isCritical;
    SEL _fetchSelector;
}

@property (nonatomic) SEL fetchSelector; // @synthesize fetchSelector=_fetchSelector;
@property (nonatomic) BOOL isCritical; // @synthesize isCritical=_isCritical;


@end

