//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CameraKit/CMKBadgeTextView.h>

@class NSString;

@interface CMKExposureBiasTextView : CMKBadgeTextView
{
    float _exposureBias;
    NSString *__lastText;
}

@property (strong, nonatomic) NSString *_lastText; // @synthesize _lastText=__lastText;
@property (nonatomic) float exposureBias; // @synthesize exposureBias=_exposureBias;

- (void).cxx_destruct;
- (id)_text;
- (id)_textAttributes;
- (id)_textForExposureBias:(float)arg1;
- (double)_textHorizontalInset;
- (double)_textHorizontalKerningOffset;
- (struct CGSize)_textSize;
- (double)_textVerticalInset;

@end

