//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AddressBook/NSObject-Protocol.h>

@class ABSAddressBook, ABSSource, NSString;
@protocol ABSCNImplementation;

@protocol ABSRecord <NSObject>

@property (readonly, nonatomic) NSString *CNIdentifierString;
@property (weak, nonatomic) ABSAddressBook *addressBook;
@property (strong, nonatomic) id<ABSCNImplementation> cnImpl;
@property (readonly, nonatomic) NSString *compositeName;
@property (readonly, nonatomic) int id;
@property (weak, nonatomic) ABSSource *source;
@property (readonly, nonatomic) unsigned int type;

- (const void *)copyValueForProperty:(int)arg1;
- (BOOL)removeProperty:(int)arg1 withError:(id *)arg2;
- (void)replaceRecordStorageWithCNObject:(id<ABSCNImplementation>)arg1;
- (BOOL)setValue:(const void *)arg1 forProperty:(int)arg2 withError:(struct __CFError **)arg3;
@end

