//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIPanGestureRecognizer.h>

@interface _AXTodayPanGestureRecognizer : UIPanGestureRecognizer
{
    BOOL _show;
    long long _overriddenState;
}

@property (nonatomic) long long overriddenState; // @synthesize overriddenState=_overriddenState;
@property (nonatomic) BOOL show; // @synthesize show=_show;

- (long long)state;
- (struct CGPoint)translationInView:(id)arg1;
- (struct CGPoint)velocityInView:(id)arg1;

@end

