//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVMLKit/_TVFocusRedirectView.h>

#import <TVMLKit/TVAppTemplateImpressionable-Protocol.h>

@class NSArray, NSString, UIView;

__attribute__((visibility("hidden")))
@interface _TVInfoTableView : _TVFocusRedirectView <TVAppTemplateImpressionable>
{
    UIView *_headerView;
    NSArray *_infoViews;
    UIView *_footerView;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (strong, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property (readonly) unsigned long long hash;
@property (strong, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property (strong, nonatomic) NSArray *infoViews; // @synthesize infoViews=_infoViews;
@property (readonly) Class superclass;

+ (id)infoTableViewWithElement:(id)arg1 existingView:(id)arg2;
- (void).cxx_destruct;
- (double)_normalizedInfoHeaderWidth;
- (id)impressionableElementsContainedInDocument:(id)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

