//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVMLKit/_TVFocusRedirectView.h>

#import <TVMLKit/TVAppTemplateImpressionable-Protocol.h>

@class IKViewElement, NSArray, NSString, UIView;

__attribute__((visibility("hidden")))
@interface _TVProductStackView : _TVFocusRedirectView <TVAppTemplateImpressionable>
{
    UIView *_lastFocusedView;
    UIView *_titleView;
    NSArray *_viewsAboveDescription;
    UIView *_descriptionView;
    NSArray *_viewsBelowDescription;
    UIView *_buttonsRowView;
    UIView *_initialFocusView;
    IKViewElement *_stackElement;
}

@property (strong, nonatomic) UIView *buttonsRowView; // @synthesize buttonsRowView=_buttonsRowView;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (strong, nonatomic) UIView *descriptionView; // @synthesize descriptionView=_descriptionView;
@property (readonly) unsigned long long hash;
@property (strong, nonatomic) UIView *initialFocusView; // @synthesize initialFocusView=_initialFocusView;
@property (strong, nonatomic) IKViewElement *stackElement; // @synthesize stackElement=_stackElement;
@property (readonly) Class superclass;
@property (strong, nonatomic) UIView *titleView; // @synthesize titleView=_titleView;
@property (strong, nonatomic) NSArray *viewsAboveDescription; // @synthesize viewsAboveDescription=_viewsAboveDescription;
@property (strong, nonatomic) NSArray *viewsBelowDescription; // @synthesize viewsBelowDescription=_viewsBelowDescription;

+ (id)productStackViewWithElement:(id)arg1 existingView:(id)arg2;
- (void).cxx_destruct;
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;
- (id)impressionableElementsContainedInDocument:(id)arg1;
- (void)layoutSubviews;
- (id)preferredFocusEnvironments;

@end

