//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Home/HFAnalyticsEvent.h>

@class NSString;

@interface HFAnalyticsTileInteractionEvent : HFAnalyticsEvent
{
    BOOL _isRoomDashboard;
    BOOL _isActionSetItem;
    BOOL _isCameraItem;
    BOOL _isServiceLikeItem;
    BOOL _isStatusItem;
    unsigned long long _interactionType;
    NSString *_itemClassName;
    long long _itemPrimaryState;
    long long _itemPriority;
    unsigned long long _numberOfRepresentedHomeKitObjects;
    NSString *_processName;
    NSString *_sourceViewControllerClassName;
}

@property (nonatomic) unsigned long long interactionType; // @synthesize interactionType=_interactionType;
@property (nonatomic) BOOL isActionSetItem; // @synthesize isActionSetItem=_isActionSetItem;
@property (nonatomic) BOOL isCameraItem; // @synthesize isCameraItem=_isCameraItem;
@property (nonatomic) BOOL isRoomDashboard; // @synthesize isRoomDashboard=_isRoomDashboard;
@property (nonatomic) BOOL isServiceLikeItem; // @synthesize isServiceLikeItem=_isServiceLikeItem;
@property (nonatomic) BOOL isStatusItem; // @synthesize isStatusItem=_isStatusItem;
@property (strong, nonatomic) NSString *itemClassName; // @synthesize itemClassName=_itemClassName;
@property (nonatomic) long long itemPrimaryState; // @synthesize itemPrimaryState=_itemPrimaryState;
@property (nonatomic) long long itemPriority; // @synthesize itemPriority=_itemPriority;
@property (nonatomic) unsigned long long numberOfRepresentedHomeKitObjects; // @synthesize numberOfRepresentedHomeKitObjects=_numberOfRepresentedHomeKitObjects;
@property (strong, nonatomic) NSString *processName; // @synthesize processName=_processName;
@property (strong, nonatomic) NSString *sourceViewControllerClassName; // @synthesize sourceViewControllerClassName=_sourceViewControllerClassName;

+ (unsigned long long)_numberOfRepresentedHomeKitObjectsForItem:(id)arg1;
- (void).cxx_destruct;
- (id)initWithData:(id)arg1;
- (id)payload;

@end

