//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Home/HFCameraClipSignificantEventItem.h>

#import <Home/HFPersonLikeItem-Protocol.h>

@class HMFaceClassification, HMHome, HMPerson, HMPersonManager, NSString, UIImage;

@interface HFFaceClassificationSignificantEventItem : HFCameraClipSignificantEventItem <HFPersonLikeItem>
{
    UIImage *_faceCropImage;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, copy, nonatomic) HMFaceClassification *faceClassification;
@property (strong, nonatomic) UIImage *faceCropImage; // @synthesize faceCropImage=_faceCropImage;
@property (readonly) unsigned long long hash;
@property (readonly, nonatomic) HMHome *home;
@property (readonly, copy, nonatomic) HMPerson *person;
@property (readonly, nonatomic) HMPersonManager *personManager;
@property (readonly) Class superclass;

+ (id)dateFormatter;
- (void).cxx_destruct;
- (id)_subclass_updateWithOptions:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithSignificantEvent:(id)arg1 home:(id)arg2;

@end

