//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Home/HFEventBuilder.h>

#import <Home/HFLocationEventBuilder-Protocol.h>

@class CLCircularRegion, NSString;

@interface HFLocationRegionEventBuilder : HFEventBuilder <HFLocationEventBuilder>
{
    CLCircularRegion *_region;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, nonatomic) unsigned long long eventType;
@property (readonly) unsigned long long hash;
@property (copy, nonatomic) CLCircularRegion *region; // @synthesize region=_region;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)buildNewEventFromCurrentState;
- (id)initWithEvent:(id)arg1;
- (BOOL)isRegionAtHome:(id)arg1;

@end

