//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CAAnimation.h>

@class CALayer, NSString;

@interface CAMatchPropertyAnimation : CAAnimation
{
}

@property (getter=isAdditive) BOOL additive;
@property (copy) NSString *keyPath;
@property unsigned int sourceContextId;
@property (weak) CALayer *sourceLayer;
@property unsigned long long sourceLayerRenderId;

- (struct Animation *)_copyRenderAnimationForLayer:(id)arg1;
- (unsigned int)_propertyFlagsForLayer:(id)arg1;
- (BOOL)_setCARenderAnimation:(struct Animation *)arg1 layer:(id)arg2;
- (void)applyForTime:(double)arg1 presentationObject:(id)arg2 modelObject:(id)arg3;

@end

