//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class AVPlayer, PUScrubberSeekRequest;
@protocol PUVideoScrubberControllerDelegate;

__attribute__((visibility("hidden")))
@interface PUVideoScrubberController : NSObject
{
    id _playerObserver;
    BOOL _needsUpdate;
    BOOL _avPlayerCurrentTimeNeedsUpdate;
    BOOL _avPlayerDurationNeedsUpdate;
    struct {
        BOOL respondsToDidUpdate;
        BOOL respondsToLengthForDuration;
        BOOL respondsToDesiredSeekTime;
    } _videoScrubberDelegateFlags;
    id<PUVideoScrubberControllerDelegate> _delegate;
    AVPlayer *_avPlayer;
    double _estimatedDuration;
    double __playheadTime;
    PUScrubberSeekRequest *__pendingSeekRequest;
    PUScrubberSeekRequest *__activeSeekRequest;
    CDStruct_1b6d18a9 __avPlayerCurrentTime;
    CDStruct_1b6d18a9 __avPlayerDuration;
}

@property (strong, nonatomic, setter=_setActiveSeekRequest:) PUScrubberSeekRequest *_activeSeekRequest; // @synthesize _activeSeekRequest=__activeSeekRequest;
@property (nonatomic, setter=_setAvPlayerCurrentTime:) CDStruct_1b6d18a9 _avPlayerCurrentTime; // @synthesize _avPlayerCurrentTime=__avPlayerCurrentTime;
@property (nonatomic, setter=_setAvPlayerDuration:) CDStruct_1b6d18a9 _avPlayerDuration; // @synthesize _avPlayerDuration=__avPlayerDuration;
@property (strong, nonatomic, setter=_setPendingSeekRequest:) PUScrubberSeekRequest *_pendingSeekRequest; // @synthesize _pendingSeekRequest=__pendingSeekRequest;
@property (nonatomic, setter=_setPlayheadTime:) double _playheadTime; // @synthesize _playheadTime=__playheadTime;
@property (readonly, nonatomic) AVPlayer *avPlayer; // @synthesize avPlayer=_avPlayer;
@property (weak, nonatomic) id<PUVideoScrubberControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property (readonly, nonatomic) double estimatedDuration; // @synthesize estimatedDuration=_estimatedDuration;
@property (readonly, nonatomic) double length;
@property (nonatomic) double playheadProgress;

- (void).cxx_destruct;
- (void)_addObservers;
- (double)_duration;
- (void)_handleTimeoutCallbackForSeekRequest:(id)arg1;
- (void)_invalidate;
- (void)_invalidateAvPlayerCurrentTime;
- (void)_invalidateAvPlayerDuration;
- (double)_lengthForDuration:(double)arg1;
- (void)_loadedDurationDidChange;
- (void)_playerDidChange:(id)arg1;
- (void)_playerItemDurationDidChange;
- (void)_playerItemStatusDidChange;
- (void)_playerStatusDidChange;
- (double)_progressForTime:(double)arg1;
- (void)_removeObservers;
- (void)_seekRequest:(id)arg1 didFinish:(BOOL)arg2;
- (void)_seekToTime:(double)arg1;
- (void)_setPlayheadProgress:(double)arg1 andSeekVideoPlayer:(BOOL)arg2;
- (double)_timeForProgress:(double)arg1;
- (void)_updateAvPlayerCurrentTimeIfNeeded;
- (void)_updateAvPlayerDurationIfNeeded;
- (void)_updateIfNeeded;
- (void)_updateSeeking;
- (void)dealloc;
- (id)init;
- (id)initWithAvPlayer:(id)arg1 estimatedDuration:(double)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

@end

