//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PhotosUICore/PXObservable.h>

#import <PhotosUICore/PXChangeObserver-Protocol.h>

@class NSString, PXExtendedTraitCollection, PXFeatureSpec;

@interface PXFeatureSpecManager : PXObservable <PXChangeObserver>
{
    PXFeatureSpec *_spec;
    PXExtendedTraitCollection *_extendedTraitCollection;
    unsigned long long _options;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, nonatomic) PXExtendedTraitCollection *extendedTraitCollection; // @synthesize extendedTraitCollection=_extendedTraitCollection;
@property (readonly) unsigned long long hash;
@property (readonly, nonatomic) unsigned long long options; // @synthesize options=_options;
@property (readonly, nonatomic) PXFeatureSpec *spec; // @synthesize spec=_spec;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_setSpec:(id)arg1;
- (void)_updateSpec;
- (id)createSpec;
- (id)init;
- (id)initWithExtendedTraitCollection:(id)arg1;
- (id)initWithExtendedTraitCollection:(id)arg1 options:(unsigned long long)arg2;
- (id)mutableChangeObject;
- (void)observable:(id)arg1 didChange:(unsigned long long)arg2 context:(void *)arg3;
- (BOOL)shouldUpdateSpecForExtendedTraitCollectionChange:(unsigned long long)arg1;
- (Class)specClass;

@end

