//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PhotosUICore/NSObject-Protocol.h>

@class NSArray, PXGSpriteReference, PXMediaProvider;
@protocol PXDisplayAsset, PXGDisplayAssetPixelBufferSource;

@protocol PXGDisplayAssetPixelBufferSourcesProvider <NSObject>
- (id<PXGDisplayAssetPixelBufferSource>)pixelBufferSourceForDisplayAsset:(id<PXDisplayAsset>)arg1 mediaProvider:(PXMediaProvider *)arg2 spriteReference:(PXGSpriteReference *)arg3;
- (void)recyclePixelBufferSourceForDisplayAssets:(NSArray *)arg1;
@end

