//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PhotosUICore/PXViewSpec.h>

@class NSArray;

@interface PXImageViewSpec : PXViewSpec
{
    BOOL _shouldEnableFocus;
    NSArray *_overlaySpecs;
    long long _roundedCornersMode;
}

@property (readonly, nonatomic) struct CGPoint floatingContentMotionRotation;
@property (readonly, nonatomic) struct CGPoint floatingContentMotionTranslation;
@property (readonly, nonatomic) double floatingShadowOpacity;
@property (readonly, nonatomic) double floatingShadowRadius;
@property (readonly, nonatomic) struct CGSize floatingUnfocusedShadowExpansion;
@property (readonly, nonatomic) double floatingUnfocusedShadowOpacity;
@property (readonly, nonatomic) double floatingUnfocusedShadowRadius;
@property (readonly, nonatomic) double floatingUnfocusedShadowVerticalOffset;
@property (readonly, nonatomic) double focusedSizeIncrease;
@property (copy, nonatomic) NSArray *overlaySpecs; // @synthesize overlaySpecs=_overlaySpecs;
@property (nonatomic) long long roundedCornersMode; // @synthesize roundedCornersMode=_roundedCornersMode;
@property (nonatomic) BOOL shouldEnableFocus; // @synthesize shouldEnableFocus=_shouldEnableFocus;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)init;
- (BOOL)isEqual:(id)arg1;

@end

