//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PhotosUI/PXActivity-Protocol.h>

@protocol PXActivityItemSourceController;

@protocol PXMomentShareSuggestionHandlingActivity <PXActivity>
+ (BOOL)canPerformActivityAsIndividualItemsInSourceController:(id<PXActivityItemSourceController>)arg1;
@end

