//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PhotosUICore/NSObject-Protocol.h>

@class PXSectionedSelectionManager, PXSelectionSnapshot;

@protocol PXSectionedSelectionManagerSnapshotValidator <NSObject>
- (PXSelectionSnapshot *)selectionManager:(PXSectionedSelectionManager *)arg1 validateSnapshot:(PXSelectionSnapshot *)arg2;
@end

