//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PhotosUICore/NSObject-Protocol.h>

@class PXSharedAlbumInvitationView, UIViewController;

@protocol PXSharedAlbumInvitationViewDelegate <NSObject>

@optional
- (void)sharedAlbumInvitationView:(PXSharedAlbumInvitationView *)arg1 didAccept:(BOOL)arg2;
- (void)sharedAlbumInvitationView:(PXSharedAlbumInvitationView *)arg1 presentViewController:(UIViewController *)arg2;
- (void)sharedAlbumInvitationViewDidReportAsJunk:(PXSharedAlbumInvitationView *)arg1;
@end

