//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString;

@interface _WKAttachmentInfo : NSObject
{
    struct RetainPtr<NSData> _data;
    struct RetainPtr<NSString> _name;
    struct RetainPtr<NSString> _filePath;
    struct RetainPtr<NSString> _contentType;
    struct RetainPtr<NSError> _fileLoadingError;
}

@property (readonly, nonatomic) NSString *contentType;
@property (readonly, nonatomic) NSData *data;
@property (readonly, nonatomic) NSString *filePath;
@property (readonly, nonatomic) NSString *name;

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)fileLoadingError;
- (id)initWithInfo:(const struct AttachmentInfo *)arg1;

@end

