//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <WebKit/NSCopying-Protocol.h>

@interface WKFindConfiguration : NSObject <NSCopying>
{
    BOOL _backwards;
    BOOL _caseSensitive;
    BOOL _wraps;
}

@property (nonatomic) BOOL backwards; // @synthesize backwards=_backwards;
@property (nonatomic) BOOL caseSensitive; // @synthesize caseSensitive=_caseSensitive;
@property (nonatomic) BOOL wraps; // @synthesize wraps=_wraps;

- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

