//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WebKitLegacy/WebEvent.h>

@class UIEvent;

__attribute__((visibility("hidden")))
@interface WKWebEvent : WebEvent
{
    UIEvent *_uiEvent;
}

@property (strong, nonatomic) UIEvent *uiEvent; // @synthesize uiEvent=_uiEvent;

- (void)dealloc;

@end

