//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <HealthKit/HKCodedObject-Protocol.h>
#import <HealthKit/NSCopying-Protocol.h>
#import <HealthKit/NSSecureCoding-Protocol.h>

@class HKInspectableValue, NSArray, NSString;

@interface HKInspectableValueCollection : NSObject <NSSecureCoding, NSCopying, HKCodedObject>
{
    long long _collectionType;
    NSArray *_collection;
    NSArray *_elementTags;
}

@property (readonly, nonatomic) NSArray *collection; // @synthesize collection=_collection;
@property (readonly, nonatomic) long long collectionType; // @synthesize collectionType=_collectionType;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, nonatomic) NSArray *elementTags; // @synthesize elementTags=_elementTags;
@property (readonly) unsigned long long hash;
@property (readonly, nonatomic) HKInspectableValue *inspectableValue;
@property (readonly, nonatomic) NSArray *inspectableValues;
@property (readonly, nonatomic) HKInspectableValue *max;
@property (readonly, nonatomic) HKInspectableValue *min;
@property (readonly) Class superclass;
@property (readonly, nonatomic) NSString *unitString;

+ (BOOL)hasNoValue:(id)arg1;
+ (id)indexableKeyPathsWithPrefix:(id)arg1;
+ (id)inspectableValueCollectionListWithValues:(id)arg1;
+ (id)inspectableValueCollectionRangeWithMax:(id)arg1;
+ (id)inspectableValueCollectionRangeWithMin:(id)arg1;
+ (id)inspectableValueCollectionRangeWithMin:(id)arg1 max:(id)arg2;
+ (id)inspectableValueCollectionSingleWithValue:(id)arg1;
+ (id)inspectableValueCollectionTaggedListWithValues:(id)arg1 tags:(id)arg2;
+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (void)_assertCollectionType;
- (id)_initWithCollectionType:(long long)arg1 collection:(id)arg2;
- (id)_initWithCollectionType:(long long)arg1 collection:(id)arg2 tags:(id)arg3;
- (BOOL)applyConcepts:(id)arg1 forKeyPath:(id)arg2 error:(id *)arg3;
- (id)codingsForKeyPath:(id)arg1 error:(id *)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)valuesWithTag:(id)arg1;

@end

