//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SDFTimeUtils : NSObject
{
}

+ (void)setTimeSpec:(struct timespec *)arg1 withDate:(id)arg2;
+ (void)setTimeSpec:(struct timespec *)arg1 withTimeVal:(struct timeval *)arg2;
+ (void)setTimeVal:(struct timeval *)arg1 withDate:(id)arg2;
+ (void)setTimeVal:(struct timeval *)arg1 withTimeSpec:(struct timespec *)arg2;
+ (double)timeIntervalWithTimeSpec:(struct timespec *)arg1;
+ (double)timeIntervalWithTimeVal:(struct timeval *)arg1;

@end

