//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValue.h>

@interface NSValue (LPExtras)
+ (id)_lp_valueWithCGRect:(struct CGRect)arg1;
+ (id)_lp_valueWithCGSize:(struct CGSize)arg1;
@end

