//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSArray, UIColor, UIFont, UILabel, UIStackView;

@interface SRAuthorizationCategoryDetailCell : UITableViewCell
{
    BOOL _showAppUsage;
    BOOL _OBKStyle;
    UILabel *_categorySubTitleLabel;
    UILabel *_categoryTitleLabel;
    UILabel *_appUsageTitleLabel;
    UILabel *_appUsageBodyLabel;
    UILabel *_collectedTitleLabel;
    UILabel *_notCollectedTitleLabel;
    NSArray *_collectedLabels;
    NSArray *_notCollectedLabels;
    long long _numberOfCollectedLabels;
    long long _numberOfNotCollectedLabels;
    UIStackView *_categoryStack;
    UIStackView *_appUsageStack;
    UIStackView *_stacks;
    UIFont *_titleFont;
    UIFont *_bodyFont;
    UIColor *_fontColor;
}

@property (nonatomic) BOOL OBKStyle; // @synthesize OBKStyle=_OBKStyle;
@property (readonly, nonatomic) UILabel *appUsageBodyLabel; // @synthesize appUsageBodyLabel=_appUsageBodyLabel;
@property (strong, nonatomic) UIStackView *appUsageStack; // @synthesize appUsageStack=_appUsageStack;
@property (readonly, nonatomic) UILabel *appUsageTitleLabel; // @synthesize appUsageTitleLabel=_appUsageTitleLabel;
@property (strong, nonatomic) UIFont *bodyFont; // @synthesize bodyFont=_bodyFont;
@property (strong, nonatomic) UIStackView *categoryStack; // @synthesize categoryStack=_categoryStack;
@property (readonly, nonatomic) UILabel *categorySubTitleLabel; // @synthesize categorySubTitleLabel=_categorySubTitleLabel;
@property (readonly, nonatomic) UILabel *categoryTitleLabel; // @synthesize categoryTitleLabel=_categoryTitleLabel;
@property (strong, nonatomic) NSArray *collectedLabels; // @synthesize collectedLabels=_collectedLabels;
@property (readonly, nonatomic) UILabel *collectedTitleLabel; // @synthesize collectedTitleLabel=_collectedTitleLabel;
@property (strong, nonatomic) UIColor *fontColor; // @synthesize fontColor=_fontColor;
@property (strong, nonatomic) NSArray *notCollectedLabels; // @synthesize notCollectedLabels=_notCollectedLabels;
@property (readonly, nonatomic) UILabel *notCollectedTitleLabel; // @synthesize notCollectedTitleLabel=_notCollectedTitleLabel;
@property (nonatomic) long long numberOfCollectedLabels; // @synthesize numberOfCollectedLabels=_numberOfCollectedLabels;
@property (nonatomic) long long numberOfNotCollectedLabels; // @synthesize numberOfNotCollectedLabels=_numberOfNotCollectedLabels;
@property (nonatomic) BOOL showAppUsage; // @synthesize showAppUsage=_showAppUsage;
@property (strong, nonatomic) UIStackView *stacks; // @synthesize stacks=_stacks;
@property (strong, nonatomic) UIFont *titleFont; // @synthesize titleFont=_titleFont;

- (void)addBulletStackViewForCollected:(BOOL)arg1 count:(long long)arg2;
- (void)dealloc;
- (id)dynamicHeightLabel;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 titleFont:(id)arg3 bodyFont:(id)arg4 fontColor:(id)arg5 OBKStyle:(BOOL)arg6;
- (id)stackViewForSubviews:(id)arg1 spacing:(double)arg2;

@end

