//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <RelevanceEngine/_REPeriodOfDayProperties-Protocol.h>

@class NSDate, NSDateInterval;

@interface _REPeriodOfDay : NSObject <_REPeriodOfDayProperties>
{
    unsigned long long _periodOfDay;
    NSDateInterval *_interval;
}

@property (readonly, nonatomic) NSDate *endDate;
@property (readonly, nonatomic) NSDateInterval *interval; // @synthesize interval=_interval;
@property (readonly, nonatomic) unsigned long long periodOfDay; // @synthesize periodOfDay=_periodOfDay;
@property (readonly, nonatomic) NSDate *startDate;

- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (id)initWithInterval:(id)arg1 periodOfDay:(unsigned long long)arg2;
- (BOOL)isEqual:(id)arg1;

@end

