//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <ProactiveEventTracker/NSCopying-Protocol.h>

@class PETRawMessage;

@interface PETAggregationKey : PBCodable <NSCopying>
{
    double _bucket;
    unsigned int _datestamp;
    PETRawMessage *_rawMessage;
    int _type;
    struct {
        unsigned int bucket:1;
        unsigned int datestamp:1;
        unsigned int type:1;
    } _has;
}

@property (nonatomic) double bucket; // @synthesize bucket=_bucket;
@property (nonatomic) unsigned int datestamp; // @synthesize datestamp=_datestamp;
@property (nonatomic) BOOL hasBucket;
@property (nonatomic) BOOL hasDatestamp;
@property (readonly, nonatomic) BOOL hasRawMessage;
@property (nonatomic) BOOL hasType;
@property (strong, nonatomic) PETRawMessage *rawMessage; // @synthesize rawMessage=_rawMessage;
@property (nonatomic) int type; // @synthesize type=_type;

- (void).cxx_destruct;
- (int)StringAsType:(id)arg1;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)typeAsString:(int)arg1;
- (void)writeTo:(id)arg1;

@end

