//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <HealthDaemon/NSCopying-Protocol.h>

@class HDCodableMessageVersion, NSData, NSString;

@interface HDCodableFHIRResource : PBCodable <NSCopying>
{
    long long _extractionHints;
    long long _originVersionMajor;
    long long _originVersionMinor;
    long long _originVersionPatch;
    double _receivedDate;
    NSString *_accountIdentifier;
    NSString *_fhirVersion;
    NSString *_gatewayExternalID;
    HDCodableMessageVersion *_messageVersion;
    NSString *_originVersionBuild;
    NSData *_rawContent;
    NSString *_receivedDateTimeZoneName;
    NSString *_resourceID;
    NSString *_resourceType;
    NSString *_sourceURL;
    struct {
        unsigned int extractionHints:1;
        unsigned int originVersionMajor:1;
        unsigned int originVersionMinor:1;
        unsigned int originVersionPatch:1;
        unsigned int receivedDate:1;
    } _has;
}

@property (strong, nonatomic) NSString *accountIdentifier; // @synthesize accountIdentifier=_accountIdentifier;
@property (nonatomic) long long extractionHints; // @synthesize extractionHints=_extractionHints;
@property (strong, nonatomic) NSString *fhirVersion; // @synthesize fhirVersion=_fhirVersion;
@property (strong, nonatomic) NSString *gatewayExternalID; // @synthesize gatewayExternalID=_gatewayExternalID;
@property (readonly, nonatomic) BOOL hasAccountIdentifier;
@property (nonatomic) BOOL hasExtractionHints;
@property (readonly, nonatomic) BOOL hasFhirVersion;
@property (readonly, nonatomic) BOOL hasGatewayExternalID;
@property (readonly, nonatomic) BOOL hasMessageVersion;
@property (readonly, nonatomic) BOOL hasOriginVersionBuild;
@property (nonatomic) BOOL hasOriginVersionMajor;
@property (nonatomic) BOOL hasOriginVersionMinor;
@property (nonatomic) BOOL hasOriginVersionPatch;
@property (readonly, nonatomic) BOOL hasRawContent;
@property (nonatomic) BOOL hasReceivedDate;
@property (readonly, nonatomic) BOOL hasReceivedDateTimeZoneName;
@property (readonly, nonatomic) BOOL hasResourceID;
@property (readonly, nonatomic) BOOL hasResourceType;
@property (readonly, nonatomic) BOOL hasSourceURL;
@property (strong, nonatomic) HDCodableMessageVersion *messageVersion; // @synthesize messageVersion=_messageVersion;
@property (strong, nonatomic) NSString *originVersionBuild; // @synthesize originVersionBuild=_originVersionBuild;
@property (nonatomic) long long originVersionMajor; // @synthesize originVersionMajor=_originVersionMajor;
@property (nonatomic) long long originVersionMinor; // @synthesize originVersionMinor=_originVersionMinor;
@property (nonatomic) long long originVersionPatch; // @synthesize originVersionPatch=_originVersionPatch;
@property (strong, nonatomic) NSData *rawContent; // @synthesize rawContent=_rawContent;
@property (nonatomic) double receivedDate; // @synthesize receivedDate=_receivedDate;
@property (strong, nonatomic) NSString *receivedDateTimeZoneName; // @synthesize receivedDateTimeZoneName=_receivedDateTimeZoneName;
@property (strong, nonatomic) NSString *resourceID; // @synthesize resourceID=_resourceID;
@property (strong, nonatomic) NSString *resourceType; // @synthesize resourceType=_resourceType;
@property (strong, nonatomic) NSString *sourceURL; // @synthesize sourceURL=_sourceURL;

- (void).cxx_destruct;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;

@end

