//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class HDDaemon, HKObserverSet, NSMutableDictionary;
@protocol HDProfileManagerObserver, OS_dispatch_queue;

@interface HDProfileManager : NSObject
{
    HDDaemon *_daemon;
    NSMutableDictionary *_profiles;
    HKObserverSet<HDProfileManagerObserver> *_observers;
    NSObject<OS_dispatch_queue> *_resourceQueue;
}

- (void).cxx_destruct;
- (id)_directoryNameForProfileIdentifier:(id)arg1;
- (id)_directoryURLForProfileIdentifier:(id)arg1;
- (id)_profileIdentifierForDirectoryName:(id)arg1 error:(id *)arg2;
- (void)_resourceQueue_addProfile:(id)arg1 dispatchChangeNotification:(BOOL)arg2;
- (id)_resourceQueue_createProfileOfType:(long long)arg1 UUID:(id)arg2 name:(id)arg3 error:(id *)arg4;
- (BOOL)_resourceQueue_deleteProfile:(id)arg1 error:(id *)arg2;
- (void)_resourceQueue_loadSecondaryProfiles;
- (id)_resourceQueue_profileForIdentifier:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)addProfile:(id)arg1;
- (id)allProfileIdentifiers;
- (BOOL)createProfileForIdentifier:(id)arg1 displayName:(id)arg2 error:(id *)arg3;
- (id)createProfileOfType:(long long)arg1 displayName:(id)arg2 error:(id *)arg3;
- (BOOL)deleteProfile:(id)arg1 error:(id *)arg2;
- (void)dispatchProfileListDidChange;
- (id)initWithDaemon:(id)arg1;
- (void)invalidateAndWait;
- (id)newProfileWithIdentifier:(id)arg1 daemon:(id)arg2 directoryPath:(id)arg3;
- (id)profileAssociatedWithNRDeviceUUID:(id)arg1;
- (id)profileForIdentifier:(id)arg1;
- (id)profileIdentifierForUUID:(id)arg1;
- (void)reloadSecondaryProfiles;
- (void)removeObserver:(id)arg1;

@end

