//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <HealthDaemon/NSObject-Protocol.h>

@class HDSQLiteDatabase, HDSQLiteStatement, NSArray, NSDate, NSSet, NSString, NSUUID;

@protocol HDSQLiteEntity <NSObject>
+ (NSArray *)allDatabaseColumnNames;
+ (NSString *)associationPropertyForEntityClass:(Class)arg1;
+ (NSArray *)columnsDefinition;
+ (NSString *)databaseName;
+ (NSString *)databaseTable;
+ (HDSQLiteStatement *)deleteStatementWithProperty:(NSString *)arg1 database:(HDSQLiteDatabase *)arg2;
+ (NSString *)disambiguatedDatabaseTable;
+ (NSString *)disambiguatedSQLForProperty:(NSString *)arg1;
+ (Class)entityForProperty:(NSString *)arg1;
+ (NSString *)foreignDatabaseColumnForProperty:(NSString *)arg1;
+ (NSString *)foreignDatabaseTableForProperty:(NSString *)arg1;
+ (NSSet *)foreignDatabaseTablesToDelete;
+ (NSString *)foreignKeyColumnForTable:(NSString *)arg1;
+ (NSSet *)joinClausesForProperty:(NSString *)arg1;
+ (NSArray *)tableAliases;
- (NSUUID *)UUIDForProperty:(NSString *)arg1 database:(HDSQLiteDatabase *)arg2;
- (BOOL)booleanForProperty:(NSString *)arg1 database:(HDSQLiteDatabase *)arg2;
- (NSDate *)dateForProperty:(NSString *)arg1 database:(HDSQLiteDatabase *)arg2;
- (BOOL)deleteFromDatabase:(HDSQLiteDatabase *)arg1 error:(id *)arg2;
- (BOOL)getValuesForProperties:(NSArray *)arg1 database:(HDSQLiteDatabase *)arg2 handler:(void (^)(NSArray *, struct HDSQLiteRow *))arg3;
- (BOOL)getValuesForProperties:(NSArray *)arg1 withDatabase:(HDSQLiteDatabase *)arg2 applier:(void (^)(NSArray *, struct HDSQLiteRow *))arg3;
- (id)valueForProperty:(NSString *)arg1 database:(HDSQLiteDatabase *)arg2;

@optional
+ (NSString *)columnNameForSortIdentifier:(NSString *)arg1;
@end

