//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FrontBoardServices/FBSSettingsDiff.h>

@interface FBSSceneClientSettingsDiff : FBSSettingsDiff
{
}

+ (id)diffFromSettings:(id)arg1 toSettings:(id)arg2;
- (BOOL)inspectPreferredInterfaceOrientation:(long long *)arg1;
- (BOOL)inspectPreferredLevel:(double *)arg1;
- (BOOL)inspectPreferredSceneHostIdentifier:(id *)arg1;
- (id)keyDescriptionForSetting:(unsigned long long)arg1;
- (id)settingsByApplyingToMutableCopyOfSettings:(id)arg1;
- (id)valueDescriptionForFlag:(long long)arg1 object:(id)arg2 ofSetting:(unsigned long long)arg3;

@end

