//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <CoreFollowUpUI/FLExtensionRemoteContextInterface-Protocol.h>
#import <CoreFollowUpUI/NSExtensionRequestHandling-Protocol.h>

@class NSExtensionContext, NSString;

@interface FLExtensionViewController : UIViewController <NSExtensionRequestHandling, FLExtensionRemoteContextInterface>
{
    NSExtensionContext *_context;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)_exportedInterface;
+ (id)_remoteViewControllerInterface;
- (void).cxx_destruct;
- (void)beginRequestWithExtensionContext:(id)arg1;
- (void)finishProcessing;
- (void)followUpPerformUpdateWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)hostInterface;
- (void)processFollowUpItem:(id)arg1 selectedAction:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)viewDidAppear:(BOOL)arg1;

@end

