//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ModelIO/MDLCamera.h>

@interface MDLStereoscopicCamera : MDLCamera
{
    float _interPupillaryDistance;
    float _leftVergence;
    float _rightVergence;
    float _overlap;
}

@property (nonatomic) float interPupillaryDistance; // @synthesize interPupillaryDistance=_interPupillaryDistance;
@property (readonly, nonatomic) CDStruct_14d5dc5e leftProjectionMatrix;
@property (nonatomic) float leftVergence; // @synthesize leftVergence=_leftVergence;
@property (readonly, nonatomic) CDStruct_14d5dc5e leftViewMatrix;
@property (nonatomic) float overlap; // @synthesize overlap=_overlap;
@property (readonly, nonatomic) CDStruct_14d5dc5e rightProjectionMatrix;
@property (nonatomic) float rightVergence; // @synthesize rightVergence=_rightVergence;
@property (readonly, nonatomic) CDStruct_14d5dc5e rightViewMatrix;

- (id)init;

@end

