//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class AKController, AKPageModelController, NSDictionary, UIColor, UIFont;

@interface AKAttributeController : NSObject
{
    BOOL _strokeIsDashed;
    BOOL _hasShadow;
    AKPageModelController *modelControllerToObserveForSelections;
    UIColor *_strokeColor;
    UIColor *_fillColor;
    double _strokeWidth;
    long long _brushStyle;
    unsigned long long _arrowHeadStyle;
    UIFont *_font;
    NSDictionary *_textAttributes;
    long long _highlightStyle;
    AKController *_controller;
}

@property unsigned long long arrowHeadStyle; // @synthesize arrowHeadStyle=_arrowHeadStyle;
@property long long brushStyle; // @synthesize brushStyle=_brushStyle;
@property (weak) AKController *controller; // @synthesize controller=_controller;
@property (strong) UIColor *fillColor; // @synthesize fillColor=_fillColor;
@property (strong) UIFont *font; // @synthesize font=_font;
@property BOOL hasShadow; // @synthesize hasShadow=_hasShadow;
@property long long highlightStyle; // @synthesize highlightStyle=_highlightStyle;
@property (strong, nonatomic) AKPageModelController *modelControllerToObserveForSelections; // @synthesize modelControllerToObserveForSelections;
@property (strong) UIColor *strokeColor; // @synthesize strokeColor=_strokeColor;
@property BOOL strokeIsDashed; // @synthesize strokeIsDashed=_strokeIsDashed;
@property double strokeWidth; // @synthesize strokeWidth=_strokeWidth;
@property (strong) NSDictionary *textAttributes; // @synthesize textAttributes=_textAttributes;

+ (id)defaultFont;
+ (id)defaultTextAttributes;
+ (void)initialize;
- (void).cxx_destruct;
- (BOOL)_isEnabledForSender:(id)arg1 segment:(long long)arg2 withSelectedAnnotations:(id)arg3;
- (void)_persistCurrentAttributes;
- (void)_restorePersistedAttributes;
- (void)_syncAttributesFromSelectedAnnotationsToUI;
- (void)_syncAttributesFromSenderToSelfAndSelectedAnnotations:(id)arg1 segment:(long long)arg2;
- (void)_updateStateOnSender:(id)arg1 segment:(long long)arg2;
- (BOOL)_updateStateOnSender:(id)arg1 segment:(long long)arg2 fromSelectedAnnotations:(id)arg3;
- (void)_updateStateOnSenderFromSelf:(id)arg1 segment:(long long)arg2;
- (id)initWithController:(id)arg1;
- (BOOL)isAttributeSenderEnabled:(id)arg1 segment:(long long)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)performAttributeActionForSender:(id)arg1 segment:(long long)arg2;
- (void)restoreStrokeColorToSystemDefault;
- (BOOL)strokeColorIsEqualTo:(id)arg1;
- (void)syncFillColorOnSelectionToUI;
- (void)syncStrokeColorOnSelectionToUI;
- (void)updateAttributeSenderState:(id)arg1 segment:(long long)arg2 enabled:(BOOL)arg3;

@end

