//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MPCPlayerResponse, NSArray, NSDictionary;
@protocol MRUUpNextDataSourceDelegate;

__attribute__((visibility("hidden")))
@interface MRUUpNextDataSource : NSObject
{
    MPCPlayerResponse *_response;
    id<MRUUpNextDataSourceDelegate> _delegate;
    NSArray *_responseItemIDs;
    NSDictionary *_responseItemsByIdentifier;
}

@property (weak, nonatomic) id<MRUUpNextDataSourceDelegate> delegate; // @synthesize delegate=_delegate;
@property (strong, nonatomic) MPCPlayerResponse *response; // @synthesize response=_response;
@property (readonly, nonatomic) NSArray *responseItemIDs; // @synthesize responseItemIDs=_responseItemIDs;
@property (strong, nonatomic) NSDictionary *responseItemsByIdentifier; // @synthesize responseItemsByIdentifier=_responseItemsByIdentifier;

- (void).cxx_destruct;
- (BOOL)canMoveResponseItemWithIdentifier:(id)arg1;
- (id)init;
- (void)moveReponseItemToNextWithIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)moveReponseItemWithIdentifier:(id)arg1 afterResponseItemWithIdentifier:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)objectForKeyedSubscript:(id)arg1;
- (void)playItemWithIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)removeResponseItemWithIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)responseItemForIdentifier:(id)arg1;
- (void)updateContentItems;

@end

