//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (SBS)
+ (id)sbs_stringFromCGRect:(struct CGRect)arg1;
- (struct CGRect)sbs_cgRectValue;
@end

