//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SafariShared/NSObject-Protocol.h>

@class NSURL;

@protocol WBSHistoryLoader <NSObject>
- (id)initWithURL:(NSURL *)arg1 itemCountLimit:(unsigned long long)arg2 ageLimit:(double)arg3 historyItemClass:(Class)arg4;
- (void)startLoading;
- (void)waitForLoadingToComplete;
@end

