//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PassKitCore/PKApplyWebServiceRequest.h>

@class NSArray, NSData, NSString, NSURL;

@interface PKApplyWebServiceDocumentSubmissionRequest : PKApplyWebServiceRequest
{
    NSString *_applicationIdentifier;
    unsigned long long _featureIdentifier;
    NSURL *_baseURL;
    NSData *_frontImageData;
    NSData *_backImageData;
    NSString *_documentCountryCode;
    unsigned long long _documentType;
    NSArray *_certificates;
}

@property (copy, nonatomic) NSString *applicationIdentifier; // @synthesize applicationIdentifier=_applicationIdentifier;
@property (copy, nonatomic) NSData *backImageData; // @synthesize backImageData=_backImageData;
@property (strong, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
@property (copy, nonatomic) NSArray *certificates; // @synthesize certificates=_certificates;
@property (copy, nonatomic) NSString *documentCountryCode; // @synthesize documentCountryCode=_documentCountryCode;
@property (nonatomic) unsigned long long documentType; // @synthesize documentType=_documentType;
@property (nonatomic) unsigned long long featureIdentifier; // @synthesize featureIdentifier=_featureIdentifier;
@property (copy, nonatomic) NSData *frontImageData; // @synthesize frontImageData=_frontImageData;

+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (id)_urlRequestWithAppleAccountInformation:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

