//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, PKPassFieldTemplate;

@interface PKPassBucketTemplate : NSObject
{
    BOOL _sitsOnStripImage;
    long long _bucketAlignment;
    double _minFieldPadding;
    PKPassFieldTemplate *_defaultFieldTemplate;
    unsigned long long _maxFields;
    NSMutableArray *_fieldTemplates;
    struct CGRect _bucketRect;
}

@property (nonatomic) long long bucketAlignment; // @synthesize bucketAlignment=_bucketAlignment;
@property (nonatomic) struct CGRect bucketRect; // @synthesize bucketRect=_bucketRect;
@property (strong, nonatomic) PKPassFieldTemplate *defaultFieldTemplate; // @synthesize defaultFieldTemplate=_defaultFieldTemplate;
@property (strong, nonatomic) NSMutableArray *fieldTemplates; // @synthesize fieldTemplates=_fieldTemplates;
@property (nonatomic) unsigned long long maxFields; // @synthesize maxFields=_maxFields;
@property (nonatomic) double minFieldPadding; // @synthesize minFieldPadding=_minFieldPadding;
@property (nonatomic) BOOL sitsOnStripImage; // @synthesize sitsOnStripImage=_sitsOnStripImage;

- (void)addFieldTemplate:(id)arg1;
- (void)dealloc;
- (id)templateForFieldAtIndex:(unsigned long long)arg1;

@end

