//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <PassKitCore/NSSecureCoding-Protocol.h>

@class NSArray, NSDate, NSDecimalNumber, NSSet, NSString, PKCurrencyAmount, PKMerchant;

@interface PKPaymentTransactionRequest : NSObject <NSSecureCoding>
{
    NSSet *_transactionSourceIdentifiers;
    NSArray *_transactionTypes;
    NSArray *_transactionSources;
    NSArray *_transactionStatuses;
    long long _peerPaymentSubType;
    NSDecimalNumber *_rewardsValue;
    unsigned long long _rewardsValueUnit;
    PKMerchant *_merchant;
    long long _merchantCategory;
    NSArray *_regions;
    NSDate *_startDate;
    NSDate *_endDate;
    long long _dateOrder;
    NSString *_currencyCode;
    PKCurrencyAmount *_amount;
    long long _amountComparison;
    NSSet *_tags;
    long long _limit;
}

@property (strong, nonatomic) PKCurrencyAmount *amount; // @synthesize amount=_amount;
@property (nonatomic) long long amountComparison; // @synthesize amountComparison=_amountComparison;
@property (strong, nonatomic) NSString *currencyCode; // @synthesize currencyCode=_currencyCode;
@property (nonatomic) long long dateOrder; // @synthesize dateOrder=_dateOrder;
@property (strong, nonatomic) NSDate *endDate; // @synthesize endDate=_endDate;
@property (nonatomic) long long limit; // @synthesize limit=_limit;
@property (strong, nonatomic) PKMerchant *merchant; // @synthesize merchant=_merchant;
@property (nonatomic) long long merchantCategory; // @synthesize merchantCategory=_merchantCategory;
@property (nonatomic) long long peerPaymentSubType; // @synthesize peerPaymentSubType=_peerPaymentSubType;
@property (strong, nonatomic) NSArray *regions; // @synthesize regions=_regions;
@property (strong, nonatomic) NSDecimalNumber *rewardsValue; // @synthesize rewardsValue=_rewardsValue;
@property (nonatomic) unsigned long long rewardsValueUnit; // @synthesize rewardsValueUnit=_rewardsValueUnit;
@property (strong, nonatomic) NSDate *startDate; // @synthesize startDate=_startDate;
@property (strong, nonatomic) NSSet *tags; // @synthesize tags=_tags;
@property (strong, nonatomic) NSSet *transactionSourceIdentifiers; // @synthesize transactionSourceIdentifiers=_transactionSourceIdentifiers;
@property (strong, nonatomic) NSArray *transactionSources; // @synthesize transactionSources=_transactionSources;
@property (strong, nonatomic) NSArray *transactionStatuses; // @synthesize transactionStatuses=_transactionStatuses;
@property (strong, nonatomic) NSArray *transactionTypes; // @synthesize transactionTypes=_transactionTypes;

+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

