//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <PassKitCore/NSCopying-Protocol.h>

@class NSString;

@interface PKProtobufPeerPaymentMessage : PBCodable <NSCopying>
{
    long long _amount;
    NSString *_currency;
    NSString *_identifer;
    NSString *_memo;
    NSString *_paymentIdentifier;
    NSString *_recipientAddress;
    NSString *_requestToken;
    NSString *_senderAddress;
    NSString *_transactionIdentifier;
    int _type;
    unsigned int _version;
    CDStruct_9fb36b4c _has;
}

@property (nonatomic) long long amount; // @synthesize amount=_amount;
@property (strong, nonatomic) NSString *currency; // @synthesize currency=_currency;
@property (nonatomic) BOOL hasAmount;
@property (readonly, nonatomic) BOOL hasCurrency;
@property (readonly, nonatomic) BOOL hasIdentifer;
@property (readonly, nonatomic) BOOL hasMemo;
@property (readonly, nonatomic) BOOL hasPaymentIdentifier;
@property (readonly, nonatomic) BOOL hasRecipientAddress;
@property (readonly, nonatomic) BOOL hasRequestToken;
@property (readonly, nonatomic) BOOL hasSenderAddress;
@property (readonly, nonatomic) BOOL hasTransactionIdentifier;
@property (nonatomic) BOOL hasType;
@property (strong, nonatomic) NSString *identifer; // @synthesize identifer=_identifer;
@property (strong, nonatomic) NSString *memo; // @synthesize memo=_memo;
@property (strong, nonatomic) NSString *paymentIdentifier; // @synthesize paymentIdentifier=_paymentIdentifier;
@property (strong, nonatomic) NSString *recipientAddress; // @synthesize recipientAddress=_recipientAddress;
@property (strong, nonatomic) NSString *requestToken; // @synthesize requestToken=_requestToken;
@property (strong, nonatomic) NSString *senderAddress; // @synthesize senderAddress=_senderAddress;
@property (strong, nonatomic) NSString *transactionIdentifier; // @synthesize transactionIdentifier=_transactionIdentifier;
@property (nonatomic) int type; // @synthesize type=_type;
@property (nonatomic) unsigned int version; // @synthesize version=_version;

- (void).cxx_destruct;
- (int)StringAsType:(id)arg1;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)typeAsString:(int)arg1;
- (void)writeTo:(id)arg1;

@end

