//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <StoreKit/SKStoreProductViewController.h>

#import <PassKit/SKStoreProductViewControllerDelegate-Protocol.h>

@class NSString;

@interface PKStoreProductViewController : SKStoreProductViewController <SKStoreProductViewControllerDelegate>
{
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (id)initWithItemIdentifier:(id)arg1;
- (void)productViewControllerDidFinish:(id)arg1;

@end

