//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreImage/CIFilter.h>

@class CIImage, CIVector, NSNumber;

__attribute__((visibility("hidden")))
@interface CIMirror : CIFilter
{
    CIImage *inputImage;
    CIVector *inputPoint;
    NSNumber *inputAngle;
}

@property (strong, nonatomic) NSNumber *inputAngle; // @synthesize inputAngle;
@property (strong, nonatomic) CIImage *inputImage; // @synthesize inputImage;
@property (strong, nonatomic) CIVector *inputPoint; // @synthesize inputPoint;

+ (id)customAttributes;
- (id)_kernel;
- (struct Rectangle)computeDOD:(struct vec2)arg1 tst:(struct vec3)arg2 off:(struct vec4)arg3 mtx:(struct vec4)arg4;
- (id)outputImage;

@end

