//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreImage/CIImageProcessorKernel.h>

__attribute__((visibility("hidden")))
@interface CIPortraitFaceMaskProcessorKernel : CIImageProcessorKernel
{
}

+ (BOOL)allowPartialOutputRegion;
+ (int)formatForInputAtIndex:(int)arg1;
+ (int)outputFormat;
+ (BOOL)processWithInputs:(id)arg1 arguments:(id)arg2 output:(id)arg3 error:(id *)arg4;
+ (struct CGRect)roiForInput:(int)arg1 arguments:(id)arg2 outputRect:(struct CGRect)arg3;

@end

