//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreImage/CGRenderer.h>

__attribute__((visibility("hidden")))
@interface PDFRenderer : CGRenderer
{
    struct __CFDictionary *info;
    struct __CFData *data;
    struct CGDataConsumer *dataConsumer;
}

- (void)dealloc;
- (void)flushRender;
- (id)init;
- (const struct __CFData *)pdfdata;
- (BOOL)setCanvasWidth:(unsigned int)arg1 height:(unsigned int)arg2;
- (void)setFileTitle:(id)arg1;
- (void)setFileURL:(id)arg1;

@end

