//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GameCenterUI/NSObject-Protocol.h>

@class GKBubbleFlowBubbleControl, GKBubbleFlowContainerView, GKBubblePathAnimator, NSArray, UIView, UIViewController;

@protocol GKBubbleFlowableViewController <NSObject>

@optional
- (GKBubblePathAnimator *)bubbleAnimatorForRotation;
- (GKBubblePathAnimator *)bubbleAnimatorForTransitionFromViewController:(UIViewController *)arg1;
- (GKBubblePathAnimator *)bubbleAnimatorForTransitionToViewController:(UIViewController *)arg1;
- (GKBubbleFlowContainerView *)bubbleContainerView;
- (double)bubbleFlowAnimateInDuration;
- (double)bubbleFlowAnimateOutDuration;
- (double)bubbleFlowSubviewFadeInDelay;
- (double)bubbleFlowSubviewFadeInDuration;
- (double)bubbleFlowSubviewFadeOutDelay;
- (double)bubbleFlowSubviewFadeOutDuration;
- (NSArray *)bubblesUsedForAnyTransition;
- (void)configureControlForBubble:(GKBubbleFlowBubbleControl *)arg1;
- (UIView *)containerViewForBubbleOfType:(long long)arg1;
- (void)delayAppearingWithBubbleFlowUntil:(void (^)(BOOL))arg1;
- (void)delayDisappearingWithBubbleFlowUntil:(void (^)(BOOL))arg1;
- (struct CGRect)finalScreenFrameInViewCoordinatesForBubbleOfType:(long long)arg1;
- (BOOL)readyToAppearWithBubbleFlow;
- (BOOL)readyToDisappearWithBubbleFlow;
- (BOOL)shouldUseSlidingDoorWhenTransitioningFrom;
- (BOOL)shouldUseSlidingDoorWhenTransitioningTo;
- (BOOL)updateBubbleTextImmediatelyForTransitionFromViewController:(UIViewController *)arg1;
- (void)viewDidAppearAnimated:(BOOL)arg1 bubbleFlow:(BOOL)arg2;
- (void)viewDidDisappearAnimated:(BOOL)arg1 bubbleFlow:(BOOL)arg2;
- (void)viewWillAppearAnimated:(BOOL)arg1 bubbleFlow:(BOOL)arg2;
- (void)viewWillDisappearAnimated:(BOOL)arg1 bubbleFlow:(BOOL)arg2;
- (NSArray *)viewsToAnimateInWhileAppearingWithBubbleFlow;
- (NSArray *)viewsToAnimateOutWhileDisappearingWithBubbleFlow;
- (void)willAnimateAppearingWithBubbleFlow;
- (void)willAnimateDisappearingWithBubbleFlow;
- (void)willAnimateKeyframesForAppearingWithBubbleFlowFromRelativeStartTime:(double)arg1 relativeDuration:(double)arg2 absoluteTransitionDuration:(double)arg3 fromViewController:(UIViewController *)arg4;
- (void)willAnimateKeyframesForDisappearingWithBubbleFlowFromRelativeStartTime:(double)arg1 relativeDuration:(double)arg2 absoluteTransitionDuration:(double)arg3 toViewController:(UIViewController *)arg4;
@end

