//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UILabel.h>

__attribute__((visibility("hidden")))
@interface _UIActivityGroupActivityCellTitleLabel : UILabel
{
}

- (void)setText:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1 sizeCategory:(id)arg2;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateFontWithSizeCategory:(id)arg1;

@end

