//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet, NSString;

__attribute__((visibility("hidden")))
@interface _UIStatisticsScalarHistogram : NSObject
{
    NSString *_baseKey;
    long long _recordCount;
    unsigned long long _values[22];
    NSString *_keys[22];
    NSMutableSet *_children;
}

- (void).cxx_destruct;
- (void)_addChildStatistic:(id)arg1;
- (void)clearValues;
- (id)initWithDomain:(id)arg1 identifierReporting:(long long)arg2;
- (void)recordValue:(double)arg1;
- (void)reportValues;

@end

