//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <HomeUI/NSObject-Protocol.h>

@class HMCameraClip, NAFuture, NSDate;
@protocol HFHomeKitObject;

@protocol HUHomeKitObjectPresenting <NSObject>
- (NAFuture *)presentHomeKitObject:(id<HFHomeKitObject>)arg1 destination:(unsigned long long)arg2 animated:(BOOL)arg3;

@optional
- (NAFuture *)presentCameraProfile:(id<HFHomeKitObject>)arg1 forCameraClip:(HMCameraClip *)arg2 animated:(BOOL)arg3;
- (NAFuture *)presentCameraProfile:(id<HFHomeKitObject>)arg1 startDate:(NSDate *)arg2 endDate:(NSDate *)arg3 animated:(BOOL)arg4;
@end

