//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <HomeKit/HMAccessoryProfile.h>

@class HMCameraAudioControl, HMCameraClipManager, HMCameraSettingsControl, HMCameraSnapshotControl, HMCameraStreamControl, HMCameraUserSettings, _HMCameraProfile;
@protocol HMCameraProfileUserSettingsDelegate;

@interface HMCameraProfile : HMAccessoryProfile
{
    HMCameraStreamControl *_streamControl;
    HMCameraSnapshotControl *_snapshotControl;
    HMCameraSettingsControl *_settingsControl;
    HMCameraAudioControl *_speakerControl;
    HMCameraAudioControl *_microphoneControl;
    id<HMCameraProfileUserSettingsDelegate> _userSettingsDelegate;
}

@property (readonly, nonatomic) _HMCameraProfile *cameraProfile;
@property (readonly) HMCameraClipManager *clipManager;
@property (strong, nonatomic) HMCameraAudioControl *microphoneControl; // @synthesize microphoneControl=_microphoneControl;
@property (strong, nonatomic) HMCameraSettingsControl *settingsControl; // @synthesize settingsControl=_settingsControl;
@property (strong, nonatomic) HMCameraSnapshotControl *snapshotControl; // @synthesize snapshotControl=_snapshotControl;
@property (strong, nonatomic) HMCameraAudioControl *speakerControl; // @synthesize speakerControl=_speakerControl;
@property (strong, nonatomic) HMCameraStreamControl *streamControl; // @synthesize streamControl=_streamControl;
@property (readonly) HMCameraUserSettings *userSettings;
@property (weak) id<HMCameraProfileUserSettingsDelegate> userSettingsDelegate; // @synthesize userSettingsDelegate=_userSettingsDelegate;

- (void).cxx_destruct;
- (BOOL)_mergeWithNewObject:(id)arg1 operations:(id)arg2;
- (void)deleteAllClipsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithCameraProfile:(id)arg1;
- (id)services;

@end

