//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <HomeKit/NSCopying-Protocol.h>

@interface HMHomeManagerConfiguration : NSObject <NSCopying>
{
    BOOL _shouldConnect;
    unsigned long long _cachePolicy;
    unsigned long long _options;
}

@property (nonatomic) unsigned long long cachePolicy; // @synthesize cachePolicy=_cachePolicy;
@property (readonly, nonatomic) unsigned long long options; // @synthesize options=_options;
@property (nonatomic) BOOL shouldConnect; // @synthesize shouldConnect=_shouldConnect;

+ (id)defaultConfiguration;
+ (id)defaultPrivateConfiguration;
- (BOOL)canUseCache;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)initWithOptions:(unsigned long long)arg1 cachePolicy:(unsigned long long)arg2;

@end

