//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <HomeKit/HMCharacteristicThresholdRangeEvent.h>

@class HMCharacteristic, HMNumberRange;

@interface HMMutableCharacteristicThresholdRangeEvent : HMCharacteristicThresholdRangeEvent
{
}

@property (strong, nonatomic) HMCharacteristic *characteristic; // @dynamic characteristic;
@property (copy, nonatomic) HMNumberRange *thresholdRange; // @dynamic thresholdRange;

@end

