//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <HomeKit/NSCopying-Protocol.h>

@class NSData;

@interface HMPBNaturalLightingAction : PBCodable <NSCopying>
{
    NSData *_lightProfileUUID;
    NSData *_uuid;
    BOOL _naturalLightingEnabled;
    struct {
        unsigned int naturalLightingEnabled:1;
    } _has;
}

@property (readonly, nonatomic) BOOL hasLightProfileUUID;
@property (nonatomic) BOOL hasNaturalLightingEnabled;
@property (readonly, nonatomic) BOOL hasUuid;
@property (strong, nonatomic) NSData *lightProfileUUID; // @synthesize lightProfileUUID=_lightProfileUUID;
@property (nonatomic) BOOL naturalLightingEnabled; // @synthesize naturalLightingEnabled=_naturalLightingEnabled;
@property (strong, nonatomic) NSData *uuid; // @synthesize uuid=_uuid;

- (void).cxx_destruct;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;

@end

