//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MLModelErrorUtils : NSObject
{
}

+ (id)IOErrorWithString:(id)arg1;
+ (id)errorWithCode:(long long)arg1 format:(id)arg2 args:(struct __va_list_tag [1])arg3;
+ (id)errorWithCode:(long long)arg1 string:(id)arg2;
+ (id)featureTypeErrorWithString:(id)arg1;
+ (id)genericErrorWithString:(id)arg1;

@end

