//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (NSStringDrawing)
+ (double)defaultBaselineOffsetForFont:(id)arg1;
+ (double)defaultLineHeightForFont:(id)arg1;
+ (float)hyphenationFactor;
+ (void)setHyphenationFactor:(float)arg1;
+ (void)setShowsControlCharacters:(BOOL)arg1;
+ (void)setShowsInvisibleCharacters:(BOOL)arg1;
+ (void)setTypesetterBehavior:(long long)arg1;
+ (void)setUsesFontLeading:(BOOL)arg1;
+ (void)setUsesScreenFonts:(BOOL)arg1;
+ (BOOL)showsControlCharacters;
+ (BOOL)showsInvisibleCharacters;
+ (long long)typesetterBehavior;
+ (BOOL)usesFontLeading;
+ (BOOL)usesScreenFonts;
- (struct CGSize)_sizeWithSize:(struct CGSize)arg1 attributes:(id)arg2;
- (struct CGRect)boundingRectWithSize:(struct CGSize)arg1 options:(long long)arg2 attributes:(id)arg3;
- (struct CGRect)boundingRectWithSize:(struct CGSize)arg1 options:(long long)arg2 attributes:(id)arg3 context:(id)arg4;
- (void)drawAtPoint:(struct CGPoint)arg1 withAttributes:(id)arg2;
- (void)drawInRect:(struct CGRect)arg1 withAttributes:(id)arg2;
- (void)drawWithRect:(struct CGRect)arg1 options:(long long)arg2 attributes:(id)arg3;
- (void)drawWithRect:(struct CGRect)arg1 options:(long long)arg2 attributes:(id)arg3 context:(id)arg4;
- (BOOL)hasColorGlyphsInRange:(struct _NSRange)arg1 attributes:(id)arg2;
- (struct CGSize)sizeWithAttributes:(id)arg1;
- (id)stringByStrippingLeadingAndTrailingWhitespaceAndQuotes;
@end

