//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PhotoLibraryServices/PLCloudScenarioProducer.h>

@class NSObject, PLCloudPhotoLibraryManager, PLPhotoLibrary;
@protocol OS_dispatch_queue;

@interface PLCloudLegacyPruneAgent : PLCloudScenarioProducer
{
    long long _lastPruneRequest;
    NSObject<OS_dispatch_queue> *_agentQueue;
    CDStruct_691a9b3b _walkStatus[7];
    PLPhotoLibrary *_localLibrary;
    PLCloudPhotoLibraryManager *_remoteLibrary;
}

@property (strong) PLPhotoLibrary *localLibrary; // @synthesize localLibrary=_localLibrary;
@property (strong) PLCloudPhotoLibraryManager *remoteLibrary; // @synthesize remoteLibrary=_remoteLibrary;

- (void)_beginPruningResourcesOfType:(unsigned long long)arg1 withFetchRequest:(id)arg2 startingAtOffset:(unsigned long long)arg3 then:(CDUnknownBlockType)arg4;
- (void)_runOnAgentQueueWithTransaction:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)_runOnAgentQueueWithTransaction:(id)arg1 delay:(double)arg2 block:(CDUnknownBlockType)arg3;
- (void)activate;
- (unsigned long long)batchSize;
- (void)beginPruningResourcesOfType:(unsigned long long)arg1 withFetchRequest:(id)arg2 then:(CDUnknownBlockType)arg3;
- (void)cplResourcesForFetchRequest:(id)arg1 ofType:(unsigned long long)arg2 startingAtOffset:(unsigned long long)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)dealloc;
- (void)emergencyPrune;
- (id)init;
- (void)pruneOlderMediums;
- (void)pruneOlderOriginals;
- (void)pruneResources;
- (void)pruneResources:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)pruneResourcesOfType:(unsigned long long)arg1 createdBeforeDate:(id)arg2 then:(CDUnknownBlockType)arg3;
- (void)pruneResourcesOfType:(unsigned long long)arg1 then:(CDUnknownBlockType)arg2;
- (BOOL)pruningEnabled;
- (void)resetWalkStatus;
- (void)runningCloudMaintenance:(id)arg1;
- (void)settingsChanged:(id)arg1;
- (BOOL)spaceAvailable:(long long *)arg1 totalSpace:(long long *)arg2;
- (void)systemStarted:(id)arg1;
- (int)typeToIndex:(unsigned long long)arg1;

@end

