//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FrontBoard/NSCopying-Protocol.h>
#import <FrontBoard/NSMutableCopying-Protocol.h>

@class NSMutableIndexSet, NSSet;

@interface FBWorkspaceConnectionsState : NSObject <NSCopying, NSMutableCopying>
{
    NSMutableIndexSet *_pidSet;
}

@property (readonly, nonatomic) unsigned long long serializedDataLength;
@property (readonly, copy, nonatomic) NSSet *workspaceIdentities;

+ (id)deserializeLength:(out unsigned long long *)arg1 fromReader:(CDUnknownBlockType)arg2;
+ (unsigned long long)minimumSerializedDataLength;
- (void).cxx_destruct;
- (id)_initWithIndexSet:(id)arg1;
- (id)copy;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned long long)hash;
- (id)init;
- (BOOL)isEqual:(id)arg1;
- (id)mutableCopy;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (long long)serializeToWriter:(CDUnknownBlockType)arg1;

@end

