//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FrontBoard/BSDescriptionProviding-Protocol.h>
#import <FrontBoard/FBSSceneAgentProxy-Protocol.h>
#import <FrontBoard/FBSSceneHandle-Protocol.h>
#import <FrontBoard/FBSceneClient-Protocol.h>
#import <FrontBoard/FBWorkspaceServerSceneEventHandler-Protocol.h>

@class FBSSceneClientSettings, FBSSceneSettings, FBSSceneSpecification, FBSSerialQueue, FBWorkspace, NSMutableArray, NSString;
@protocol FBSSceneHostAgent, FBSceneHost, OS_dispatch_queue;

@interface FBWorkspaceScene : NSObject <FBWorkspaceServerSceneEventHandler, FBSSceneHandle, FBSSceneAgentProxy, BSDescriptionProviding, FBSceneClient>
{
    id<FBSceneHost> _host;
    FBWorkspace *_workspace;
    NSObject<OS_dispatch_queue> *_workspaceQueue;
    NSString *_identifier;
    FBSSceneSpecification *_specification;
    FBSSceneSettings *_settings;
    FBSSceneClientSettings *_clientSettings;
    BOOL _handledInitialSettingsDiff;
    BOOL _sentCreationEvent;
    BOOL _invalidated;
    id<FBSSceneHostAgent> _hostAgent;
    FBSSerialQueue *_agentQueue;
    CDUnknownBlockType _agentMessageHandler;
    unsigned long long _agentEventSequenceNumber;
    NSMutableArray *_agentOutstandingEventSequence;
    NSMutableArray *_agentSessions;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, getter=_workspaceQueue_handledInitialSettingsDiff, setter=_workspaceQueue_setHandledInitialSettingsDiff:) BOOL handledInitialSettingsDiff; // @synthesize handledInitialSettingsDiff=_handledInitialSettingsDiff;
@property (readonly) unsigned long long hash;
@property (readonly, weak, nonatomic) id<FBSceneHost> host; // @synthesize host=_host;
@property (readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property (readonly, weak, nonatomic) FBWorkspace *parentWorkspace; // @synthesize parentWorkspace=_workspace;
@property (copy, nonatomic, getter=_workspaceQueue_sceneSettings, setter=_workspaceQueue_setSceneSettings:) FBSSceneSettings *sceneSettings; // @synthesize sceneSettings=_settings;
@property (nonatomic, getter=_workspaceQueue_hasSentCreationEvent, setter=_workspaceQueue_setSentCreationEvent:) BOOL sentCreationEvent; // @synthesize sentCreationEvent=_sentCreationEvent;
@property (readonly, copy, nonatomic) FBSSceneSettings *settings;
@property (readonly, copy, nonatomic) FBSSceneSpecification *specification; // @synthesize specification=_specification;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_handleDidUpdateSettings:(id)arg1 withDiff:(id)arg2 transitionContext:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_handleInvalidationWithTransitionContext:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)_workspaceQueue;
- (void)_workspaceQueue_dispatchClientBlockIfNecessary:(CDUnknownBlockType)arg1 success:(BOOL)arg2;
- (void)_workspaceQueue_invalidate;
- (void)_workspaceQueue_invalidateSceneAgentWithEvent:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)_workspaceQueue_process;
- (void)_workspaceQueue_sendDestroyWithTransitionContext:(id)arg1 responseEventHandler:(CDUnknownBlockType)arg2;
- (void)_workspaceQueue_sendSettingsDiff:(id)arg1 transitionContext:(id)arg2 responseEventHandler:(CDUnknownBlockType)arg3;
- (void)agent:(id)arg1 registerMessageHandler:(CDUnknownBlockType)arg2;
- (void)agent:(id)arg1 sendMessage:(id)arg2 withResponse:(CDUnknownBlockType)arg3;
- (id)callOutQueue;
- (id)clientProcess;
- (void)closeSession:(id)arg1;
- (id)counterpartAgent;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (void)host:(id)arg1 configureWithDefinition:(id)arg2 parameters:(id)arg3;
- (void)host:(id)arg1 didInvalidateWithTransitionContext:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)host:(id)arg1 didReceiveActions:(id)arg2;
- (void)host:(id)arg1 didUpdateSettings:(id)arg2 withDiff:(id)arg3 transitionContext:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (id)hostProcess;
- (id)initWithParentWorkspace:(id)arg1 identifier:(id)arg2;
- (void)invalidate;
- (id)openSessionWithName:(id)arg1 executionPolicy:(id)arg2;
- (id)parameters;
- (void)sceneAttachLayer:(id)arg1;
- (void)sceneDetachLayer:(id)arg1;
- (void)sceneDidReceiveActions:(id)arg1;
- (void)sceneDidReceiveMessage:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)sceneDidUpdateClientSettings:(id)arg1;
- (void)sceneUpdateLayer:(id)arg1;
- (id)sessionForIdentifier:(id)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;

@end

