//
//     Generated by class-dump 3.5-MH (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FrontBoard/NSObject-Protocol.h>

@class FBSceneClientHandshake;

@protocol FBWorkspaceEventDispatcherTarget <NSObject>
- (void)didReceiveHandshake:(FBSceneClientHandshake *)arg1;
@end

